import type { Deliverable, Task, AssignedUser } from "./types";

// ── Users ──────────────────────────────────────────────────────────────────
export const MOCK_USERS: AssignedUser[] = [
  { id: "u1", name: "Jessica Reyes",   initials: "JR", avatarColor: "#1B4FD8"},
  { id: "u2", name: "Marcus Webb",     initials: "MW", avatarColor: "#059669"},
  { id: "u3", name: "Priya Nair",      initials: "PN", avatarColor: "#7C3AED"},
  { id: "u4", name: "Daniel Okonkwo",  initials: "DO", avatarColor: "#D97706"},
  { id: "u5", name: "Sofia Castillo",  initials: "SC", avatarColor: "#DC2626"},
  { id: "u6", name: "Aaron Park",      initials: "AP", avatarColor: "#0891B2"},
  { id: "u7", name: "Lily Chen",       initials: "LC", avatarColor: "#BE185D"},
  { id: "u8", name: "Ryan Torres",     initials: "RT", avatarColor: "#065F46"},
];

const [jess, marcus, priya, daniel, sofia, aaron, lily, ryan] = MOCK_USERS;

// ── Deliverables with embedded tasks ──────────────────────────────────────
export const MOCK_DELIVERABLES: Deliverable[] = [
  // ── D1: Q3 SEO Overhaul ──────────────────────────────────────────────
  {
    id: "d1",
    title: "Q3 SEO Overhaul",
    description: "Comprehensive SEO audit, keyword refresh, and on-page optimisation across 12 client sites.",
    status: "In Progress",
    priority: "High",
    department: "SEO",
    owner: priya,
    assignees: [priya, marcus],
    startDate: "2025-07-01",
    dueDate: "2025-08-15",
    tags: ["seo", "q3"],
    blockers: [],
    notes: [
      {
        id: "n1",
        authorId: "u3",
        authorName: "Priya Nair",
        body: "Waiting on keyword research tool renewal before completing audit phase.",
        createdAt: "2025-07-10T09:00:00Z",
      },
    ],
    createdAt: "2025-06-25T08:00:00Z",
    updatedAt: "2025-07-10T09:00:00Z",
    tasks: [
      {
        id: "t1",
        deliverableId: "d1",
        title: "Keyword gap analysis for all 12 clients",
        description: "Run Semrush gap analysis vs. top 3 competitors per client.",
        status: "Done",
        priority: "High",
        department: "SEO",
        assignees: [priya],
        startDate: "2025-07-01",
        dueDate: "2025-07-07",
        blockers: [],
        notes: [],
        tags: ["seo", "research"],
        createdAt: "2025-06-25T08:00:00Z",
        updatedAt: "2025-07-07T17:00:00Z",
      },
      {
        id: "t2",
        deliverableId: "d1",
        title: "On-page meta & heading updates",
        description: "Update titles, H1s, and meta descriptions per new keyword map.",
        status: "In Progress",
        priority: "High",
        department: "SEO",
        assignees: [priya, marcus],
        startDate: "2025-07-08",
        dueDate: "2025-07-25",
        blockers: [],
        notes: [],
        tags: ["seo", "on-page"],
        createdAt: "2025-07-01T08:00:00Z",
        updatedAt: "2025-07-14T10:00:00Z",
      },
      {
        id: "t3",
        deliverableId: "d1",
        title: "Technical audit & Core Web Vitals fixes",
        description: "Resolve CLS, LCP, and crawl issues flagged in Screaming Frog.",
        status: "Pending",
        priority: "Medium",
        department: "SEO",
        assignees: [marcus],
        startDate: "2025-07-26",
        dueDate: "2025-08-08",
        blockers: [],
        notes: [],
        tags: ["seo", "technical"],
        createdAt: "2025-07-01T08:00:00Z",
        updatedAt: "2025-07-01T08:00:00Z",
      },
      {
        id: "t4",
        deliverableId: "d1",
        title: "Monthly SEO report delivery",
        description: "Compile and send client-facing SEO performance report.",
        status: "Pending",
        priority: "Low",
        department: "SEO",
        assignees: [priya],
        startDate: "2025-08-09",
        dueDate: "2025-08-15",
        blockers: [],
        notes: [],
        tags: ["seo", "reporting"],
        createdAt: "2025-07-01T08:00:00Z",
        updatedAt: "2025-07-01T08:00:00Z",
      },
    ],
  },

  // ── D2: Client Onboarding Refresh ────────────────────────────────────
  {
    id: "d2",
    title: "Client Onboarding Refresh",
    description: "Redesign new-client onboarding flow including welcome email, intake form, and first-30-day checklist.",
    status: "In Review",
    priority: "Critical",
    department: "Account Management",
    owner: jess,
    assignees: [jess, daniel, lily],
    startDate: "2025-06-15",
    dueDate: "2025-07-31",
    tags: ["onboarding", "cx"],
    blockers: [
      {
        id: "b1",
        description: "Legal sign-off on updated SLA language in welcome packet pending.",
        raisedAt: "2025-07-05T14:00:00Z",
      },
    ],
    notes: [
      {
        id: "n2",
        authorId: "u1",
        authorName: "Jessica Reyes",
        body: "Design mockups approved by AM leadership. Waiting on legal before final publish.",
        createdAt: "2025-07-12T11:30:00Z",
      },
    ],
    createdAt: "2025-06-10T08:00:00Z",
    updatedAt: "2025-07-12T11:30:00Z",
    tasks: [
      {
        id: "t5",
        deliverableId: "d2",
        title: "Redesign welcome email sequence (5 emails)",
        status: "Done",
        priority: "High",
        department: "Content",
        assignees: [lily],
        startDate: "2025-06-15",
        dueDate: "2025-06-28",
        blockers: [],
        notes: [],
        tags: ["email", "content"],
        createdAt: "2025-06-10T08:00:00Z",
        updatedAt: "2025-06-29T16:00:00Z",
      },
      {
        id: "t6",
        deliverableId: "d2",
        title: "Update client intake form",
        status: "Done",
        priority: "Medium",
        department: "Account Management",
        assignees: [jess],
        startDate: "2025-06-20",
        dueDate: "2025-07-04",
        blockers: [],
        notes: [],
        tags: ["form", "intake"],
        createdAt: "2025-06-10T08:00:00Z",
        updatedAt: "2025-07-05T09:00:00Z",
      },
      {
        id: "t7",
        deliverableId: "d2",
        title: "Build first-30-day checklist template",
        status: "In Review",
        priority: "High",
        department: "Account Management",
        assignees: [jess, daniel],
        startDate: "2025-07-05",
        dueDate: "2025-07-20",
        blockers: [],
        notes: [],
        tags: ["template"],
        createdAt: "2025-06-10T08:00:00Z",
        updatedAt: "2025-07-14T08:00:00Z",
      },
      {
        id: "t8",
        deliverableId: "d2",
        title: "Legal review of updated SLA language",
        status: "Blocked",
        priority: "Critical",
        department: "Account Management",
        assignees: [jess],
        startDate: "2025-07-05",
        dueDate: "2025-07-31",
        blockers: [
          {
            id: "b2",
            description: "Legal team unavailable until week of July 21.",
            raisedAt: "2025-07-08T09:00:00Z",
          },
        ],
        notes: [],
        tags: ["legal"],
        createdAt: "2025-07-05T08:00:00Z",
        updatedAt: "2025-07-08T09:00:00Z",
      },
    ],
  },

  // ── D3: Meta Ads Creative Refresh ────────────────────────────────────
  {
    id: "d3",
    title: "Meta Ads Creative Refresh — August",
    description: "Produce new static and video ad creatives for 8 active client campaigns ahead of August budget cycle.",
    status: "In Progress",
    priority: "High",
    department: "Meta Ads & PPC",
    owner: sofia,
    assignees: [sofia, aaron, lily],
    startDate: "2025-07-10",
    dueDate: "2025-07-28",
    tags: ["ads", "design", "creative"],
    blockers: [],
    notes: [],
    createdAt: "2025-07-05T08:00:00Z",
    updatedAt: "2025-07-14T08:00:00Z",
    tasks: [
      {
        id: "t9",
        deliverableId: "d3",
        title: "Creative brief for all 8 clients",
        status: "Done",
        priority: "High",
        department: "Meta Ads & PPC",
        assignees: [sofia],
        startDate: "2025-07-10",
        dueDate: "2025-07-13",
        blockers: [],
        notes: [],
        tags: ["brief"],
        createdAt: "2025-07-05T08:00:00Z",
        updatedAt: "2025-07-13T17:00:00Z",
      },
      {
        id: "t10",
        deliverableId: "d3",
        title: "Design static banner sets (1200×628, 1080×1080)",
        status: "In Progress",
        priority: "High",
        department: "Design",
        assignees: [lily, aaron],
        startDate: "2025-07-14",
        dueDate: "2025-07-21",
        blockers: [],
        notes: [],
        tags: ["design", "banners"],
        createdAt: "2025-07-05T08:00:00Z",
        updatedAt: "2025-07-14T10:00:00Z",
      },
      {
        id: "t11",
        deliverableId: "d3",
        title: "Produce Reels/video ad (15-sec)",
        status: "Pending",
        priority: "Medium",
        department: "Design",
        assignees: [lily],
        startDate: "2025-07-22",
        dueDate: "2025-07-26",
        blockers: [],
        notes: [],
        tags: ["video", "reels"],
        createdAt: "2025-07-05T08:00:00Z",
        updatedAt: "2025-07-05T08:00:00Z",
      },
      {
        id: "t12",
        deliverableId: "d3",
        title: "Upload creatives & configure A/B test",
        status: "Pending",
        priority: "High",
        department: "Meta Ads & PPC",
        assignees: [sofia, aaron],
        startDate: "2025-07-27",
        dueDate: "2025-07-28",
        blockers: [],
        notes: [],
        tags: ["ads", "ab-test"],
        createdAt: "2025-07-05T08:00:00Z",
        updatedAt: "2025-07-05T08:00:00Z",
      },
    ],
  },

  // ── D4: Billing Reconciliation ────────────────────────────────────────
  {
    id: "d4",
    title: "July Billing Reconciliation",
    description: "Reconcile all July invoices, flag overdue accounts, and send renewal notices.",
    status: "Pending",
    priority: "Medium",
    department: "Billing",
    owner: daniel,
    assignees: [daniel],
    startDate: "2025-07-29",
    dueDate: "2025-08-05",
    tags: ["billing", "finance"],
    blockers: [],
    notes: [],
    createdAt: "2025-07-15T08:00:00Z",
    updatedAt: "2025-07-15T08:00:00Z",
    tasks: [
      {
        id: "t13",
        deliverableId: "d4",
        title: "Export July invoice report",
        status: "Pending",
        priority: "Medium",
        department: "Billing",
        assignees: [daniel],
        startDate: "2025-07-29",
        dueDate: "2025-07-30",
        blockers: [],
        notes: [],
        tags: ["billing"],
        createdAt: "2025-07-15T08:00:00Z",
        updatedAt: "2025-07-15T08:00:00Z",
      },
      {
        id: "t14",
        deliverableId: "d4",
        title: "Flag & contact overdue accounts",
        status: "Pending",
        priority: "High",
        department: "Billing",
        assignees: [daniel],
        startDate: "2025-07-31",
        dueDate: "2025-08-01",
        blockers: [],
        notes: [],
        tags: ["billing", "overdue"],
        createdAt: "2025-07-15T08:00:00Z",
        updatedAt: "2025-07-15T08:00:00Z",
      },
      {
        id: "t15",
        deliverableId: "d4",
        title: "Send renewal notices for expiring contracts",
        status: "Pending",
        priority: "Medium",
        department: "Billing",
        assignees: [daniel],
        startDate: "2025-08-02",
        dueDate: "2025-08-05",
        blockers: [],
        notes: [],
        tags: ["billing", "renewals"],
        createdAt: "2025-07-15T08:00:00Z",
        updatedAt: "2025-07-15T08:00:00Z",
      },
    ],
  },

  // ── D5: IT Security Hardening ─────────────────────────────────────────
  {
    id: "d5",
    title: "Infrastructure Security Hardening",
    description: "Audit server configs, enforce MFA on all admin accounts, update SSL certs.",
    status: "Blocked",
    priority: "Critical",
    department: "IT & Security",
    owner: ryan,
    assignees: [ryan, aaron],
    startDate: "2025-07-01",
    dueDate: "2025-07-31",
    tags: ["security", "infra"],
    blockers: [
      {
        id: "b3",
        description: "Vendor access credentials for legacy server not yet provided by client.",
        raisedAt: "2025-07-03T10:00:00Z",
      },
    ],
    notes: [
      {
        id: "n3",
        authorId: "u8",
        authorName: "Ryan Torres",
        body: "Escalated to client success team on July 5. Still awaiting credentials from client.",
        createdAt: "2025-07-09T15:00:00Z",
      },
    ],
    createdAt: "2025-06-28T08:00:00Z",
    updatedAt: "2025-07-09T15:00:00Z",
    tasks: [
      {
        id: "t16",
        deliverableId: "d5",
        title: "MFA enforcement on all admin accounts",
        status: "Done",
        priority: "Critical",
        department: "IT & Security",
        assignees: [ryan],
        startDate: "2025-07-01",
        dueDate: "2025-07-07",
        blockers: [],
        notes: [],
        tags: ["mfa", "security"],
        createdAt: "2025-06-28T08:00:00Z",
        updatedAt: "2025-07-07T17:00:00Z",
      },
      {
        id: "t17",
        deliverableId: "d5",
        title: "SSL certificate renewal for 6 domains",
        status: "Done",
        priority: "High",
        department: "IT & Security",
        assignees: [ryan, aaron],
        startDate: "2025-07-08",
        dueDate: "2025-07-12",
        blockers: [],
        notes: [],
        tags: ["ssl"],
        createdAt: "2025-06-28T08:00:00Z",
        updatedAt: "2025-07-12T16:00:00Z",
      },
      {
        id: "t18",
        deliverableId: "d5",
        title: "Legacy server audit & config hardening",
        status: "Blocked",
        priority: "Critical",
        department: "IT & Security",
        assignees: [ryan],
        startDate: "2025-07-13",
        dueDate: "2025-07-31",
        blockers: [
          {
            id: "b4",
            description: "Credentials from client not received.",
            raisedAt: "2025-07-03T10:00:00Z",
          },
        ],
        notes: [],
        tags: ["server", "audit"],
        createdAt: "2025-06-28T08:00:00Z",
        updatedAt: "2025-07-09T15:00:00Z",
      },
    ],
  },

  // ── D6: Content Calendar — August ────────────────────────────────────
  {
    id: "d6",
    title: "August Content Calendar",
    description: "Plan and produce blog posts, social captions, and email newsletters for August.",
    status: "In Progress",
    priority: "Medium",
    department: "Content",
    owner: lily,
    assignees: [lily, marcus],
    startDate: "2025-07-14",
    dueDate: "2025-07-27",
    tags: ["content", "calendar"],
    blockers: [],
    notes: [],
    createdAt: "2025-07-08T08:00:00Z",
    updatedAt: "2025-07-14T08:00:00Z",
    tasks: [
      {
        id: "t19",
        deliverableId: "d6",
        title: "Draft August editorial calendar",
        status: "Done",
        priority: "Medium",
        department: "Content",
        assignees: [lily],
        startDate: "2025-07-14",
        dueDate: "2025-07-16",
        blockers: [],
        notes: [],
        tags: ["planning"],
        createdAt: "2025-07-08T08:00:00Z",
        updatedAt: "2025-07-16T17:00:00Z",
      },
      {
        id: "t20",
        deliverableId: "d6",
        title: "Write 4 blog posts",
        status: "In Progress",
        priority: "Medium",
        department: "Content",
        assignees: [lily, marcus],
        startDate: "2025-07-17",
        dueDate: "2025-07-23",
        blockers: [],
        notes: [],
        tags: ["blog"],
        createdAt: "2025-07-08T08:00:00Z",
        updatedAt: "2025-07-17T09:00:00Z",
      },
      {
        id: "t21",
        deliverableId: "d6",
        title: "Write social captions (30 posts)",
        status: "Pending",
        priority: "Low",
        department: "Content",
        assignees: [marcus],
        startDate: "2025-07-24",
        dueDate: "2025-07-26",
        blockers: [],
        notes: [],
        tags: ["social"],
        createdAt: "2025-07-08T08:00:00Z",
        updatedAt: "2025-07-08T08:00:00Z",
      },
      {
        id: "t22",
        deliverableId: "d6",
        title: "Email newsletter copy",
        status: "Pending",
        priority: "Medium",
        department: "Content",
        assignees: [lily],
        startDate: "2025-07-25",
        dueDate: "2025-07-27",
        blockers: [],
        notes: [],
        tags: ["email"],
        createdAt: "2025-07-08T08:00:00Z",
        updatedAt: "2025-07-08T08:00:00Z",
      },
    ],
  },

  // ── D7: Q3 Sales Pipeline Push ────────────────────────────────────────
  {
    id: "d7",
    title: "Q3 Sales Pipeline Push",
    description: "Close 8 new retainer accounts before end of Q3.",
    status: "In Progress",
    priority: "High",
    department: "Sales",
    owner: daniel,
    assignees: [daniel, aaron],
    startDate: "2025-07-01",
    dueDate: "2025-09-30",
    tags: ["sales", "q3"],
    blockers: [],
    notes: [],
    createdAt: "2025-06-25T08:00:00Z",
    updatedAt: "2025-07-10T09:00:00Z",
    tasks: [
      {
        id: "t23",
        deliverableId: "d7",
        title: "Update CRM pipeline for all Q3 leads",
        status: "Done",
        priority: "High",
        department: "Sales",
        assignees: [daniel],
        startDate: "2025-07-01",
        dueDate: "2025-07-05",
        blockers: [],
        notes: [],
        tags: ["crm"],
        createdAt: "2025-06-25T08:00:00Z",
        updatedAt: "2025-07-05T17:00:00Z",
      },
      {
        id: "t24",
        deliverableId: "d7",
        title: "Send discovery call invites to 20 warm leads",
        status: "In Progress",
        priority: "High",
        department: "Sales",
        assignees: [daniel, aaron],
        startDate: "2025-07-06",
        dueDate: "2025-07-20",
        blockers: [],
        notes: [],
        tags: ["outreach"],
        createdAt: "2025-07-01T08:00:00Z",
        updatedAt: "2025-07-14T10:00:00Z",
      },
      {
        id: "t25",
        deliverableId: "d7",
        title: "Prepare and deliver 8 proposals",
        status: "Pending",
        priority: "Critical",
        department: "Sales",
        assignees: [daniel],
        startDate: "2025-07-21",
        dueDate: "2025-08-15",
        blockers: [],
        notes: [],
        tags: ["proposals"],
        createdAt: "2025-07-01T08:00:00Z",
        updatedAt: "2025-07-01T08:00:00Z",
      },
    ],
  },

  // ── D8: Monthly Reporting Package ────────────────────────────────────
  {
    id: "d8",
    title: "July Monthly Reporting Package",
    description: "Compile performance reports for all active clients for July.",
    status: "In Progress",
    priority: "High",
    department: "Reporting",
    owner: ryan,
    assignees: [ryan, sofia],
    startDate: "2025-07-28",
    dueDate: "2025-08-05",
    tags: ["reporting", "monthly"],
    blockers: [],
    notes: [],
    createdAt: "2025-07-20T08:00:00Z",
    updatedAt: "2025-07-28T08:00:00Z",
    tasks: [
      {
        id: "t26",
        deliverableId: "d8",
        title: "Pull GA4 and GSC data for all clients",
        status: "In Progress",
        priority: "High",
        department: "Reporting",
        assignees: [ryan],
        startDate: "2025-07-28",
        dueDate: "2025-07-30",
        blockers: [],
        notes: [],
        tags: ["analytics"],
        createdAt: "2025-07-20T08:00:00Z",
        updatedAt: "2025-07-28T09:00:00Z",
      },
      {
        id: "t27",
        deliverableId: "d8",
        title: "Compile ad performance summaries",
        status: "Pending",
        priority: "High",
        department: "Reporting",
        assignees: [sofia],
        startDate: "2025-07-31",
        dueDate: "2025-08-02",
        blockers: [],
        notes: [],
        tags: ["ads"],
        createdAt: "2025-07-20T08:00:00Z",
        updatedAt: "2025-07-20T08:00:00Z",
      },
      {
        id: "t28",
        deliverableId: "d8",
        title: "Send reports to all clients",
        status: "Pending",
        priority: "High",
        department: "Reporting",
        assignees: [ryan],
        startDate: "2025-08-04",
        dueDate: "2025-08-05",
        blockers: [],
        notes: [],
        tags: ["delivery"],
        createdAt: "2025-07-20T08:00:00Z",
        updatedAt: "2025-07-20T08:00:00Z",
      },
    ],
  },

  // ── D9: LSA Campaign Setup ────────────────────────────────────────────
  {
    id: "d9",
    title: "LSA Campaign Setup — 3 New Clients",
    description: "Set up Local Service Ads for Blue Ridge Plumbing, Harbor Auto, and Summit Landscaping.",
    status: "In Progress",
    priority: "High",
    department: "Local Service Ads",
    owner: aaron,
    assignees: [aaron, jess],
    startDate: "2025-07-07",
    dueDate: "2025-07-31",
    tags: ["lsa", "setup"],
    blockers: [],
    notes: [],
    createdAt: "2025-07-01T08:00:00Z",
    updatedAt: "2025-07-14T09:00:00Z",
    tasks: [
      {
        id: "t29",
        deliverableId: "d9",
        title: "Submit business verification docs for Blue Ridge",
        status: "In Progress",
        priority: "Critical",
        department: "Local Service Ads",
        assignees: [aaron],
        startDate: "2025-07-07",
        dueDate: "2025-07-14",
        blockers: [],
        notes: [],
        tags: ["verification"],
        createdAt: "2025-07-01T08:00:00Z",
        updatedAt: "2025-07-10T11:00:00Z",
      },
      {
        id: "t30",
        deliverableId: "d9",
        title: "Configure ad budget and service areas for Harbor Auto",
        status: "Pending",
        priority: "High",
        department: "Local Service Ads",
        assignees: [jess],
        startDate: "2025-07-15",
        dueDate: "2025-07-22",
        blockers: [],
        notes: [],
        tags: ["setup"],
        createdAt: "2025-07-01T08:00:00Z",
        updatedAt: "2025-07-01T08:00:00Z",
      },
      {
        id: "t31",
        deliverableId: "d9",
        title: "QA and launch all 3 LSA campaigns",
        status: "Pending",
        priority: "High",
        department: "Local Service Ads",
        assignees: [aaron, jess],
        startDate: "2025-07-23",
        dueDate: "2025-07-31",
        blockers: [],
        notes: [],
        tags: ["launch"],
        createdAt: "2025-07-01T08:00:00Z",
        updatedAt: "2025-07-01T08:00:00Z",
      },
    ],
  },
];

// ── Flat list of all tasks (derived) ──────────────────────────────────────
export const ALL_TASKS: Task[] = MOCK_DELIVERABLES.flatMap((d) => d.tasks);

// ── KPI helpers ───────────────────────────────────────────────────────────
export function getTaskStats(tasks: Task[]) {
  const total = tasks.length;
  const byStatus = {
    Pending:     tasks.filter((t) => t.status === "Pending").length,
    "In Progress": tasks.filter((t) => t.status === "In Progress").length,
    "In Review":  tasks.filter((t) => t.status === "In Review").length,
    Blocked:     tasks.filter((t) => t.status === "Blocked").length,
    Done:        tasks.filter((t) => t.status === "Done").length,
  };
  const overdue = tasks.filter((t) => {
    if (!t.dueDate || t.status === "Done") return false;
    return new Date(t.dueDate) < new Date();
  }).length;
  return { total, byStatus, overdue };
}
