// Workspace-level task mock data
// Each task carries client, service, owner, priority, dueDate, status, and blocker info
// for display in the rich child-workspace task pages.

export type WorkspaceTaskStatus =
  | "Pending"| "In Progress"| "In Review"| "Blocked"| "Done";

export type WorkspaceTaskPriority = "Low"| "Medium"| "High"| "Critical";

export interface WorkspaceTask {
  id: string;
  title: string;
  client: string;
  service: string;
  owner: string;
  priority: WorkspaceTaskPriority;
  dueDate: string;
  status: WorkspaceTaskStatus;
  blocker: string | null; // null = no blocker; string = blocker description
}

// ── SEO ──────────────────────────────────────────────────────────────────
export const SEO_TASKS: WorkspaceTask[] = [
  {
    id: "seo-t1",
    title: "Keyword gap analysis — all 12 clients",
    client: "All Clients",
    service: "SEO Audit",
    owner: "Priya Nair",
    priority: "High",
    dueDate: "2025-07-07",
    status: "Done",
    blocker: null,
  },
  {
    id: "seo-t2",
    title: "On-page meta & heading updates",
    client: "Blue Ridge Plumbing",
    service: "On-Page SEO",
    owner: "Marcus Webb",
    priority: "High",
    dueDate: "2025-07-25",
    status: "In Progress",
    blocker: null,
  },
  {
    id: "seo-t3",
    title: "Technical audit & Core Web Vitals fixes",
    client: "Harbor Auto",
    service: "Technical SEO",
    owner: "Marcus Webb",
    priority: "Medium",
    dueDate: "2025-08-08",
    status: "Pending",
    blocker: null,
  },
  {
    id: "seo-t4",
    title: "Monthly SEO performance report",
    client: "Summit Landscaping",
    service: "SEO Reporting",
    owner: "Priya Nair",
    priority: "Low",
    dueDate: "2025-08-15",
    status: "Pending",
    blocker: null,
  },
  {
    id: "seo-t5",
    title: "Backlink outreach campaign",
    client: "Westside Dental",
    service: "Link Building",
    owner: "Priya Nair",
    priority: "Medium",
    dueDate: "2025-07-30",
    status: "In Review",
    blocker: null,
  },
  {
    id: "seo-t6",
    title: "Schema markup implementation",
    client: "CityLine Fitness",
    service: "Technical SEO",
    owner: "Marcus Webb",
    priority: "High",
    dueDate: "2025-07-18",
    status: "Blocked",
    blocker: "Awaiting CMS access credentials from client.",
  },
];

// ── GBP ──────────────────────────────────────────────────────────────────
export const GBP_TASKS: WorkspaceTask[] = [
  {
    id: "gbp-t1",
    title: "Verify & update NAP info across all profiles",
    client: "All Clients",
    service: "GBP Management",
    owner: "Aaron Park",
    priority: "High",
    dueDate: "2025-07-15",
    status: "Done",
    blocker: null,
  },
  {
    id: "gbp-t2",
    title: "Upload Q3 photo sets to GBP listings",
    client: "Blue Ridge Plumbing",
    service: "GBP Optimization",
    owner: "Sofia Castillo",
    priority: "Medium",
    dueDate: "2025-07-22",
    status: "In Progress",
    blocker: null,
  },
  {
    id: "gbp-t3",
    title: "Respond to new GBP reviews (July batch)",
    client: "Harbor Auto",
    service: "Review Management",
    owner: "Jessica Reyes",
    priority: "High",
    dueDate: "2025-07-20",
    status: "In Review",
    blocker: null,
  },
  {
    id: "gbp-t4",
    title: "Create GBP posts for summer promotions",
    client: "Summit Landscaping",
    service: "GBP Content",
    owner: "Lily Chen",
    priority: "Low",
    dueDate: "2025-07-28",
    status: "Pending",
    blocker: null,
  },
  {
    id: "gbp-t5",
    title: "Fix service area settings — 3 clients",
    client: "Multiple Clients",
    service: "GBP Setup",
    owner: "Aaron Park",
    priority: "High",
    dueDate: "2025-07-17",
    status: "Blocked",
    blocker: "Google verification hold on Harbor Auto profile.",
  },
  {
    id: "gbp-t6",
    title: "Q2 GBP insights report",
    client: "Westside Dental",
    service: "GBP Reporting",
    owner: "Priya Nair",
    priority: "Medium",
    dueDate: "2025-08-01",
    status: "Pending",
    blocker: null,
  },
];

// ── Yelp ─────────────────────────────────────────────────────────────────
export const YELP_TASKS: WorkspaceTask[] = [
  {
    id: "yelp-t1",
    title: "Claim & verify Yelp profiles — 4 new clients",
    client: "Multiple Clients",
    service: "Yelp Setup",
    owner: "Jessica Reyes",
    priority: "High",
    dueDate: "2025-07-14",
    status: "Done",
    blocker: null,
  },
  {
    id: "yelp-t2",
    title: "Respond to flagged 1-star reviews",
    client: "Harbor Auto",
    service: "Reputation Management",
    owner: "Aaron Park",
    priority: "Critical",
    dueDate: "2025-07-16",
    status: "In Progress",
    blocker: null,
  },
  {
    id: "yelp-t3",
    title: "Upload business photos (50+ per profile)",
    client: "Blue Ridge Plumbing",
    service: "Yelp Optimization",
    owner: "Lily Chen",
    priority: "Medium",
    dueDate: "2025-07-24",
    status: "Pending",
    blocker: null,
  },
  {
    id: "yelp-t4",
    title: "Yelp Ads monthly review & budget adjustment",
    client: "CityLine Fitness",
    service: "Yelp Advertising",
    owner: "Sofia Castillo",
    priority: "High",
    dueDate: "2025-07-31",
    status: "In Review",
    blocker: null,
  },
  {
    id: "yelp-t5",
    title: "Update hours & specials — all profiles",
    client: "All Clients",
    service: "Yelp Management",
    owner: "Jessica Reyes",
    priority: "Low",
    dueDate: "2025-08-05",
    status: "Pending",
    blocker: null,
  },
  {
    id: "yelp-t6",
    title: "Investigate Yelp algorithm filter on Summit",
    client: "Summit Landscaping",
    service: "Reputation Management",
    owner: "Aaron Park",
    priority: "High",
    dueDate: "2025-07-19",
    status: "Blocked",
    blocker: "Yelp support ticket #88234 unresolved — awaiting platform response.",
  },
];

// ── Meta Ads ─────────────────────────────────────────────────────────────
export const META_ADS_TASKS: WorkspaceTask[] = [
  {
    id: "meta-t1",
    title: "Creative brief for August campaigns",
    client: "All Clients",
    service: "Meta Ads Strategy",
    owner: "Sofia Castillo",
    priority: "High",
    dueDate: "2025-07-13",
    status: "Done",
    blocker: null,
  },
  {
    id: "meta-t2",
    title: "Design static banner sets (1200×628, 1080×1080)",
    client: "Harbor Auto",
    service: "Creative Production",
    owner: "Lily Chen",
    priority: "High",
    dueDate: "2025-07-21",
    status: "In Progress",
    blocker: null,
  },
  {
    id: "meta-t3",
    title: "Produce Reels/video ad (15-sec)",
    client: "CityLine Fitness",
    service: "Video Production",
    owner: "Aaron Park",
    priority: "Medium",
    dueDate: "2025-07-26",
    status: "Pending",
    blocker: null,
  },
  {
    id: "meta-t4",
    title: "Upload creatives & configure A/B test",
    client: "Blue Ridge Plumbing",
    service: "Meta Ads Management",
    owner: "Sofia Castillo",
    priority: "High",
    dueDate: "2025-07-28",
    status: "Pending",
    blocker: null,
  },
  {
    id: "meta-t5",
    title: "Audience refresh — retargeting pools",
    client: "Westside Dental",
    service: "Meta Ads Strategy",
    owner: "Aaron Park",
    priority: "Medium",
    dueDate: "2025-07-30",
    status: "In Review",
    blocker: null,
  },
  {
    id: "meta-t6",
    title: "Pixel verification & event tracking audit",
    client: "Summit Landscaping",
    service: "Tracking & Analytics",
    owner: "Sofia Castillo",
    priority: "High",
    dueDate: "2025-07-22",
    status: "Blocked",
    blocker: "Client hasn't granted pixel access — email sent 2025-07-10, no reply.",
  },
];

// ── Google Ads ────────────────────────────────────────────────────────────
export const GOOGLE_ADS_TASKS: WorkspaceTask[] = [
  {
    id: "gads-t1",
    title: "Negative keyword list cleanup — Q3",
    client: "All Clients",
    service: "Google Ads Optimization",
    owner: "Aaron Park",
    priority: "High",
    dueDate: "2025-07-10",
    status: "Done",
    blocker: null,
  },
  {
    id: "gads-t2",
    title: "Responsive Search Ads copy refresh",
    client: "Blue Ridge Plumbing",
    service: "Google Ads Creative",
    owner: "Marcus Webb",
    priority: "High",
    dueDate: "2025-07-24",
    status: "In Progress",
    blocker: null,
  },
  {
    id: "gads-t3",
    title: "Smart bidding strategy migration (tCPA → tROAS)",
    client: "Harbor Auto",
    service: "Google Ads Strategy",
    owner: "Sofia Castillo",
    priority: "Critical",
    dueDate: "2025-07-29",
    status: "In Review",
    blocker: null,
  },
  {
    id: "gads-t4",
    title: "Performance Max campaign setup",
    client: "CityLine Fitness",
    service: "Google Ads Setup",
    owner: "Aaron Park",
    priority: "Medium",
    dueDate: "2025-08-05",
    status: "Pending",
    blocker: null,
  },
  {
    id: "gads-t5",
    title: "Conversion tracking audit & fixes",
    client: "Westside Dental",
    service: "Tracking & Analytics",
    owner: "Marcus Webb",
    priority: "High",
    dueDate: "2025-07-20",
    status: "Blocked",
    blocker: "Google Tag Manager access not yet granted by client IT team.",
  },
  {
    id: "gads-t6",
    title: "Monthly Google Ads performance report",
    client: "Summit Landscaping",
    service: "Google Ads Reporting",
    owner: "Sofia Castillo",
    priority: "Low",
    dueDate: "2025-08-07",
    status: "Pending",
    blocker: null,
  },
];

// ── Web Development ───────────────────────────────────────────────────────
export const WEB_DEV_TASKS: WorkspaceTask[] = [
  {
    id: "webdev-t1",
    title: "Website audit & speed optimization",
    client: "Blue Ridge Plumbing",
    service: "Web Development",
    owner: "Ryan Torres",
    priority: "High",
    dueDate: "2025-07-18",
    status: "Done",
    blocker: null,
  },
  {
    id: "webdev-t2",
    title: "Landing page build — summer promo",
    client: "CityLine Fitness",
    service: "Landing Page",
    owner: "Marcus Webb",
    priority: "High",
    dueDate: "2025-07-25",
    status: "In Progress",
    blocker: null,
  },
  {
    id: "webdev-t3",
    title: "E-commerce checkout flow redesign",
    client: "Harbor Auto",
    service: "Web Development",
    owner: "Ryan Torres",
    priority: "Critical",
    dueDate: "2025-08-01",
    status: "In Review",
    blocker: null,
  },
  {
    id: "webdev-t4",
    title: "WordPress plugin updates & security patches",
    client: "Summit Landscaping",
    service: "Web Maintenance",
    owner: "Marcus Webb",
    priority: "Medium",
    dueDate: "2025-07-22",
    status: "Pending",
    blocker: null,
  },
  {
    id: "webdev-t5",
    title: "Form integration — HubSpot CRM",
    client: "Westside Dental",
    service: "Web Development",
    owner: "Ryan Torres",
    priority: "High",
    dueDate: "2025-07-29",
    status: "Blocked",
    blocker: "HubSpot API key not shared by client ops team.",
  },
  {
    id: "webdev-t6",
    title: "Mobile responsiveness fixes — 6 pages",
    client: "Blue Ridge Plumbing",
    service: "Web Development",
    owner: "Marcus Webb",
    priority: "Medium",
    dueDate: "2025-08-06",
    status: "Pending",
    blocker: null,
  },
];

// ── Design ────────────────────────────────────────────────────────────────
export const DESIGN_TASKS: WorkspaceTask[] = [
  {
    id: "design-t1",
    title: "Brand identity refresh — logo & color palette",
    client: "Summit Landscaping",
    service: "Brand Design",
    owner: "Lily Chen",
    priority: "High",
    dueDate: "2025-07-20",
    status: "Done",
    blocker: null,
  },
  {
    id: "design-t2",
    title: "Social media template kit (12 templates)",
    client: "CityLine Fitness",
    service: "Social Media Design",
    owner: "Lily Chen",
    priority: "Medium",
    dueDate: "2025-07-27",
    status: "In Progress",
    blocker: null,
  },
  {
    id: "design-t3",
    title: "Email newsletter redesign",
    client: "Westside Dental",
    service: "Email Design",
    owner: "Aaron Park",
    priority: "Medium",
    dueDate: "2025-07-31",
    status: "In Progress",
    blocker: null,
  },
  {
    id: "design-t4",
    title: "Print brochure design — tri-fold",
    client: "Blue Ridge Plumbing",
    service: "Print Design",
    owner: "Lily Chen",
    priority: "Low",
    dueDate: "2025-08-05",
    status: "Pending",
    blocker: null,
  },
  {
    id: "design-t5",
    title: "Infographic: Local SEO stats 2025",
    client: "All Clients",
    service: "Content Design",
    owner: "Aaron Park",
    priority: "Low",
    dueDate: "2025-08-10",
    status: "Pending",
    blocker: null,
  },
  {
    id: "design-t6",
    title: "Ad creative revisions — client feedback round 2",
    client: "Harbor Auto",
    service: "Creative Production",
    owner: "Lily Chen",
    priority: "High",
    dueDate: "2025-07-19",
    status: "Blocked",
    blocker: "Client feedback not received — follow-up email sent 2025-07-12.",
  },
];
