import type { RTMNotification } from "./types";

// ─────────────────────────────────────────────────────────────────
// RTM OS — 60 Realistic Notifications across all modules
// ─────────────────────────────────────────────────────────────────

export const NOTIFICATIONS: RTMNotification[] = [
  // ── WORKFLOW ENGINE ─────────────────────────────────────────────
  {
    id: "n-001", priority: "High", type: "Workflow",
    title: "Proposal Approved — Notify Billing",
    description: "Proposal for Horizon Dental approved. Billing must generate the first invoice.",
    client: "Horizon Dental", clientSlug: "horizon-dental",
    module: "Workflow Engine", createdDate: "2025-07-14",
    status: "Unread", relatedRoute: "/admin/workflows",
  },
  {
    id: "n-002", priority: "High", type: "Workflow",
    title: "Invoice Paid — Notify Account Management",
    description: "Invoice #INV-2241 paid by Blue Sky Dental. AM notified to begin onboarding.",
    client: "Blue Sky Dental", clientSlug: "blue-sky-dental",
    module: "Workflow Engine", createdDate: "2025-07-14",
    status: "Unread", relatedRoute: "/admin/workflows",
  },
  {
    id: "n-003", priority: "Urgent", type: "Workflow",
    title: "Department Activation Pending — Operations",
    description: "SEO + GBP activation pending for Summit Law Group. No AM assigned yet.",
    client: "Summit Law Group", clientSlug: "summit-law-group",
    module: "Workflow Engine", createdDate: "2025-07-13",
    status: "Unread", relatedRoute: "/admin/workflows",
  },
  {
    id: "n-004", priority: "Critical", type: "Renewal",
    title: "Renewal Due — AM Action Required",
    description: "Apex Roofing renewal due in 28 days. Proposal must be sent immediately.",
    client: "Apex Roofing", clientSlug: "apex-roofing",
    module: "Renewals", createdDate: "2025-07-13",
    status: "Escalated", relatedRoute: "/renewals",
    escalation: { level: 2, daysOpen: 5, trigger: "Renewal < 30 Days" },
  },
  {
    id: "n-005", priority: "High", type: "Cancellation",
    title: "Cancellation Approved — Notify Billing + Ops",
    description: "Cancellation approved for Metro Glass Co. Final invoice + offboarding initiated.",
    client: "Metro Glass Co", clientSlug: "metro-glass-co",
    module: "Cancellations", createdDate: "2025-07-12",
    status: "Unread", relatedRoute: "/billing/cancellations",
  },
  {
    id: "n-006", priority: "High", type: "Workflow",
    title: "Onboarding Started — Kickoff Pending",
    description: "Onboarding workflow triggered for Lakeview Chiropractic. Kickoff not scheduled.",
    client: "Lakeview Chiropractic", clientSlug: "lakeview-chiropractic",
    module: "Account Management", createdDate: "2025-07-12",
    status: "Read", relatedRoute: "/account-management/onboarding",
  },
  {
    id: "n-007", priority: "Medium", type: "Workflow",
    title: "Proposal Rejected — Notify Sales",
    description: "Proposal for Valley HVAC rejected. Sales team follow-up required.",
    client: "Valley HVAC", clientSlug: "valley-hvac",
    module: "Sales", createdDate: "2025-07-11",
    status: "Read", relatedRoute: "/sales",
  },
  {
    id: "n-008", priority: "Medium", type: "Workflow",
    title: "Lead Assigned — New Prospect",
    description: "New lead Pacific Dental Group assigned to sales rep Ryan Adams.",
    client: "Pacific Dental Group", clientSlug: "pacific-dental-group",
    module: "Sales", createdDate: "2025-07-11",
    status: "Unread", relatedRoute: "/sales",
  },
  {
    id: "n-009", priority: "High", type: "Activation",
    title: "Client Activated — AM Handoff Complete",
    description: "Bright Path Financial activation complete. All departments now live.",
    client: "Bright Path Financial", clientSlug: "bright-path-financial",
    module: "Billing Activation", createdDate: "2025-07-10",
    status: "Acknowledged", relatedRoute: "/billing/activation",
  },
  {
    id: "n-010", priority: "Urgent", type: "Offboarding",
    title: "Offboarding Triggered — Action Required",
    description: "Offboarding workflow started for Coastal Insurance. Access removal pending.",
    client: "Coastal Insurance", clientSlug: "coastal-insurance",
    module: "Offboarding", createdDate: "2025-07-10",
    status: "Unread", relatedRoute: "/cancellations/offboarding",
  },

  // ── TASK ENGINE ─────────────────────────────────────────────────
  {
    id: "n-011", priority: "Urgent", type: "Task",
    title: "Task Overdue — SEO Audit for Ridgeline Roofing",
    description: "Task 'Conduct SEO Technical Audit' is 9 days overdue. Manager notified.",
    client: "Ridgeline Roofing", clientSlug: "ridgeline-roofing",
    module: "Task Engine", createdDate: "2025-07-14",
    status: "Escalated", relatedRoute: "/tasks",
    escalation: { level: 1, daysOpen: 9, trigger: "Task Overdue > 7 Days" },
  },
  {
    id: "n-012", priority: "High", type: "Task",
    title: "Task Assigned — Meta Ads Campaign Setup",
    description: "Meta Ads campaign setup assigned to Lisa Park for Urban Fresh Market.",
    client: "Urban Fresh Market", clientSlug: "urban-fresh-market",
    module: "Task Engine", createdDate: "2025-07-14",
    status: "Unread", relatedRoute: "/tasks",
  },
  {
    id: "n-013", priority: "High", type: "Task",
    title: "Task Blocked — GBP Optimization",
    description: "GBP profile optimization blocked pending client photo submission.",
    client: "Gourmet Bistro", clientSlug: "gourmet-bistro",
    module: "Task Engine", createdDate: "2025-07-13",
    status: "Unread", relatedRoute: "/tasks",
  },
  {
    id: "n-014", priority: "Medium", type: "Task",
    title: "Task Due Tomorrow — Monthly Reporting",
    description: "Monthly performance report for Horizon Dental due tomorrow.",
    client: "Horizon Dental", clientSlug: "horizon-dental",
    module: "Task Engine", createdDate: "2025-07-13",
    status: "Unread", relatedRoute: "/tasks",
  },
  {
    id: "n-015", priority: "Critical", type: "Task",
    title: "Dependency Blocked — Activation Chain Stalled",
    description: "Activation task chain stalled. Dept setup depends on billing confirmation.",
    client: "Summit Law Group", clientSlug: "summit-law-group",
    module: "Task Engine", createdDate: "2025-07-13",
    status: "Escalated", relatedRoute: "/tasks",
    escalation: { level: 3, daysOpen: 3, trigger: "Activation Blocked" },
  },
  {
    id: "n-016", priority: "Medium", type: "Task",
    title: "Task Completed — Keyword Research Delivered",
    description: "Keyword research for Lakeview Chiropractic completed. Requestor notified.",
    client: "Lakeview Chiropractic", clientSlug: "lakeview-chiropractic",
    module: "Task Engine", createdDate: "2025-07-12",
    status: "Read", relatedRoute: "/tasks",
  },
  {
    id: "n-017", priority: "High", type: "Task",
    title: "Task Reassigned — Content Calendar",
    description: "Content calendar task reassigned from Kelly Brown to Maria Santos.",
    client: "Pacific Dental Group", clientSlug: "pacific-dental-group",
    module: "Task Engine", createdDate: "2025-07-12",
    status: "Read", relatedRoute: "/tasks",
  },
  {
    id: "n-018", priority: "Urgent", type: "Task",
    title: "Task Overdue — Invoice Follow-up",
    description: "Invoice follow-up task 12 days overdue. Escalated to billing manager.",
    client: "Metro Glass Co", clientSlug: "metro-glass-co",
    module: "Task Engine", createdDate: "2025-07-11",
    status: "Escalated", relatedRoute: "/tasks",
    escalation: { level: 2, daysOpen: 12, trigger: "Task Overdue > 7 Days" },
  },
  {
    id: "n-019", priority: "Medium", type: "Task",
    title: "Task Due Today — LSA Campaign Review",
    description: "LSA campaign weekly review task due today for Blue Sky Dental.",
    client: "Blue Sky Dental", clientSlug: "blue-sky-dental",
    module: "Task Engine", createdDate: "2025-07-14",
    status: "Unread", relatedRoute: "/tasks",
  },
  {
    id: "n-020", priority: "Low", type: "Task",
    title: "Task Waiting — Design Assets Pending Feedback",
    description: "Web design mockups waiting on client feedback from Apex Roofing.",
    client: "Apex Roofing", clientSlug: "apex-roofing",
    module: "Task Engine", createdDate: "2025-07-10",
    status: "Acknowledged", relatedRoute: "/tasks",
  },

  // ── BILLING ─────────────────────────────────────────────────────
  {
    id: "n-021", priority: "Urgent", type: "Billing",
    title: "Invoice Overdue — 30 Days Outstanding",
    description: "Invoice #INV-2198 for Valley HVAC is 30 days overdue. Collection needed.",
    client: "Valley HVAC", clientSlug: "valley-hvac",
    module: "Billing", createdDate: "2025-07-14",
    status: "Escalated", relatedRoute: "/billing/invoices",
    escalation: { level: 2, daysOpen: 30, trigger: "Outstanding Balance > Threshold" },
  },
  {
    id: "n-022", priority: "High", type: "Billing",
    title: "Invoice Sent — Follow Up In 7 Days",
    description: "Invoice #INV-2245 sent to Pacific Dental Group for $3,200/month services.",
    client: "Pacific Dental Group", clientSlug: "pacific-dental-group",
    module: "Billing", createdDate: "2025-07-13",
    status: "Unread", relatedRoute: "/billing/invoices",
  },
  {
    id: "n-023", priority: "Critical", type: "Billing",
    title: "Billing Hold — Activation Blocked",
    description: "Billing hold on Summit Law Group blocks activation. Payment issue unresolved.",
    client: "Summit Law Group", clientSlug: "summit-law-group",
    module: "Billing", createdDate: "2025-07-13",
    status: "Unread", relatedRoute: "/billing/invoices",
  },
  {
    id: "n-024", priority: "High", type: "Billing",
    title: "Payment Received — Invoice #INV-2231",
    description: "Payment of $2,850 received from Ridgeline Roofing. Account current.",
    client: "Ridgeline Roofing", clientSlug: "ridgeline-roofing",
    module: "Billing", createdDate: "2025-07-12",
    status: "Read", relatedRoute: "/billing/invoices",
  },
  {
    id: "n-025", priority: "High", type: "Billing",
    title: "Final Invoice Needed — Client Offboarding",
    description: "Final invoice must be generated for Metro Glass Co before offboarding closes.",
    client: "Metro Glass Co", clientSlug: "metro-glass-co",
    module: "Billing", createdDate: "2025-07-12",
    status: "Unread", relatedRoute: "/billing/invoices",
  },
  {
    id: "n-026", priority: "Medium", type: "Billing",
    title: "Invoice Sent — Gourmet Bistro",
    description: "Monthly invoice #INV-2251 sent to Gourmet Bistro for content services.",
    client: "Gourmet Bistro", clientSlug: "gourmet-bistro",
    module: "Billing", createdDate: "2025-07-11",
    status: "Read", relatedRoute: "/billing/invoices",
  },
  {
    id: "n-027", priority: "Low", type: "Billing",
    title: "Subscription Renewed — Auto-Billing Confirmed",
    description: "Urban Fresh Market auto-billing renewed successfully. No action needed.",
    client: "Urban Fresh Market", clientSlug: "urban-fresh-market",
    module: "Billing", createdDate: "2025-07-10",
    status: "Resolved", relatedRoute: "/billing",
  },

  // ── RENEWALS ─────────────────────────────────────────────────────
  {
    id: "n-028", priority: "Critical", type: "Renewal",
    title: "Renewal Escalated — 14 Days Remaining",
    description: "Coastal Insurance renewal now at critical stage — 14 days left. Immediate action.",
    client: "Coastal Insurance", clientSlug: "coastal-insurance",
    module: "Renewals", createdDate: "2025-07-14",
    status: "Escalated", relatedRoute: "/renewals",
    escalation: { level: 3, daysOpen: 16, trigger: "Renewal < 14 Days" },
  },
  {
    id: "n-029", priority: "High", type: "Renewal",
    title: "Renewal Proposal Needed — 30 Days Out",
    description: "Ridgeline Roofing renewal in 30 days. Proposal must be drafted this week.",
    client: "Ridgeline Roofing", clientSlug: "ridgeline-roofing",
    module: "Renewals", createdDate: "2025-07-13",
    status: "Unread", relatedRoute: "/renewals",
  },
  {
    id: "n-030", priority: "Medium", type: "Renewal",
    title: "Renewal Alert — 60 Days Before Contract End",
    description: "Lakeview Chiropractic contract ends in 60 days. Begin renewal outreach.",
    client: "Lakeview Chiropractic", clientSlug: "lakeview-chiropractic",
    module: "Renewals", createdDate: "2025-07-11",
    status: "Unread", relatedRoute: "/renewals",
  },
  {
    id: "n-031", priority: "Low", type: "Renewal",
    title: "Renewal Reminder — 90 Days Notice",
    description: "Valley HVAC contract renewal window opens in 90 days. Plan ahead.",
    client: "Valley HVAC", clientSlug: "valley-hvac",
    module: "Renewals", createdDate: "2025-07-09",
    status: "Read", relatedRoute: "/renewals",
  },
  {
    id: "n-032", priority: "Low", type: "Renewal",
    title: "Renewal Reminder — 120 Days Notice",
    description: "Blue Sky Dental renewal 120 days out. Early planning recommended.",
    client: "Blue Sky Dental", clientSlug: "blue-sky-dental",
    module: "Renewals", createdDate: "2025-07-08",
    status: "Resolved", relatedRoute: "/renewals",
  },

  // ── CANCELLATIONS ────────────────────────────────────────────────
  {
    id: "n-033", priority: "High", type: "Cancellation",
    title: "Cancellation Request Received",
    description: "Cancellation request submitted for Gourmet Bistro. AM review required.",
    client: "Gourmet Bistro", clientSlug: "gourmet-bistro",
    module: "Cancellations", createdDate: "2025-07-14",
    status: "Unread", relatedRoute: "/billing/cancellations",
  },
  {
    id: "n-034", priority: "Medium", type: "Cancellation",
    title: "Cancellation Pending — Awaiting Billing Confirmation",
    description: "Coastal Insurance cancellation pending. Final billing confirmation needed.",
    client: "Coastal Insurance", clientSlug: "coastal-insurance",
    module: "Cancellations", createdDate: "2025-07-12",
    status: "Unread", relatedRoute: "/billing/cancellations",
  },

  // ── OFFBOARDING ──────────────────────────────────────────────────
  {
    id: "n-035", priority: "High", type: "Offboarding",
    title: "Offboarding Started — Access Revocation Pending",
    description: "Offboarding for Metro Glass Co initiated. IT must revoke portal access.",
    client: "Metro Glass Co", clientSlug: "metro-glass-co",
    module: "Offboarding", createdDate: "2025-07-13",
    status: "Unread", relatedRoute: "/cancellations/offboarding",
  },
  {
    id: "n-036", priority: "Medium", type: "Offboarding",
    title: "Offboarding Checklist Incomplete",
    description: "Coastal Insurance offboarding checklist 3 items incomplete. Review required.",
    client: "Coastal Insurance", clientSlug: "coastal-insurance",
    module: "Offboarding", createdDate: "2025-07-12",
    status: "Unread", relatedRoute: "/cancellations/offboarding",
  },

  // ── AFFILIATE MANAGEMENT ─────────────────────────────────────────
  {
    id: "n-037", priority: "High", type: "Affiliate",
    title: "New Referral Submitted — Horizon Dental",
    description: "Affiliate partner Jake Sullivan submitted a new referral for Horizon Dental.",
    client: "Horizon Dental", clientSlug: "horizon-dental",
    module: "Affiliate Management", createdDate: "2025-07-14",
    status: "Unread", relatedRoute: "/sales",
  },
  {
    id: "n-038", priority: "High", type: "Affiliate",
    title: "Commission Approval Needed",
    description: "Commission of $450 pending approval for referral by partner Lisa Monroe.",
    client: "Pacific Dental Group", clientSlug: "pacific-dental-group",
    module: "Affiliate Management", createdDate: "2025-07-13",
    status: "Unread", relatedRoute: "/sales",
  },
  {
    id: "n-039", priority: "Medium", type: "Affiliate",
    title: "Affiliate Activated — New Partner Onboarded",
    description: "New affiliate partner Brian Chen activated. Referral tracking now live.",
    client: "—", clientSlug: "",
    module: "Affiliate Management", createdDate: "2025-07-12",
    status: "Read", relatedRoute: "/sales",
  },
  {
    id: "n-040", priority: "Medium", type: "Affiliate",
    title: "Commission Approved — Payout Due",
    description: "Commission of $750 approved for partner Sarah Kim. Process payout this week.",
    client: "Bright Path Financial", clientSlug: "bright-path-financial",
    module: "Affiliate Management", createdDate: "2025-07-11",
    status: "Acknowledged", relatedRoute: "/sales",
  },
  {
    id: "n-041", priority: "Low", type: "Affiliate",
    title: "Referral Converted — New Client Signed",
    description: "Referral for Blue Sky Dental by partner Tom Harris converted. Commission triggered.",
    client: "Blue Sky Dental", clientSlug: "blue-sky-dental",
    module: "Affiliate Management", createdDate: "2025-07-10",
    status: "Resolved", relatedRoute: "/sales",
  },

  // ── ACCOUNT MANAGEMENT / CLIENT PORTFOLIO ───────────────────────
  {
    id: "n-042", priority: "High", type: "Account Management",
    title: "Client Ready For Onboarding",
    description: "Summit Law Group payment confirmed. Assign AM and start onboarding immediately.",
    client: "Summit Law Group", clientSlug: "summit-law-group",
    module: "Account Management", createdDate: "2025-07-14",
    status: "Unread", relatedRoute: "/account-management",
  },
  {
    id: "n-043", priority: "Medium", type: "Account Management",
    title: "Health Alert — Client Engagement Low",
    description: "Apex Roofing engagement score dropped below threshold. AM review recommended.",
    client: "Apex Roofing", clientSlug: "apex-roofing",
    module: "Client Portfolio", createdDate: "2025-07-13",
    status: "Unread", relatedRoute: "/clients/apex-roofing",
  },
  {
    id: "n-044", priority: "Medium", type: "Account Management",
    title: "Account Review Due — Quarterly Check-in",
    description: "Quarterly review for Lakeview Chiropractic due this week. Schedule meeting.",
    client: "Lakeview Chiropractic", clientSlug: "lakeview-chiropractic",
    module: "Account Management", createdDate: "2025-07-12",
    status: "Unread", relatedRoute: "/clients/lakeview-chiropractic",
  },
  {
    id: "n-045", priority: "Low", type: "Account Management",
    title: "Client Note Added — Service Update",
    description: "AM Marcus Webb added a note to Bright Path Financial's account.",
    client: "Bright Path Financial", clientSlug: "bright-path-financial",
    module: "Account Management", createdDate: "2025-07-11",
    status: "Read", relatedRoute: "/clients/bright-path-financial",
  },
  {
    id: "n-046", priority: "High", type: "Activation",
    title: "Activation Blocked — Missing Credentials",
    description: "Urban Fresh Market activation blocked. Client hasn't submitted Google login.",
    client: "Urban Fresh Market", clientSlug: "urban-fresh-market",
    module: "Billing Activation", createdDate: "2025-07-13",
    status: "Unread", relatedRoute: "/billing/activation",
  },
  {
    id: "n-047", priority: "Medium", type: "Activation",
    title: "Activation In Progress — Departments Launching",
    description: "Blue Sky Dental activation in progress. SEO + Content depts launching.",
    client: "Blue Sky Dental", clientSlug: "blue-sky-dental",
    module: "Billing Activation", createdDate: "2025-07-12",
    status: "Read", relatedRoute: "/billing/activation",
  },

  // ── SYSTEM ───────────────────────────────────────────────────────
  {
    id: "n-048", priority: "Medium", type: "System",
    title: "Workflow Engine Update Deployed",
    description: "Workflow engine v2.4 deployed. New automation rules now active.",
    client: "—", clientSlug: "",
    module: "Admin", createdDate: "2025-07-13",
    status: "Read", relatedRoute: "/admin",
  },
  {
    id: "n-049", priority: "Low", type: "System",
    title: "Scheduled Maintenance — Tonight 11PM",
    description: "Platform maintenance window tonight 11PM–1AM. Brief outage expected.",
    client: "—", clientSlug: "",
    module: "Admin", createdDate: "2025-07-13",
    status: "Acknowledged", relatedRoute: "/admin",
  },
  {
    id: "n-050", priority: "High", type: "System",
    title: "Integration Error — Billing Sync Failed",
    description: "Stripe billing sync failed for 3 accounts. Manual reconciliation required.",
    client: "—", clientSlug: "",
    module: "Admin", createdDate: "2025-07-14",
    status: "Unread", relatedRoute: "/admin",
  },

  // ── EXTRA NOTIFICATIONS ──────────────────────────────────────────
  {
    id: "n-051", priority: "High", type: "Task",
    title: "Task Assigned — Website Redesign Kickoff",
    description: "Website redesign project kicked off for Horizon Dental. Tasks assigned.",
    client: "Horizon Dental", clientSlug: "horizon-dental",
    module: "Task Engine", createdDate: "2025-07-11",
    status: "Read", relatedRoute: "/tasks",
  },
  {
    id: "n-052", priority: "Medium", type: "Billing",
    title: "Invoice Disputed — Client Requesting Review",
    description: "Valley HVAC disputes invoice #INV-2177. Billing team review needed.",
    client: "Valley HVAC", clientSlug: "valley-hvac",
    module: "Billing", createdDate: "2025-07-10",
    status: "Unread", relatedRoute: "/billing/invoices",
  },
  {
    id: "n-053", priority: "Medium", type: "Renewal",
    title: "Renewal Proposal Sent — Awaiting Signature",
    description: "Renewal proposal sent to Gourmet Bistro. Following up in 5 business days.",
    client: "Gourmet Bistro", clientSlug: "gourmet-bistro",
    module: "Renewals", createdDate: "2025-07-10",
    status: "Acknowledged", relatedRoute: "/renewals",
  },
  {
    id: "n-054", priority: "High", type: "Workflow",
    title: "Invoice Requested — Proposal Signed",
    description: "Urban Fresh Market signed proposal. Invoice request sent to billing team.",
    client: "Urban Fresh Market", clientSlug: "urban-fresh-market",
    module: "Workflow Engine", createdDate: "2025-07-09",
    status: "Read", relatedRoute: "/admin/workflows",
  },
  {
    id: "n-055", priority: "Low", type: "Account Management",
    title: "Client Survey Completed — 5-Star Rating",
    description: "Pacific Dental Group submitted 5-star satisfaction survey. AM notified.",
    client: "Pacific Dental Group", clientSlug: "pacific-dental-group",
    module: "Account Management", createdDate: "2025-07-09",
    status: "Resolved", relatedRoute: "/clients/pacific-dental-group",
  },
  {
    id: "n-056", priority: "Urgent", type: "Task",
    title: "Task Overdue — Paid Ads Report Missing",
    description: "Monthly paid ads report for Apex Roofing is 11 days overdue.",
    client: "Apex Roofing", clientSlug: "apex-roofing",
    module: "Task Engine", createdDate: "2025-07-08",
    status: "Escalated", relatedRoute: "/tasks",
    escalation: { level: 1, daysOpen: 11, trigger: "Task Overdue > 7 Days" },
  },
  {
    id: "n-057", priority: "Medium", type: "Affiliate",
    title: "Payout Due — End of Month",
    description: "3 affiliate commissions totaling $1,400 are due for payout this Friday.",
    client: "—", clientSlug: "",
    module: "Affiliate Management", createdDate: "2025-07-08",
    status: "Unread", relatedRoute: "/sales",
  },
  {
    id: "n-058", priority: "High", type: "Cancellation",
    title: "At-Risk Account — Cancellation Likely",
    description: "Blue Sky Dental flagged as at-risk following support escalation. AM call needed.",
    client: "Blue Sky Dental", clientSlug: "blue-sky-dental",
    module: "Cancellations", createdDate: "2025-07-07",
    status: "Unread", relatedRoute: "/billing/cancellations",
  },
  {
    id: "n-059", priority: "Medium", type: "Workflow",
    title: "Workflow Step Completed — Billing Confirmation",
    description: "Billing confirmation step completed for Bright Path Financial workflow.",
    client: "Bright Path Financial", clientSlug: "bright-path-financial",
    module: "Workflow Engine", createdDate: "2025-07-07",
    status: "Read", relatedRoute: "/admin/workflows",
  },
  {
    id: "n-060", priority: "Low", type: "System",
    title: "New User Onboarded — Team Access Granted",
    description: "New team member Jordan Lee granted access to RTM OS platform.",
    client: "—", clientSlug: "",
    module: "Admin", createdDate: "2025-07-06",
    status: "Resolved", relatedRoute: "/admin/users",
  },
];

export const UNREAD_COUNT = NOTIFICATIONS.filter(
  (n) => n.status === "Unread" || n.status === "Escalated"
).length;
