import type { ChangeRequest } from "./types";

// ─────────────────────────────────────────────────────────────────────────────
// Change Request Engine — Mock Data (20 records)
// ─────────────────────────────────────────────────────────────────────────────

export const MOCK_CHANGE_REQUESTS: ChangeRequest[] = [
  // ── CR-001: Budget Reallocation ────────────────────────────────────────────
  {
    id: "CR-001",
    client: "Acme Corp",
    project: "Q3 Digital Campaign",
    requestType: "Budget Reallocation",
    requestedBy: "Sarah Mitchell",
    requestedByRole: "Account Manager",
    assignedAM: "Sarah Mitchell",
    revenueImpact: 0,
    revenueDirection: "Neutral",
    departmentsImpacted: ["SEO", "Paid Advertising"],
    status: "Approved",
    submittedDate: "2025-06-15",
    effectiveDate: "2025-07-01",
    description: "Reallocate $1,200/mo from SEO to PPC to capitalize on high-converting paid search window.",
    clientHealthScore: 88,
    clientHealthStatus: "Healthy",
    renewalRisk: "Low",
    expansionOpportunity: "Medium",
    clientMRR: 4500,
    clientARR: 54000,
    openEscalations: 0,
    openProjects: 3,
    lastCommunication: "2025-06-20",
    aiClientSummary: "Acme Corp is a high-performing client with strong campaign results. Budget reallocation aligns with seasonal PPC opportunity identified in last QBR.",
    projectsImpacted: ["Q3 Digital Campaign", "PPC Setup"],
    tasksAdded: 4,
    tasksRemoved: 2,
    milestonesAffected: 1,
    contractAmendmentRequired: false,
    billingApprovalStatus: "Approved",
    budgetLines: [
      { service: "SEO", department: "SEO", currentBudget: 2500, proposedBudget: 1300, difference: -1200 },
      { service: "PPC", department: "Paid Advertising", currentBudget: 1000, proposedBudget: 2200, difference: 1200 },
    ],
    approvalWorkflow: [
      { stage: "Review", assignee: "Sarah Mitchell", status: "Approved", completedDate: "2025-06-16" },
      { stage: "Department Approval", assignee: "SEO Lead", status: "Approved", completedDate: "2025-06-17" },
      { stage: "Account Manager Approval", assignee: "Sarah Mitchell", status: "Approved", completedDate: "2025-06-17" },
      { stage: "Billing Approval", assignee: "Billing Team", status: "Approved", completedDate: "2025-06-18" },
      { stage: "Final Approval", assignee: "Director of AM", status: "Approved", completedDate: "2025-06-19" },
    ],
    implementationItems: [
      { area: "Projects Updated", status: "Completed", completedDate: "2025-06-21" },
      { area: "Task Blueprints Updated", status: "Completed", completedDate: "2025-06-21" },
      { area: "Departments Updated", status: "Completed", completedDate: "2025-06-21" },
      { area: "Billing Updated", status: "Completed", completedDate: "2025-06-22" },
      { area: "Contract Updated", status: "Not Required" },
    ],
    implementationStatus: "Completed",
    implementationCompletedDate: "2025-06-22",
    aiImpactAssessment: "Budget reallocation carries low risk. PPC performance data supports the shift. SEO tasks will be reduced proportionally with no expected ranking impact within the 90-day window.",
    aiRiskAssessment: "Low risk. Client is healthy and has approved the change. SEO deliverables need to be reviewed for reduced scope.",
    aiRecommendedActions: ["Confirm SEO task list reduction", "Set PPC expanded budget caps", "Report to client on Q3 reallocation effectiveness"],
    aiImplementationPlan: "Update PPC budget cap in campaign manager. Reduce SEO deliverable count from 8 to 5 monthly tasks. Update billing schedule effective July 1. Notify both department leads.",
    activityTimeline: [
      { date: "2025-06-15", event: "Request Created", actor: "Sarah Mitchell" },
      { date: "2025-06-16", event: "Review Started", actor: "Sarah Mitchell" },
      { date: "2025-06-17", event: "Department Approval", actor: "SEO Lead", note: "Approved with reduced deliverable plan" },
      { date: "2025-06-18", event: "Billing Approval", actor: "Billing Team" },
      { date: "2025-06-19", event: "Final Approval", actor: "Director of AM" },
      { date: "2025-06-21", event: "Projects Updated", actor: "Sarah Mitchell" },
      { date: "2025-06-22", event: "Request Implemented", actor: "System" },
    ],
    mrrChange: 0,
    arrChange: 0,
    oneTimeFees: 0,
    credits: 0,
    adjustments: 0,
  },

  // ── CR-002: Service Addition ───────────────────────────────────────────────
  {
    id: "CR-002",
    client: "BlueSky Solutions",
    project: "Local Lead Generation",
    requestType: "Service Addition",
    requestedBy: "James Carter",
    requestedByRole: "Account Manager",
    assignedAM: "James Carter",
    revenueImpact: 1500,
    revenueDirection: "Increase",
    departmentsImpacted: ["Local Service Ads"],
    status: "Pending Approval",
    submittedDate: "2025-06-28",
    effectiveDate: "2025-07-15",
    description: "Add LSA (Local Service Ads) management service to existing package. Client requests activation for plumbing vertical.",
    clientHealthScore: 74,
    clientHealthStatus: "Needs Attention",
    renewalRisk: "Medium",
    expansionOpportunity: "High",
    clientMRR: 3200,
    clientARR: 38400,
    openEscalations: 1,
    openProjects: 2,
    lastCommunication: "2025-06-25",
    aiClientSummary: "BlueSky Solutions is a growing local services business. The LSA addition aligns with their expansion into residential plumbing. One open escalation regarding GBP listing accuracy should be resolved before LSA activation.",
    projectsImpacted: ["Local Lead Generation", "LSA Activation"],
    tasksAdded: 12,
    tasksRemoved: 0,
    milestonesAffected: 2,
    contractAmendmentRequired: true,
    billingApprovalStatus: "Pending",
    serviceAdded: "Local Service Ads Management",
    additionalDepartments: ["Local Service Ads"],
    newDeliverables: ["LSA Profile Setup", "LSA Budget Management", "Lead Review", "Weekly LSA Reports"],
    approvalWorkflow: [
      { stage: "Review", assignee: "James Carter", status: "Approved", completedDate: "2025-06-29" },
      { stage: "Department Approval", assignee: "LSA Lead", status: "Approved", completedDate: "2025-06-30" },
      { stage: "Account Manager Approval", assignee: "James Carter", status: "Approved", completedDate: "2025-06-30" },
      { stage: "Billing Approval", assignee: "Billing Team", status: "In Progress" },
      { stage: "Executive Approval", assignee: "VP of Operations", status: "Pending" },
      { stage: "Final Approval", assignee: "Director of AM", status: "Pending" },
    ],
    implementationItems: [
      { area: "Projects Updated", status: "Pending" },
      { area: "Task Blueprints Updated", status: "Pending" },
      { area: "Departments Updated", status: "Pending" },
      { area: "Billing Updated", status: "Pending" },
      { area: "Contract Updated", status: "Pending" },
    ],
    implementationStatus: "Not Started",
    aiImpactAssessment: "Service addition increases MRR by $1,500 and requires LSA department activation. Task blueprint generation needed for LSA vertical. Open GBP escalation may delay LSA approval from Google.",
    aiRiskAssessment: "Medium risk. Open escalation must be resolved before LSA activation. Contract amendment required. Billing approval in progress.",
    aiRecommendedActions: ["Resolve open GBP escalation first", "Generate LSA task blueprint", "Amend contract to include LSA terms", "Set LSA activation date post-approval"],
    aiImplementationPlan: "Resolve GBP escalation. Generate LSA task blueprint. Create LSA activation project. Update contract. Update billing to $4,700/mo effective July 15.",
    activityTimeline: [
      { date: "2025-06-28", event: "Request Created", actor: "James Carter" },
      { date: "2025-06-29", event: "Review Started", actor: "James Carter" },
      { date: "2025-06-30", event: "Department Approval", actor: "LSA Lead" },
      { date: "2025-07-01", event: "Billing Approval Requested", actor: "System" },
    ],
    mrrChange: 1500,
    arrChange: 18000,
    oneTimeFees: 500,
    credits: 0,
    adjustments: 0,
  },

  // ── CR-003: Service Upgrade ────────────────────────────────────────────────
  {
    id: "CR-003",
    client: "NovaTech Inc",
    project: "Enterprise SEO Program",
    requestType: "Service Upgrade",
    requestedBy: "Rachel Torres",
    requestedByRole: "Account Manager",
    assignedAM: "Rachel Torres",
    revenueImpact: 3000,
    revenueDirection: "Increase",
    departmentsImpacted: ["SEO", "Content", "Reporting"],
    status: "Approved",
    submittedDate: "2025-06-10",
    effectiveDate: "2025-07-01",
    description: "Upgrade NovaTech from SEO Pro to SEO Enterprise. Includes content team activation and monthly reporting.",
    clientHealthScore: 91,
    clientHealthStatus: "Healthy",
    renewalRisk: "Low",
    expansionOpportunity: "High",
    clientMRR: 8000,
    clientARR: 96000,
    openEscalations: 0,
    openProjects: 5,
    lastCommunication: "2025-06-18",
    aiClientSummary: "NovaTech Inc is a flagship client with strong growth trajectory. Service upgrade to Enterprise tier unlocks advanced content strategy and enterprise reporting capabilities.",
    projectsImpacted: ["Enterprise SEO Program", "Content Calendar", "Monthly Reporting"],
    tasksAdded: 22,
    tasksRemoved: 0,
    milestonesAffected: 3,
    contractAmendmentRequired: true,
    billingApprovalStatus: "Approved",
    currentPackage: "SEO Pro ($5,000/mo)",
    newPackage: "SEO Enterprise ($8,000/mo)",
    newDeliverables: ["Enterprise SEO Strategy", "Content Production (8 pcs/mo)", "Executive Reporting", "Quarterly Business Review"],
    additionalDepartments: ["Content", "Reporting"],
    approvalWorkflow: [
      { stage: "Review", assignee: "Rachel Torres", status: "Approved", completedDate: "2025-06-11" },
      { stage: "Department Approval", assignee: "SEO Lead", status: "Approved", completedDate: "2025-06-12" },
      { stage: "Account Manager Approval", assignee: "Rachel Torres", status: "Approved", completedDate: "2025-06-12" },
      { stage: "Billing Approval", assignee: "Billing Team", status: "Approved", completedDate: "2025-06-13" },
      { stage: "Executive Approval", assignee: "VP of Operations", status: "Approved", completedDate: "2025-06-14" },
      { stage: "Final Approval", assignee: "Director of AM", status: "Approved", completedDate: "2025-06-15" },
    ],
    implementationItems: [
      { area: "Projects Updated", status: "Completed", completedDate: "2025-06-18" },
      { area: "Task Blueprints Updated", status: "Completed", completedDate: "2025-06-18" },
      { area: "Departments Updated", status: "Completed", completedDate: "2025-06-19" },
      { area: "Billing Updated", status: "Completed", completedDate: "2025-06-20" },
      { area: "Contract Updated", status: "Completed", completedDate: "2025-06-21" },
    ],
    implementationStatus: "Completed",
    implementationCompletedDate: "2025-06-21",
    aiImpactAssessment: "Service upgrade is revenue-positive at $3,000/mo increase. Content and reporting departments will be activated. 22 new task blueprints required. Implementation complete.",
    aiRiskAssessment: "Low risk. Client is healthy. All approvals complete. Contract amended successfully.",
    aiRecommendedActions: ["Monitor content department ramp-up", "Schedule enterprise reporting kickoff", "Update client success plan for Enterprise tier"],
    aiImplementationPlan: "Activate Content team with 8 pieces/month plan. Enable enterprise reporting module. Update contract to Enterprise terms. Update billing to $8,000/mo effective July 1.",
    activityTimeline: [
      { date: "2025-06-10", event: "Request Created", actor: "Rachel Torres" },
      { date: "2025-06-11", event: "Review Started", actor: "Rachel Torres" },
      { date: "2025-06-12", event: "Department Approval", actor: "SEO Lead" },
      { date: "2025-06-14", event: "Executive Approval", actor: "VP of Operations" },
      { date: "2025-06-15", event: "Final Approval", actor: "Director of AM" },
      { date: "2025-06-18", event: "Projects Updated", actor: "Rachel Torres" },
      { date: "2025-06-21", event: "Request Implemented", actor: "System" },
    ],
    mrrChange: 3000,
    arrChange: 36000,
    oneTimeFees: 0,
    credits: 0,
    adjustments: 0,
  },

  // ── CR-004: Service Downgrade ──────────────────────────────────────────────
  {
    id: "CR-004",
    client: "Greenfield Media",
    project: "Digital Marketing Program",
    requestType: "Service Downgrade",
    requestedBy: "James Carter",
    requestedByRole: "Account Manager",
    assignedAM: "James Carter",
    revenueImpact: -1500,
    revenueDirection: "Decrease",
    departmentsImpacted: ["Content", "Reporting"],
    status: "Under Review",
    submittedDate: "2025-07-01",
    description: "Client requests content production reduction from 10 to 5 pieces/month and removal of advanced reporting add-on due to budget constraints.",
    clientHealthScore: 65,
    clientHealthStatus: "Needs Attention",
    renewalRisk: "High",
    expansionOpportunity: "Low",
    clientMRR: 3000,
    clientARR: 36000,
    openEscalations: 2,
    openProjects: 3,
    lastCommunication: "2025-06-30",
    aiClientSummary: "Greenfield Media is facing budget pressure. The downgrade request signals potential churn risk. Recommend retention conversation before approving the full downgrade.",
    projectsImpacted: ["Digital Marketing Program", "Content Calendar"],
    tasksAdded: 0,
    tasksRemoved: 18,
    milestonesAffected: 2,
    contractAmendmentRequired: true,
    billingApprovalStatus: "Pending",
    currentPackage: "Content Plus + Advanced Reporting ($3,000/mo)",
    newPackage: "Content Core ($1,500/mo)",
    removedDeliverables: ["5 Content Pieces/mo", "Advanced Reporting Dashboard", "Bi-weekly Reporting Calls"],
    approvalWorkflow: [
      { stage: "Review", assignee: "James Carter", status: "In Progress" },
      { stage: "Department Approval", assignee: "Content Lead", status: "Pending" },
      { stage: "Account Manager Approval", assignee: "James Carter", status: "Pending" },
      { stage: "Billing Approval", assignee: "Billing Team", status: "Pending" },
      { stage: "Final Approval", assignee: "Director of AM", status: "Pending" },
    ],
    implementationItems: [
      { area: "Projects Updated", status: "Pending" },
      { area: "Task Blueprints Updated", status: "Pending" },
      { area: "Departments Updated", status: "Pending" },
      { area: "Billing Updated", status: "Pending" },
      { area: "Contract Updated", status: "Pending" },
    ],
    implementationStatus: "Not Started",
    aiImpactAssessment: "Downgrade reduces MRR by $1,500. Content team will lose 5 recurring tasks. Advanced reporting module deactivated. Client health is already at-risk — downgrade may accelerate churn.",
    aiRiskAssessment: "High risk. Client has 2 open escalations and medium-high churn probability. Consider retention offer before approving downgrade.",
    aiRecommendedActions: ["Initiate retention conversation", "Offer 90-day billing credit in lieu of downgrade", "Escalate to leadership if client declines retention offer", "Document client decision regardless of outcome"],
    aiImplementationPlan: "Hold retention conversation first. If downgrade proceeds: reduce content blueprint from 10 to 5 tasks, deactivate advanced reporting, amend contract, update billing to $1,500/mo.",
    activityTimeline: [
      { date: "2025-07-01", event: "Request Created", actor: "James Carter" },
      { date: "2025-07-01", event: "Review Started", actor: "James Carter", note: "Retention conversation recommended" },
    ],
    mrrChange: -1500,
    arrChange: -18000,
    oneTimeFees: 0,
    credits: 0,
    adjustments: 0,
  },

  // ── CR-005: Pause ──────────────────────────────────────────────────────────
  {
    id: "CR-005",
    client: "Vertex Partners",
    project: "Brand Awareness Campaign",
    requestType: "Pause",
    requestedBy: "Vertex Partners (Client)",
    requestedByRole: "Client Contact",
    assignedAM: "Sarah Mitchell",
    revenueImpact: -2500,
    revenueDirection: "Decrease",
    departmentsImpacted: ["Paid Advertising", "Content", "Design"],
    status: "Approved",
    submittedDate: "2025-06-20",
    effectiveDate: "2025-07-01",
    description: "Client requests 60-day service pause while internal restructuring is underway. All campaign activity to be suspended July 1 through August 31.",
    clientHealthScore: 80,
    clientHealthStatus: "Healthy",
    renewalRisk: "Medium",
    expansionOpportunity: "Medium",
    clientMRR: 5000,
    clientARR: 60000,
    openEscalations: 0,
    openProjects: 4,
    lastCommunication: "2025-06-22",
    aiClientSummary: "Vertex Partners is a stable client undergoing internal restructuring. Pause is temporary and expected. Reactivation plan confirmed for September. Risk is moderate — monitor for signals of permanent churn.",
    projectsImpacted: ["Brand Awareness Campaign", "PPC Q3", "Monthly Content"],
    tasksAdded: 0,
    tasksRemoved: 0,
    milestonesAffected: 4,
    contractAmendmentRequired: false,
    billingApprovalStatus: "Approved",
    pauseStartDate: "2025-07-01",
    pauseEndDate: "2025-08-31",
    pauseReason: "Internal restructuring. CFO change. Budget freeze.",
    reactivationPlan: "Full reactivation September 1 with Q4 campaign brief. AM check-in scheduled August 15.",
    approvalWorkflow: [
      { stage: "Review", assignee: "Sarah Mitchell", status: "Approved", completedDate: "2025-06-21" },
      { stage: "Account Manager Approval", assignee: "Sarah Mitchell", status: "Approved", completedDate: "2025-06-21" },
      { stage: "Billing Approval", assignee: "Billing Team", status: "Approved", completedDate: "2025-06-22" },
      { stage: "Final Approval", assignee: "Director of AM", status: "Approved", completedDate: "2025-06-23" },
    ],
    implementationItems: [
      { area: "Projects Updated", status: "Completed", completedDate: "2025-06-25" },
      { area: "Task Blueprints Updated", status: "Completed", completedDate: "2025-06-25" },
      { area: "Departments Updated", status: "Completed", completedDate: "2025-06-25" },
      { area: "Billing Updated", status: "Completed", completedDate: "2025-06-26" },
      { area: "Contract Updated", status: "Not Required" },
    ],
    implementationStatus: "Completed",
    implementationCompletedDate: "2025-06-26",
    aiImpactAssessment: "Pause impacts $2,500/mo in billing for 2 months ($5,000 total impact). All campaign tasks suspended. 3 departments affected. Reactivation plan is in place.",
    aiRiskAssessment: "Medium risk. Extended pauses beyond 90 days historically correlate with 40% churn rate. Schedule AM check-in before reactivation.",
    aiRecommendedActions: ["Schedule AM check-in August 15", "Prepare Q4 reactivation brief", "Monitor for any client-side signals of non-renewal"],
    aiImplementationPlan: "Suspend all active campaigns July 1. Pause billing for July and August. Create reactivation reminder for September 1. Assign check-in task for August 15.",
    activityTimeline: [
      { date: "2025-06-20", event: "Request Created", actor: "Sarah Mitchell" },
      { date: "2025-06-21", event: "Review Started", actor: "Sarah Mitchell" },
      { date: "2025-06-22", event: "Billing Approval", actor: "Billing Team" },
      { date: "2025-06-23", event: "Final Approval", actor: "Director of AM" },
      { date: "2025-06-25", event: "Projects Updated", actor: "Sarah Mitchell" },
      { date: "2025-06-26", event: "Billing Updated", actor: "Billing Team" },
      { date: "2025-06-26", event: "Request Implemented", actor: "System" },
    ],
    mrrChange: -2500,
    arrChange: 0,
    oneTimeFees: 0,
    credits: 0,
    adjustments: -5000,
  },

  // ── CR-006: Reactivation ───────────────────────────────────────────────────
  {
    id: "CR-006",
    client: "Summit Digital",
    project: "Brand Relaunch",
    requestType: "Reactivation",
    requestedBy: "Rachel Torres",
    requestedByRole: "Account Manager",
    assignedAM: "Rachel Torres",
    revenueImpact: 2200,
    revenueDirection: "Increase",
    departmentsImpacted: ["Paid Advertising", "Content"],
    status: "Submitted",
    submittedDate: "2025-07-02",
    effectiveDate: "2025-07-15",
    description: "Reactivate Summit Digital services following 45-day pause. Reinstate PPC and content services per reactivation plan.",
    clientHealthScore: 72,
    clientHealthStatus: "Needs Attention",
    renewalRisk: "Medium",
    expansionOpportunity: "Medium",
    clientMRR: 2200,
    clientARR: 26400,
    openEscalations: 0,
    openProjects: 1,
    lastCommunication: "2025-07-01",
    aiClientSummary: "Summit Digital is returning from a planned pause. Reactivation aligns with their brand relaunch timeline. Historical performance was solid. Priority is smooth campaign restart.",
    projectsImpacted: ["Brand Relaunch", "PPC Restart"],
    tasksAdded: 14,
    tasksRemoved: 0,
    milestonesAffected: 2,
    contractAmendmentRequired: false,
    billingApprovalStatus: "Pending",
    reactivationPlan: "Reactivate PPC with refreshed Q3 creative. Restart content calendar with new brand messaging. Resume billing July 15.",
    approvalWorkflow: [
      { stage: "Review", assignee: "Rachel Torres", status: "In Progress" },
      { stage: "Department Approval", assignee: "PPC Lead", status: "Pending" },
      { stage: "Billing Approval", assignee: "Billing Team", status: "Pending" },
      { stage: "Final Approval", assignee: "Director of AM", status: "Pending" },
    ],
    implementationItems: [
      { area: "Projects Updated", status: "Pending" },
      { area: "Task Blueprints Updated", status: "Pending" },
      { area: "Departments Updated", status: "Pending" },
      { area: "Billing Updated", status: "Pending" },
      { area: "Contract Updated", status: "Not Required" },
    ],
    implementationStatus: "Not Started",
    aiImpactAssessment: "Reactivation restores $2,200/mo MRR. PPC campaigns need Q3 creative refresh. Content team reassignment required. 14 tasks to be generated from blueprint.",
    aiRiskAssessment: "Low-medium risk. Client returning after short pause with clear plan. Monitor first 30 days for campaign performance.",
    aiRecommendedActions: ["Confirm creative assets are ready", "Schedule campaign restart briefing", "Set 30-day performance review milestone"],
    aiImplementationPlan: "Reactivate PPC campaign with Q3 brief. Restart content calendar. Generate 14 tasks from reactivation blueprint. Resume billing July 15.",
    activityTimeline: [
      { date: "2025-07-02", event: "Request Created", actor: "Rachel Torres" },
      { date: "2025-07-02", event: "Review Started", actor: "Rachel Torres" },
    ],
    mrrChange: 2200,
    arrChange: 26400,
    oneTimeFees: 0,
    credits: 0,
    adjustments: 0,
  },

  // ── CR-007: Service Removal ────────────────────────────────────────────────
  {
    id: "CR-007",
    client: "Cobalt Systems",
    project: "Digital Presence Management",
    requestType: "Service Removal",
    requestedBy: "Sarah Mitchell",
    requestedByRole: "Account Manager",
    assignedAM: "Sarah Mitchell",
    revenueImpact: -800,
    revenueDirection: "Decrease",
    departmentsImpacted: ["GBP"],
    status: "Implemented",
    submittedDate: "2025-06-05",
    effectiveDate: "2025-06-15",
    description: "Remove GBP management service. Client has brought GBP in-house. Service terminated by mutual agreement.",
    clientHealthScore: 82,
    clientHealthStatus: "Healthy",
    renewalRisk: "Low",
    expansionOpportunity: "Low",
    clientMRR: 3500,
    clientARR: 42000,
    openEscalations: 0,
    openProjects: 2,
    lastCommunication: "2025-06-10",
    aiClientSummary: "Cobalt Systems is stable and healthy. GBP removal is strategic — they have in-house resources. Core SEO services remain intact. No churn risk.",
    projectsImpacted: ["Digital Presence Management"],
    tasksAdded: 0,
    tasksRemoved: 8,
    milestonesAffected: 1,
    contractAmendmentRequired: true,
    billingApprovalStatus: "Approved",
    serviceRemoved: "GBP Management",
    removedDeliverables: ["GBP Optimization", "GBP Post Scheduling", "Review Management"],
    approvalWorkflow: [
      { stage: "Review", assignee: "Sarah Mitchell", status: "Approved", completedDate: "2025-06-06" },
      { stage: "Department Approval", assignee: "GBP Lead", status: "Approved", completedDate: "2025-06-07" },
      { stage: "Billing Approval", assignee: "Billing Team", status: "Approved", completedDate: "2025-06-08" },
      { stage: "Final Approval", assignee: "Director of AM", status: "Approved", completedDate: "2025-06-09" },
    ],
    implementationItems: [
      { area: "Projects Updated", status: "Completed", completedDate: "2025-06-12" },
      { area: "Task Blueprints Updated", status: "Completed", completedDate: "2025-06-12" },
      { area: "Departments Updated", status: "Completed", completedDate: "2025-06-12" },
      { area: "Billing Updated", status: "Completed", completedDate: "2025-06-13" },
      { area: "Contract Updated", status: "Completed", completedDate: "2025-06-14" },
    ],
    implementationStatus: "Completed",
    implementationCompletedDate: "2025-06-14",
    aiImpactAssessment: "Service removal reduces MRR by $800. GBP tasks removed from blueprint. Contract amended. Client retains core SEO services.",
    aiRiskAssessment: "Low risk. Mutual agreement. Client bringing service in-house is a common transition.",
    aiRecommendedActions: ["Document GBP removal rationale", "Offer GBP consulting in future if needed", "Monitor client health post-removal"],
    aiImplementationPlan: "Remove GBP tasks from active projects. Archive GBP task blueprint. Update contract to remove GBP line. Update billing effective June 15.",
    activityTimeline: [
      { date: "2025-06-05", event: "Request Created", actor: "Sarah Mitchell" },
      { date: "2025-06-06", event: "Review Started", actor: "Sarah Mitchell" },
      { date: "2025-06-08", event: "Billing Approval", actor: "Billing Team" },
      { date: "2025-06-09", event: "Final Approval", actor: "Director of AM" },
      { date: "2025-06-12", event: "Projects Updated", actor: "Sarah Mitchell" },
      { date: "2025-06-13", event: "Billing Updated", actor: "Billing Team" },
      { date: "2025-06-14", event: "Contract Updated", actor: "Contracts Team" },
      { date: "2025-06-14", event: "Request Implemented", actor: "System" },
    ],
    mrrChange: -800,
    arrChange: -9600,
    oneTimeFees: 0,
    credits: 0,
    adjustments: 0,
  },

  // ── CR-008: Contract Amendment ─────────────────────────────────────────────
  {
    id: "CR-008",
    client: "Harmon & Associates",
    project: "Full Service Marketing",
    requestType: "Contract Amendment",
    requestedBy: "James Carter",
    requestedByRole: "Account Manager",
    assignedAM: "James Carter",
    revenueImpact: -1000,
    revenueDirection: "Decrease",
    departmentsImpacted: ["SEO", "Paid Advertising", "Content"],
    status: "Pending Approval",
    submittedDate: "2025-06-25",
    effectiveDate: "2025-08-01",
    description: "Amend contract to reflect adjusted pricing terms following renewal negotiation. $1,000/mo reduction in exchange for 12-month contract extension.",
    clientHealthScore: 60,
    clientHealthStatus: "Needs Attention",
    renewalRisk: "High",
    expansionOpportunity: "Low",
    clientMRR: 7000,
    clientARR: 84000,
    openEscalations: 3,
    openProjects: 4,
    lastCommunication: "2025-06-24",
    aiClientSummary: "Harmon & Associates is at renewal risk. The contract amendment is a retention play — $1,000/mo reduction in exchange for a 12-month extension. Net revenue impact is positive long-term.",
    projectsImpacted: ["Full Service Marketing"],
    tasksAdded: 0,
    tasksRemoved: 0,
    milestonesAffected: 0,
    contractAmendmentRequired: true,
    billingApprovalStatus: "Pending",
    currentContract: "Month-to-month, $7,000/mo",
    proposedContract: "12-month term, $6,000/mo",
    approvalWorkflow: [
      { stage: "Review", assignee: "James Carter", status: "Approved", completedDate: "2025-06-26" },
      { stage: "Account Manager Approval", assignee: "James Carter", status: "Approved", completedDate: "2025-06-26" },
      { stage: "Billing Approval", assignee: "Billing Team", status: "In Progress" },
      { stage: "Executive Approval", assignee: "VP of Operations", status: "Pending" },
      { stage: "Final Approval", assignee: "Director of AM", status: "Pending" },
    ],
    implementationItems: [
      { area: "Projects Updated", status: "Not Required" },
      { area: "Task Blueprints Updated", status: "Not Required" },
      { area: "Departments Updated", status: "Not Required" },
      { area: "Billing Updated", status: "Pending" },
      { area: "Contract Updated", status: "Pending" },
    ],
    implementationStatus: "Not Started",
    aiImpactAssessment: "Short-term MRR reduction of $1,000 in exchange for 12-month contract lock. Net annual impact: +$60,000 locked ARR. Strategic retention move.",
    aiRiskAssessment: "Medium risk. Client has 3 open escalations. Contract amendment is contingent on client signing. Executive approval required.",
    aiRecommendedActions: ["Resolve open escalations before contract signature", "Prepare amended contract draft", "Schedule client signing call"],
    aiImplementationPlan: "Draft amended contract. Obtain executive approval. Client signature. Update billing effective August 1. Close escalations.",
    activityTimeline: [
      { date: "2025-06-25", event: "Request Created", actor: "James Carter" },
      { date: "2025-06-26", event: "Review Started", actor: "James Carter" },
      { date: "2025-06-27", event: "Billing Approval Requested", actor: "System" },
    ],
    mrrChange: -1000,
    arrChange: 0,
    oneTimeFees: 0,
    credits: 0,
    adjustments: 0,
  },

  // ── CR-009: Budget Reallocation ────────────────────────────────────────────
  {
    id: "CR-009",
    client: "Pinnacle Home Services",
    project: "Lead Generation Suite",
    requestType: "Budget Reallocation",
    requestedBy: "Rachel Torres",
    requestedByRole: "Account Manager",
    assignedAM: "Rachel Torres",
    revenueImpact: 0,
    revenueDirection: "Neutral",
    departmentsImpacted: ["GBP", "Local Service Ads"],
    status: "Approved",
    submittedDate: "2025-06-18",
    effectiveDate: "2025-07-01",
    description: "Reallocate $600/mo from GBP management to LSA to prioritize verified lead generation over organic listing optimization.",
    clientHealthScore: 85,
    clientHealthStatus: "Healthy",
    renewalRisk: "Low",
    expansionOpportunity: "Medium",
    clientMRR: 2800,
    clientARR: 33600,
    openEscalations: 0,
    openProjects: 2,
    lastCommunication: "2025-06-19",
    aiClientSummary: "Pinnacle Home Services is a seasonal business with strong summer demand. LSA reallocation is well-timed for peak season. No health concerns.",
    projectsImpacted: ["Lead Generation Suite"],
    tasksAdded: 3,
    tasksRemoved: 3,
    milestonesAffected: 0,
    contractAmendmentRequired: false,
    billingApprovalStatus: "Approved",
    budgetLines: [
      { service: "GBP Management", department: "GBP", currentBudget: 800, proposedBudget: 200, difference: -600 },
      { service: "LSA Management", department: "Local Service Ads", currentBudget: 600, proposedBudget: 1200, difference: 600 },
    ],
    approvalWorkflow: [
      { stage: "Review", assignee: "Rachel Torres", status: "Approved", completedDate: "2025-06-19" },
      { stage: "Department Approval", assignee: "GBP Lead", status: "Approved", completedDate: "2025-06-20" },
      { stage: "Billing Approval", assignee: "Billing Team", status: "Approved", completedDate: "2025-06-21" },
      { stage: "Final Approval", assignee: "Director of AM", status: "Approved", completedDate: "2025-06-22" },
    ],
    implementationItems: [
      { area: "Projects Updated", status: "Completed", completedDate: "2025-06-24" },
      { area: "Task Blueprints Updated", status: "Completed", completedDate: "2025-06-24" },
      { area: "Departments Updated", status: "Completed", completedDate: "2025-06-24" },
      { area: "Billing Updated", status: "Completed", completedDate: "2025-06-25" },
      { area: "Contract Updated", status: "Not Required" },
    ],
    implementationStatus: "Completed",
    implementationCompletedDate: "2025-06-25",
    aiImpactAssessment: "Budget-neutral reallocation. LSA allocation increase aligns with peak seasonal demand. GBP tasks reduced from 6 to 2 per month.",
    aiRiskAssessment: "Low risk. Both departments are staffed and operational.",
    aiRecommendedActions: ["Monitor LSA lead quality post-reallocation", "Review GBP performance monthly"],
    aiImplementationPlan: "Adjust GBP budget cap down. Increase LSA budget cap. Swap 3 GBP tasks for 3 LSA tasks in project.",
    activityTimeline: [
      { date: "2025-06-18", event: "Request Created", actor: "Rachel Torres" },
      { date: "2025-06-19", event: "Review Started", actor: "Rachel Torres" },
      { date: "2025-06-22", event: "Final Approval", actor: "Director of AM" },
      { date: "2025-06-25", event: "Request Implemented", actor: "System" },
    ],
    mrrChange: 0,
    arrChange: 0,
    oneTimeFees: 0,
    credits: 0,
    adjustments: 0,
  },

  // ── CR-010: Custom Scope Change ────────────────────────────────────────────
  {
    id: "CR-010",
    client: "Apex Dental Group",
    project: "Multi-Location Marketing",
    requestType: "Custom Scope Change",
    requestedBy: "Sarah Mitchell",
    requestedByRole: "Account Manager",
    assignedAM: "Sarah Mitchell",
    revenueImpact: 2000,
    revenueDirection: "Increase",
    departmentsImpacted: ["SEO", "GBP", "Reporting"],
    status: "Under Review",
    submittedDate: "2025-07-01",
    description: "Add third practice location to all active service scopes. Expand SEO, GBP, and reporting to cover new Westside Dental location.",
    clientHealthScore: 90,
    clientHealthStatus: "Healthy",
    renewalRisk: "Low",
    expansionOpportunity: "High",
    clientMRR: 6000,
    clientARR: 72000,
    openEscalations: 0,
    openProjects: 4,
    lastCommunication: "2025-07-01",
    aiClientSummary: "Apex Dental Group is expanding. Adding a third location is a revenue growth opportunity. All departments have capacity. High priority for fast activation.",
    projectsImpacted: ["Multi-Location Marketing", "SEO Westside", "GBP Westside"],
    tasksAdded: 28,
    tasksRemoved: 0,
    milestonesAffected: 3,
    contractAmendmentRequired: true,
    billingApprovalStatus: "Pending",
    approvalWorkflow: [
      { stage: "Review", assignee: "Sarah Mitchell", status: "In Progress" },
      { stage: "Department Approval", assignee: "SEO Lead", status: "Pending" },
      { stage: "Billing Approval", assignee: "Billing Team", status: "Pending" },
      { stage: "Executive Approval", assignee: "VP of Operations", status: "Pending" },
      { stage: "Final Approval", assignee: "Director of AM", status: "Pending" },
    ],
    implementationItems: [
      { area: "Projects Updated", status: "Pending" },
      { area: "Task Blueprints Updated", status: "Pending" },
      { area: "Departments Updated", status: "Pending" },
      { area: "Billing Updated", status: "Pending" },
      { area: "Contract Updated", status: "Pending" },
    ],
    implementationStatus: "Not Started",
    aiImpactAssessment: "Adding a third location increases MRR by $2,000. 28 new tasks across SEO, GBP, and reporting. Contract amendment required. High-value expansion.",
    aiRiskAssessment: "Low risk. Client is healthy. Departments have capacity. Contract needs to be updated to reflect third-location terms.",
    aiRecommendedActions: ["Fast-track approval given high client value", "Prepare location-3 task blueprints", "Amend contract immediately upon approval"],
    aiImplementationPlan: "Create location 3 project. Generate SEO, GBP, and reporting blueprints for Westside location. Amend contract. Update billing to $8,000/mo.",
    activityTimeline: [
      { date: "2025-07-01", event: "Request Created", actor: "Sarah Mitchell" },
      { date: "2025-07-01", event: "Review Started", actor: "Sarah Mitchell" },
    ],
    mrrChange: 2000,
    arrChange: 24000,
    oneTimeFees: 250,
    credits: 0,
    adjustments: 0,
  },

  // ── CR-011: Service Addition ───────────────────────────────────────────────
  {
    id: "CR-011",
    client: "RiverBend Roofing",
    project: "Digital Lead Program",
    requestType: "Service Addition",
    requestedBy: "James Carter",
    requestedByRole: "Account Manager",
    assignedAM: "James Carter",
    revenueImpact: 900,
    revenueDirection: "Increase",
    departmentsImpacted: ["Yelp"],
    status: "Submitted",
    submittedDate: "2025-07-03",
    description: "Add Yelp Ads management to existing digital lead program. Client wants to capture Yelp review traffic.",
    clientHealthScore: 77,
    clientHealthStatus: "Healthy",
    renewalRisk: "Low",
    expansionOpportunity: "Medium",
    clientMRR: 2200,
    clientARR: 26400,
    openEscalations: 0,
    openProjects: 2,
    lastCommunication: "2025-07-02",
    aiClientSummary: "RiverBend Roofing has good organic performance. Yelp Ads addition is a natural next step given their strong review profile.",
    projectsImpacted: ["Digital Lead Program"],
    tasksAdded: 6,
    tasksRemoved: 0,
    milestonesAffected: 1,
    contractAmendmentRequired: false,
    billingApprovalStatus: "Pending",
    serviceAdded: "Yelp Ads Management",
    newDeliverables: ["Yelp Ad Setup", "Yelp Budget Management", "Yelp Monthly Report"],
    approvalWorkflow: [
      { stage: "Review", assignee: "James Carter", status: "In Progress" },
      { stage: "Department Approval", assignee: "Yelp Lead", status: "Pending" },
      { stage: "Billing Approval", assignee: "Billing Team", status: "Pending" },
      { stage: "Final Approval", assignee: "Director of AM", status: "Pending" },
    ],
    implementationItems: [
      { area: "Projects Updated", status: "Pending" },
      { area: "Task Blueprints Updated", status: "Pending" },
      { area: "Departments Updated", status: "Pending" },
      { area: "Billing Updated", status: "Pending" },
      { area: "Contract Updated", status: "Not Required" },
    ],
    implementationStatus: "Not Started",
    aiImpactAssessment: "Addition of Yelp Ads increases MRR by $900. 6 new tasks. Yelp department activation required.",
    aiRiskAssessment: "Low risk. Straightforward service addition.",
    aiRecommendedActions: ["Activate Yelp department", "Generate task blueprint", "Set up Yelp Ads account access"],
    aiImplementationPlan: "Generate Yelp Ads blueprint. Create Yelp tasks in Digital Lead Program project. Update billing to $3,100/mo.",
    activityTimeline: [
      { date: "2025-07-03", event: "Request Created", actor: "James Carter" },
      { date: "2025-07-03", event: "Review Started", actor: "James Carter" },
    ],
    mrrChange: 900,
    arrChange: 10800,
    oneTimeFees: 0,
    credits: 0,
    adjustments: 0,
  },

  // ── CR-012: Service Downgrade ──────────────────────────────────────────────
  {
    id: "CR-012",
    client: "Metro Law Group",
    project: "Legal Marketing Program",
    requestType: "Service Downgrade",
    requestedBy: "Rachel Torres",
    requestedByRole: "Account Manager",
    assignedAM: "Rachel Torres",
    revenueImpact: -2500,
    revenueDirection: "Decrease",
    departmentsImpacted: ["Paid Advertising", "Content"],
    status: "Rejected",
    submittedDate: "2025-06-12",
    description: "Client requested removal of PPC and content services. Internal review rejected — legal vertical requires full-funnel approach.",
    clientHealthScore: 68,
    clientHealthStatus: "Needs Attention",
    renewalRisk: "High",
    expansionOpportunity: "Low",
    clientMRR: 5500,
    clientARR: 66000,
    openEscalations: 2,
    openProjects: 3,
    lastCommunication: "2025-06-20",
    aiClientSummary: "Metro Law Group is showing signs of dissatisfaction. Downgrade rejected due to operational concerns. Retention plan recommended.",
    projectsImpacted: ["Legal Marketing Program"],
    tasksAdded: 0,
    tasksRemoved: 0,
    milestonesAffected: 0,
    contractAmendmentRequired: false,
    billingApprovalStatus: "Not Required",
    currentPackage: "Full Funnel Legal ($5,500/mo)",
    newPackage: "SEO Only ($3,000/mo)",
    removedDeliverables: ["PPC Management", "Content Production"],
    approvalWorkflow: [
      { stage: "Review", assignee: "Rachel Torres", status: "Rejected", completedDate: "2025-06-14", notes: "Rejected: Legal vertical requires full-funnel approach. PPC and content are interdependent." },
      { stage: "Department Approval", assignee: "Operations Lead", status: "Rejected", completedDate: "2025-06-14" },
      { stage: "Final Approval", assignee: "Director of AM", status: "Rejected", completedDate: "2025-06-15" },
    ],
    implementationItems: [
      { area: "Projects Updated", status: "Not Required" },
      { area: "Task Blueprints Updated", status: "Not Required" },
      { area: "Departments Updated", status: "Not Required" },
      { area: "Billing Updated", status: "Not Required" },
      { area: "Contract Updated", status: "Not Required" },
    ],
    implementationStatus: "Not Started",
    aiImpactAssessment: "Downgrade rejected. Recommend retention conversation to address underlying client concerns.",
    aiRiskAssessment: "High risk. Client dissatisfaction may lead to cancellation. Retention plan critical.",
    aiRecommendedActions: ["Initiate retention conversation", "Address client performance concerns directly", "Offer temporary billing credit to maintain relationship"],
    aiImplementationPlan: "No implementation required. Initiate retention plan.",
    activityTimeline: [
      { date: "2025-06-12", event: "Request Created", actor: "Rachel Torres" },
      { date: "2025-06-14", event: "Review Started", actor: "Rachel Torres" },
      { date: "2025-06-15", event: "Request Rejected", actor: "Director of AM", note: "Legal vertical requires full-funnel approach" },
    ],
    mrrChange: 0,
    arrChange: 0,
    oneTimeFees: 0,
    credits: 0,
    adjustments: 0,
  },

  // ── CR-013: Budget Reallocation ────────────────────────────────────────────
  {
    id: "CR-013",
    client: "Sunrise HVAC",
    project: "Seasonal Campaign",
    requestType: "Budget Reallocation",
    requestedBy: "Sarah Mitchell",
    requestedByRole: "Account Manager",
    assignedAM: "Sarah Mitchell",
    revenueImpact: 0,
    revenueDirection: "Neutral",
    departmentsImpacted: ["Local Service Ads", "GBP"],
    status: "Draft",
    submittedDate: "2025-07-04",
    description: "Draft reallocation for summer peak: shift $500 from GBP to LSA to maximize summer lead capture. Not yet submitted.",
    clientHealthScore: 79,
    clientHealthStatus: "Healthy",
    renewalRisk: "Low",
    expansionOpportunity: "Medium",
    clientMRR: 1800,
    clientARR: 21600,
    openEscalations: 0,
    openProjects: 2,
    lastCommunication: "2025-07-03",
    aiClientSummary: "Sunrise HVAC has a strong seasonal pattern. Summer peak demands more LSA budget for AC installation leads. Draft reallocation is strategic.",
    projectsImpacted: ["Seasonal Campaign"],
    tasksAdded: 2,
    tasksRemoved: 2,
    milestonesAffected: 0,
    contractAmendmentRequired: false,
    billingApprovalStatus: "Not Required",
    budgetLines: [
      { service: "GBP Management", department: "GBP", currentBudget: 600, proposedBudget: 100, difference: -500 },
      { service: "LSA Management", department: "Local Service Ads", currentBudget: 400, proposedBudget: 900, difference: 500 },
    ],
    approvalWorkflow: [
      { stage: "Review", assignee: "Sarah Mitchell", status: "Pending" },
      { stage: "Department Approval", assignee: "GBP Lead", status: "Pending" },
      { stage: "Billing Approval", assignee: "Billing Team", status: "Pending" },
      { stage: "Final Approval", assignee: "Director of AM", status: "Pending" },
    ],
    implementationItems: [
      { area: "Projects Updated", status: "Pending" },
      { area: "Task Blueprints Updated", status: "Pending" },
      { area: "Departments Updated", status: "Pending" },
      { area: "Billing Updated", status: "Pending" },
      { area: "Contract Updated", status: "Not Required" },
    ],
    implementationStatus: "Not Started",
    aiImpactAssessment: "Draft stage. Budget-neutral reallocation aligned with seasonal demand. Ready to submit.",
    aiRiskAssessment: "Low risk. Seasonal reallocation is standard practice for HVAC clients.",
    aiRecommendedActions: ["Submit for review", "Confirm LSA department capacity"],
    aiImplementationPlan: "On approval: adjust GBP budget cap, increase LSA cap, swap tasks.",
    activityTimeline: [
      { date: "2025-07-04", event: "Request Created (Draft)", actor: "Sarah Mitchell" },
    ],
    mrrChange: 0,
    arrChange: 0,
    oneTimeFees: 0,
    credits: 0,
    adjustments: 0,
  },

  // ── CR-014: Service Upgrade ────────────────────────────────────────────────
  {
    id: "CR-014",
    client: "Lakefront Auto Group",
    project: "Automotive Digital Marketing",
    requestType: "Service Upgrade",
    requestedBy: "James Carter",
    requestedByRole: "Account Manager",
    assignedAM: "James Carter",
    revenueImpact: 1800,
    revenueDirection: "Increase",
    departmentsImpacted: ["Paid Advertising", "Reporting"],
    status: "Pending Approval",
    submittedDate: "2025-06-30",
    effectiveDate: "2025-07-15",
    description: "Upgrade from Standard PPC to Premium PPC with advanced audience targeting and bi-weekly reporting.",
    clientHealthScore: 83,
    clientHealthStatus: "Healthy",
    renewalRisk: "Low",
    expansionOpportunity: "High",
    clientMRR: 4200,
    clientARR: 50400,
    openEscalations: 0,
    openProjects: 3,
    lastCommunication: "2025-06-29",
    aiClientSummary: "Lakefront Auto Group is a growing dealership. Premium PPC with advanced targeting is a natural upgrade given their expansion to 3 dealership locations.",
    projectsImpacted: ["Automotive Digital Marketing", "PPC Premium Activation"],
    tasksAdded: 10,
    tasksRemoved: 2,
    milestonesAffected: 2,
    contractAmendmentRequired: false,
    billingApprovalStatus: "In Progress",
    currentPackage: "Standard PPC ($2,400/mo)",
    newPackage: "Premium PPC ($4,200/mo)",
    newDeliverables: ["Advanced Audience Targeting", "Bi-weekly Reporting", "Display Network Campaigns", "YouTube Pre-roll"],
    additionalDepartments: ["Reporting"],
    approvalWorkflow: [
      { stage: "Review", assignee: "James Carter", status: "Approved", completedDate: "2025-07-01" },
      { stage: "Department Approval", assignee: "PPC Lead", status: "Approved", completedDate: "2025-07-01" },
      { stage: "Account Manager Approval", assignee: "James Carter", status: "Approved", completedDate: "2025-07-01" },
      { stage: "Billing Approval", assignee: "Billing Team", status: "In Progress" },
      { stage: "Final Approval", assignee: "Director of AM", status: "Pending" },
    ],
    implementationItems: [
      { area: "Projects Updated", status: "Pending" },
      { area: "Task Blueprints Updated", status: "Pending" },
      { area: "Departments Updated", status: "Pending" },
      { area: "Billing Updated", status: "Pending" },
      { area: "Contract Updated", status: "Not Required" },
    ],
    implementationStatus: "Not Started",
    aiImpactAssessment: "Upgrade increases MRR by $1,800. Advanced targeting requires audience research sprint. Reporting department activated for bi-weekly cadence.",
    aiRiskAssessment: "Low risk. Client is healthy and eager for upgrade. Billing approval in progress.",
    aiRecommendedActions: ["Confirm billing approval timeline", "Schedule Premium PPC kickoff call", "Build audience segments before go-live"],
    aiImplementationPlan: "Upgrade PPC blueprint to Premium tier. Add Display and YouTube campaign tasks. Activate Reporting for bi-weekly cadence. Update billing effective July 15.",
    activityTimeline: [
      { date: "2025-06-30", event: "Request Created", actor: "James Carter" },
      { date: "2025-07-01", event: "Department Approval", actor: "PPC Lead" },
      { date: "2025-07-01", event: "Billing Approval Requested", actor: "System" },
    ],
    mrrChange: 1800,
    arrChange: 21600,
    oneTimeFees: 0,
    credits: 0,
    adjustments: 0,
  },

  // ── CR-015: Pause ──────────────────────────────────────────────────────────
  {
    id: "CR-015",
    client: "Blue Ridge Landscaping",
    project: "Seasonal Digital",
    requestType: "Pause",
    requestedBy: "Blue Ridge (Client)",
    requestedByRole: "Client Contact",
    assignedAM: "Rachel Torres",
    revenueImpact: -1200,
    revenueDirection: "Decrease",
    departmentsImpacted: ["Paid Advertising"],
    status: "Under Review",
    submittedDate: "2025-07-02",
    effectiveDate: "2025-07-31",
    description: "Pause PPC campaigns during off-season (August through November). Client confirmed reactivation in December for spring prep.",
    clientHealthScore: 75,
    clientHealthStatus: "Healthy",
    renewalRisk: "Medium",
    expansionOpportunity: "Low",
    clientMRR: 1800,
    clientARR: 21600,
    openEscalations: 0,
    openProjects: 2,
    lastCommunication: "2025-07-01",
    aiClientSummary: "Blue Ridge Landscaping has a clear seasonal pattern. Summer PPC pause is expected. December reactivation for spring season prep is confirmed.",
    projectsImpacted: ["Seasonal Digital"],
    tasksAdded: 0,
    tasksRemoved: 0,
    milestonesAffected: 3,
    contractAmendmentRequired: false,
    billingApprovalStatus: "Pending",
    pauseStartDate: "2025-07-31",
    pauseEndDate: "2025-11-30",
    pauseReason: "Off-season — landscaping demand low August through November.",
    reactivationPlan: "December 1 reactivation for spring prep campaigns. AM check-in November 15.",
    approvalWorkflow: [
      { stage: "Review", assignee: "Rachel Torres", status: "In Progress" },
      { stage: "Billing Approval", assignee: "Billing Team", status: "Pending" },
      { stage: "Final Approval", assignee: "Director of AM", status: "Pending" },
    ],
    implementationItems: [
      { area: "Projects Updated", status: "Pending" },
      { area: "Task Blueprints Updated", status: "Pending" },
      { area: "Departments Updated", status: "Pending" },
      { area: "Billing Updated", status: "Pending" },
      { area: "Contract Updated", status: "Not Required" },
    ],
    implementationStatus: "Not Started",
    aiImpactAssessment: "PPC pause reduces MRR by $1,200 for 4 months. Total billing impact: $4,800. December reactivation planned.",
    aiRiskAssessment: "Low-medium risk. Seasonal client — pause is expected. Set reactivation reminder.",
    aiRecommendedActions: ["Set reactivation reminder for November 15", "Prepare December spring campaign brief", "Confirm billing pause terms"],
    aiImplementationPlan: "Pause PPC billing August 1. Suspend campaign tasks. Create December 1 reactivation reminder. Assign November 15 check-in task.",
    activityTimeline: [
      { date: "2025-07-02", event: "Request Created", actor: "Rachel Torres" },
      { date: "2025-07-02", event: "Review Started", actor: "Rachel Torres" },
    ],
    mrrChange: -1200,
    arrChange: 0,
    oneTimeFees: 0,
    credits: 0,
    adjustments: -4800,
  },

  // ── CR-016: Contract Amendment ─────────────────────────────────────────────
  {
    id: "CR-016",
    client: "Cascade Health Systems",
    project: "Healthcare Marketing",
    requestType: "Contract Amendment",
    requestedBy: "Sarah Mitchell",
    requestedByRole: "Account Manager",
    assignedAM: "Sarah Mitchell",
    revenueImpact: 500,
    revenueDirection: "Increase",
    departmentsImpacted: ["SEO", "Content"],
    status: "Implemented",
    submittedDate: "2025-05-20",
    effectiveDate: "2025-06-01",
    description: "Amend contract to add HIPAA-compliant content addendum and increase content production from 4 to 6 pieces per month.",
    clientHealthScore: 87,
    clientHealthStatus: "Healthy",
    renewalRisk: "Low",
    expansionOpportunity: "Medium",
    clientMRR: 4800,
    clientARR: 57600,
    openEscalations: 0,
    openProjects: 3,
    lastCommunication: "2025-06-15",
    aiClientSummary: "Cascade Health Systems requires HIPAA-compliant content workflows. Contract amendment adds compliance addendum and scales content production.",
    projectsImpacted: ["Healthcare Marketing", "Content Calendar"],
    tasksAdded: 6,
    tasksRemoved: 0,
    milestonesAffected: 1,
    contractAmendmentRequired: true,
    billingApprovalStatus: "Approved",
    currentContract: "$4,300/mo — 4 content pieces, standard terms",
    proposedContract: "$4,800/mo — 6 content pieces, HIPAA-compliant addendum",
    approvalWorkflow: [
      { stage: "Review", assignee: "Sarah Mitchell", status: "Approved", completedDate: "2025-05-21" },
      { stage: "Department Approval", assignee: "Content Lead", status: "Approved", completedDate: "2025-05-22" },
      { stage: "Billing Approval", assignee: "Billing Team", status: "Approved", completedDate: "2025-05-23" },
      { stage: "Executive Approval", assignee: "VP of Operations", status: "Approved", completedDate: "2025-05-25" },
      { stage: "Final Approval", assignee: "Director of AM", status: "Approved", completedDate: "2025-05-26" },
    ],
    implementationItems: [
      { area: "Projects Updated", status: "Completed", completedDate: "2025-05-28" },
      { area: "Task Blueprints Updated", status: "Completed", completedDate: "2025-05-28" },
      { area: "Departments Updated", status: "Completed", completedDate: "2025-05-29" },
      { area: "Billing Updated", status: "Completed", completedDate: "2025-05-30" },
      { area: "Contract Updated", status: "Completed", completedDate: "2025-05-31" },
    ],
    implementationStatus: "Completed",
    implementationCompletedDate: "2025-05-31",
    aiImpactAssessment: "Contract amendment increases MRR by $500. HIPAA addendum reduces compliance risk. Content team capacity increase of 2 pieces/month.",
    aiRiskAssessment: "Low risk. All approvals complete. HIPAA addendum reviewed by legal.",
    aiRecommendedActions: ["Monitor HIPAA-compliant content workflow", "Confirm content team HIPAA training complete"],
    aiImplementationPlan: "Attach HIPAA addendum to contract. Update billing. Add 2 content tasks per month to project blueprint.",
    activityTimeline: [
      { date: "2025-05-20", event: "Request Created", actor: "Sarah Mitchell" },
      { date: "2025-05-22", event: "Department Approval", actor: "Content Lead" },
      { date: "2025-05-26", event: "Final Approval", actor: "Director of AM" },
      { date: "2025-05-31", event: "Contract Updated", actor: "Contracts Team" },
      { date: "2025-05-31", event: "Request Implemented", actor: "System" },
    ],
    mrrChange: 500,
    arrChange: 6000,
    oneTimeFees: 0,
    credits: 0,
    adjustments: 0,
  },

  // ── CR-017: Reactivation ───────────────────────────────────────────────────
  {
    id: "CR-017",
    client: "Ironclad Pest Control",
    project: "Digital Lead Generation",
    requestType: "Reactivation",
    requestedBy: "James Carter",
    requestedByRole: "Account Manager",
    assignedAM: "James Carter",
    revenueImpact: 1600,
    revenueDirection: "Increase",
    departmentsImpacted: ["LSA", "GBP"],
    status: "Approved",
    submittedDate: "2025-06-22",
    effectiveDate: "2025-07-01",
    description: "Reactivate LSA and GBP services after 30-day pause. Client returning from budget freeze with renewed contract.",
    clientHealthScore: 81,
    clientHealthStatus: "Healthy",
    renewalRisk: "Low",
    expansionOpportunity: "Medium",
    clientMRR: 1600,
    clientARR: 19200,
    openEscalations: 0,
    openProjects: 1,
    lastCommunication: "2025-06-20",
    aiClientSummary: "Ironclad Pest Control is returning from a short pause. Budget freeze resolved. Full reactivation with no scope changes. High confidence in smooth restart.",
    projectsImpacted: ["Digital Lead Generation"],
    tasksAdded: 10,
    tasksRemoved: 0,
    milestonesAffected: 1,
    contractAmendmentRequired: false,
    billingApprovalStatus: "Approved",
    reactivationPlan: "Resume LSA campaigns and GBP optimization. Update lead routing. Resume billing July 1.",
    approvalWorkflow: [
      { stage: "Review", assignee: "James Carter", status: "Approved", completedDate: "2025-06-23" },
      { stage: "Billing Approval", assignee: "Billing Team", status: "Approved", completedDate: "2025-06-24" },
      { stage: "Final Approval", assignee: "Director of AM", status: "Approved", completedDate: "2025-06-25" },
    ],
    implementationItems: [
      { area: "Projects Updated", status: "Completed", completedDate: "2025-06-27" },
      { area: "Task Blueprints Updated", status: "Completed", completedDate: "2025-06-27" },
      { area: "Departments Updated", status: "Completed", completedDate: "2025-06-27" },
      { area: "Billing Updated", status: "Completed", completedDate: "2025-06-28" },
      { area: "Contract Updated", status: "Not Required" },
    ],
    implementationStatus: "Completed",
    implementationCompletedDate: "2025-06-28",
    aiImpactAssessment: "Reactivation restores $1,600/mo MRR. All tasks regenerated from blueprint. Smooth restart.",
    aiRiskAssessment: "Low risk. Short pause, confirmed reactivation.",
    aiRecommendedActions: ["Monitor first 2 weeks of campaign performance", "Confirm lead routing is correct"],
    aiImplementationPlan: "Regenerate tasks from blueprint. Reactivate LSA and GBP campaigns. Resume billing July 1.",
    activityTimeline: [
      { date: "2025-06-22", event: "Request Created", actor: "James Carter" },
      { date: "2025-06-23", event: "Review Started", actor: "James Carter" },
      { date: "2025-06-25", event: "Final Approval", actor: "Director of AM" },
      { date: "2025-06-28", event: "Request Implemented", actor: "System" },
    ],
    mrrChange: 1600,
    arrChange: 19200,
    oneTimeFees: 0,
    credits: 0,
    adjustments: 0,
  },

  // ── CR-018: Service Addition ───────────────────────────────────────────────
  {
    id: "CR-018",
    client: "Modern Eye Care",
    project: "Patient Acquisition",
    requestType: "Service Addition",
    requestedBy: "Rachel Torres",
    requestedByRole: "Account Manager",
    assignedAM: "Rachel Torres",
    revenueImpact: 1200,
    revenueDirection: "Increase",
    departmentsImpacted: ["Content"],
    status: "Submitted",
    submittedDate: "2025-07-03",
    description: "Add blog content production service to patient acquisition program. 4 HIPAA-safe blog posts per month for SEO.",
    clientHealthScore: 84,
    clientHealthStatus: "Healthy",
    renewalRisk: "Low",
    expansionOpportunity: "Medium",
    clientMRR: 3100,
    clientARR: 37200,
    openEscalations: 0,
    openProjects: 2,
    lastCommunication: "2025-07-02",
    aiClientSummary: "Modern Eye Care has a strong local SEO foundation. Adding content production will accelerate organic rankings for eye care search terms.",
    projectsImpacted: ["Patient Acquisition"],
    tasksAdded: 8,
    tasksRemoved: 0,
    milestonesAffected: 1,
    contractAmendmentRequired: false,
    billingApprovalStatus: "Pending",
    serviceAdded: "Blog Content Production",
    newDeliverables: ["4 Blog Posts/month", "Content Calendar", "SEO-Optimized Copy", "CTA Integration"],
    approvalWorkflow: [
      { stage: "Review", assignee: "Rachel Torres", status: "In Progress" },
      { stage: "Department Approval", assignee: "Content Lead", status: "Pending" },
      { stage: "Billing Approval", assignee: "Billing Team", status: "Pending" },
      { stage: "Final Approval", assignee: "Director of AM", status: "Pending" },
    ],
    implementationItems: [
      { area: "Projects Updated", status: "Pending" },
      { area: "Task Blueprints Updated", status: "Pending" },
      { area: "Departments Updated", status: "Pending" },
      { area: "Billing Updated", status: "Pending" },
      { area: "Contract Updated", status: "Not Required" },
    ],
    implementationStatus: "Not Started",
    aiImpactAssessment: "Content addition increases MRR by $1,200. 8 new tasks in Content department. Low complexity.",
    aiRiskAssessment: "Low risk. Content team has capacity.",
    aiRecommendedActions: ["Generate content brief template for eye care", "Confirm HIPAA content guidelines with content team"],
    aiImplementationPlan: "Generate content blueprint with 4 blog posts/month. Add content tasks to Patient Acquisition project. Update billing.",
    activityTimeline: [
      { date: "2025-07-03", event: "Request Created", actor: "Rachel Torres" },
      { date: "2025-07-03", event: "Review Started", actor: "Rachel Torres" },
    ],
    mrrChange: 1200,
    arrChange: 14400,
    oneTimeFees: 0,
    credits: 0,
    adjustments: 0,
  },

  // ── CR-019: Custom Scope Change ────────────────────────────────────────────
  {
    id: "CR-019",
    client: "Titan Restoration",
    project: "Storm Damage Lead Program",
    requestType: "Custom Scope Change",
    requestedBy: "Sarah Mitchell",
    requestedByRole: "Account Manager",
    assignedAM: "Sarah Mitchell",
    revenueImpact: 3500,
    revenueDirection: "Increase",
    departmentsImpacted: ["Paid Advertising", "LSA", "Content", "Reporting"],
    status: "Pending Approval",
    submittedDate: "2025-07-01",
    description: "Emergency scope expansion following major storm event. Add storm damage PPC, emergency LSA budget increase, and daily reporting for 90 days.",
    clientHealthScore: 88,
    clientHealthStatus: "Healthy",
    renewalRisk: "Low",
    expansionOpportunity: "High",
    clientMRR: 6500,
    clientARR: 78000,
    openEscalations: 0,
    openProjects: 4,
    lastCommunication: "2025-07-01",
    aiClientSummary: "Titan Restoration is responding to a regional storm event. Emergency scope expansion is time-sensitive. Fast-track approval recommended given business opportunity.",
    projectsImpacted: ["Storm Damage Lead Program", "Emergency PPC", "LSA Emergency"],
    tasksAdded: 32,
    tasksRemoved: 0,
    milestonesAffected: 4,
    contractAmendmentRequired: false,
    billingApprovalStatus: "Pending",
    approvalWorkflow: [
      { stage: "Review", assignee: "Sarah Mitchell", status: "Approved", completedDate: "2025-07-01" },
      { stage: "Department Approval", assignee: "PPC Lead", status: "Approved", completedDate: "2025-07-01" },
      { stage: "Billing Approval", assignee: "Billing Team", status: "In Progress" },
      { stage: "Executive Approval", assignee: "VP of Operations", status: "Pending" },
      { stage: "Final Approval", assignee: "Director of AM", status: "Pending" },
    ],
    implementationItems: [
      { area: "Projects Updated", status: "Pending" },
      { area: "Task Blueprints Updated", status: "Pending" },
      { area: "Departments Updated", status: "Pending" },
      { area: "Billing Updated", status: "Pending" },
      { area: "Contract Updated", status: "Not Required" },
    ],
    implementationStatus: "Not Started",
    aiImpactAssessment: "Emergency expansion increases MRR by $3,500 for 90-day window. 32 new tasks. Time-sensitive — delayed approval reduces campaign effectiveness.",
    aiRiskAssessment: "Low risk. Client is healthy. Time-sensitive opportunity. Fast-track recommended.",
    aiRecommendedActions: ["Fast-track billing and executive approval", "Pre-build task blueprints before final approval", "Launch PPC immediately upon approval"],
    aiImplementationPlan: "Pre-build blueprints for storm damage campaigns. Launch PPC and LSA emergency increase on same-day approval. Begin daily reporting immediately.",
    activityTimeline: [
      { date: "2025-07-01", event: "Request Created", actor: "Sarah Mitchell" },
      { date: "2025-07-01", event: "Department Approval", actor: "PPC Lead", note: "Fast-tracked" },
      { date: "2025-07-01", event: "Billing Approval Requested", actor: "System" },
    ],
    mrrChange: 3500,
    arrChange: 0,
    oneTimeFees: 0,
    credits: 0,
    adjustments: 10500,
  },

  // ── CR-020: Service Removal ────────────────────────────────────────────────
  {
    id: "CR-020",
    client: "Valley Chiropractic",
    project: "Patient Growth Program",
    requestType: "Service Removal",
    requestedBy: "James Carter",
    requestedByRole: "Account Manager",
    assignedAM: "James Carter",
    revenueImpact: -600,
    revenueDirection: "Decrease",
    departmentsImpacted: ["Yelp"],
    status: "Submitted",
    submittedDate: "2025-07-03",
    description: "Remove Yelp Ads service. Performance below threshold for 3 months. Client and AM agree to reallocate to LSA instead.",
    clientHealthScore: 76,
    clientHealthStatus: "Healthy",
    renewalRisk: "Low",
    expansionOpportunity: "Medium",
    clientMRR: 2400,
    clientARR: 28800,
    openEscalations: 0,
    openProjects: 2,
    lastCommunication: "2025-07-02",
    aiClientSummary: "Valley Chiropractic has underperforming Yelp Ads. Removing and reallocating to LSA is the right strategic decision. Client is healthy overall.",
    projectsImpacted: ["Patient Growth Program"],
    tasksAdded: 0,
    tasksRemoved: 5,
    milestonesAffected: 1,
    contractAmendmentRequired: false,
    billingApprovalStatus: "Pending",
    serviceRemoved: "Yelp Ads Management",
    removedDeliverables: ["Yelp Ad Management", "Yelp Monthly Report"],
    approvalWorkflow: [
      { stage: "Review", assignee: "James Carter", status: "In Progress" },
      { stage: "Department Approval", assignee: "Yelp Lead", status: "Pending" },
      { stage: "Billing Approval", assignee: "Billing Team", status: "Pending" },
      { stage: "Final Approval", assignee: "Director of AM", status: "Pending" },
    ],
    implementationItems: [
      { area: "Projects Updated", status: "Pending" },
      { area: "Task Blueprints Updated", status: "Pending" },
      { area: "Departments Updated", status: "Pending" },
      { area: "Billing Updated", status: "Pending" },
      { area: "Contract Updated", status: "Not Required" },
    ],
    implementationStatus: "Not Started",
    aiImpactAssessment: "Yelp Ads removal reduces MRR by $600. 5 tasks removed. LSA addition likely to follow — net revenue will be neutral or positive.",
    aiRiskAssessment: "Low risk. Performance-based removal with client agreement.",
    aiRecommendedActions: ["Pair with LSA addition change request", "Confirm Yelp account access transfer to client"],
    aiImplementationPlan: "Remove Yelp tasks from project blueprint. Deactivate Yelp department for this client. Update billing.",
    activityTimeline: [
      { date: "2025-07-03", event: "Request Created", actor: "James Carter" },
      { date: "2025-07-03", event: "Review Started", actor: "James Carter" },
    ],
    mrrChange: -600,
    arrChange: -7200,
    oneTimeFees: 0,
    credits: 0,
    adjustments: 0,
  },
];
