// ─────────────────────────────────────────────────────────────────────────────
// RTM OS — Workflow Engine Mock Data
// Route: /operations/workflows
// ─────────────────────────────────────────────────────────────────────────────

export type WorkflowStatus = "Active" | "Inactive" | "Failed" | "Draft";
export type WorkflowCategory =
  | "Activation"
  | "Project"
  | "Task"
  | "Billing"
  | "Renewal"
  | "Expansion"
  | "Cancellation"
  | "Offboarding"
  | "Escalation"
  | "Notification"
  | "Custom";

export type TriggerType =
  | "Proposal Accepted"
  | "Contract Signed"
  | "Invoice Paid"
  | "Project Created"
  | "Task Overdue"
  | "Project Delayed"
  | "Client Health Changed"
  | "Renewal Window Reached"
  | "Cancellation Requested"
  | "Offboarding Started"
  | "Manual Trigger"
  | "Custom Trigger";

export type ExecutionResult = "Success" | "Failed" | "Partial" | "Skipped";

export interface Workflow {
  id: string;
  name: string;
  category: WorkflowCategory;
  trigger: TriggerType;
  status: WorkflowStatus;
  lastRun: string;
  successRate: number;
  owner: string;
  description: string;
  actionsCount: number;
  runsTotal: number;
  runsSuccess: number;
  createdAt: string;
  tags: string[];
}

export interface ExecutionRecord {
  id: string;
  workflowId: string;
  workflowName: string;
  date: string;
  trigger: TriggerType;
  result: ExecutionResult;
  durationMs: number;
  status: WorkflowStatus;
  errorDetails?: string;
  actionsExecuted: number;
  notificationsSent: number;
  tasksGenerated: number;
  projectsGenerated: number;
}

export interface WorkflowTemplate {
  id: string;
  name: string;
  category: WorkflowCategory;
  description: string;
  steps: string[];
  estimatedDuration: string;
  automationCount: number;
}

export interface AIRecommendation {
  id: string;
  type: "Bottleneck" | "Opportunity" | "Improvement" | "Suggestion";
  title: string;
  description: string;
  impact: "High" | "Medium" | "Low";
  effort: "High" | "Medium" | "Low";
  category: WorkflowCategory;
}

// ── 25 Workflows ──────────────────────────────────────────────────────────────

export const WORKFLOWS: Workflow[] = [
  {
    id: "wf-001",
    name: "Client Activation — Invoice Paid",
    category: "Activation",
    trigger: "Invoice Paid",
    status: "Active",
    lastRun: "2025-07-24 09:14",
    successRate: 97,
    owner: "Operations Team",
    description: "Automatically creates activation project, assigns AM, generates task blueprints, and notifies departments when an invoice is paid.",
    actionsCount: 6,
    runsTotal: 142,
    runsSuccess: 138,
    createdAt: "2025-01-10",
    tags: ["activation", "billing", "project"],
  },
  {
    id: "wf-002",
    name: "Proposal Accepted — Sales Handoff",
    category: "Activation",
    trigger: "Proposal Accepted",
    status: "Active",
    lastRun: "2025-07-24 08:32",
    successRate: 100,
    owner: "Sales Team",
    description: "Triggers contract generation task, notifies billing, and creates a pending activation record when a proposal is accepted.",
    actionsCount: 4,
    runsTotal: 89,
    runsSuccess: 89,
    createdAt: "2025-01-15",
    tags: ["sales", "handoff", "contract"],
  },
  {
    id: "wf-003",
    name: "Renewal — 90-Day Window",
    category: "Renewal",
    trigger: "Renewal Window Reached",
    status: "Active",
    lastRun: "2025-07-23 17:00",
    successRate: 94,
    owner: "Account Management",
    description: "Creates renewal opportunity, notifies AM, and generates a client review packet when renewal window opens at 90 days.",
    actionsCount: 5,
    runsTotal: 67,
    runsSuccess: 63,
    createdAt: "2025-02-01",
    tags: ["renewal", "am", "client-review"],
  },
  {
    id: "wf-004",
    name: "Cancellation — Offboarding Kickoff",
    category: "Cancellation",
    trigger: "Cancellation Requested",
    status: "Active",
    lastRun: "2025-07-23 14:22",
    successRate: 91,
    owner: "Operations Team",
    description: "Creates offboarding project, generates department shutdown tasks, and notifies all assigned departments when cancellation is approved.",
    actionsCount: 7,
    runsTotal: 34,
    runsSuccess: 31,
    createdAt: "2025-02-10",
    tags: ["cancellation", "offboarding", "departments"],
  },
  {
    id: "wf-005",
    name: "Task Overdue — Escalation",
    category: "Escalation",
    trigger: "Task Overdue",
    status: "Active",
    lastRun: "2025-07-24 07:00",
    successRate: 88,
    owner: "Operations Team",
    description: "Automatically escalates overdue tasks to department leads, notifies operations support, and creates an escalation record.",
    actionsCount: 3,
    runsTotal: 218,
    runsSuccess: 192,
    createdAt: "2025-01-20",
    tags: ["escalation", "overdue", "tasks"],
  },
  {
    id: "wf-006",
    name: "Contract Signed — Project Creation",
    category: "Project",
    trigger: "Contract Signed",
    status: "Active",
    lastRun: "2025-07-24 10:05",
    successRate: 99,
    owner: "Operations Team",
    description: "Creates the client project, assigns account manager, generates the initial task blueprint, and assigns departments.",
    actionsCount: 5,
    runsTotal: 104,
    runsSuccess: 103,
    createdAt: "2025-01-12",
    tags: ["project", "contract", "onboarding"],
  },
  {
    id: "wf-007",
    name: "Client Health Drop — Intervention",
    category: "Escalation",
    trigger: "Client Health Changed",
    status: "Active",
    lastRun: "2025-07-24 06:00",
    successRate: 82,
    owner: "Account Management",
    description: "Triggers AM notification, creates a client check-in task, and escalates to department lead when health score drops below threshold.",
    actionsCount: 4,
    runsTotal: 56,
    runsSuccess: 46,
    createdAt: "2025-03-01",
    tags: ["health", "escalation", "am"],
  },
  {
    id: "wf-008",
    name: "Expansion — Upsell Opportunity",
    category: "Expansion",
    trigger: "Client Health Changed",
    status: "Active",
    lastRun: "2025-07-22 15:00",
    successRate: 90,
    owner: "Sales Team",
    description: "Creates an expansion opportunity record, notifies the sales team, and generates an expansion proposal task when client health is high.",
    actionsCount: 4,
    runsTotal: 28,
    runsSuccess: 25,
    createdAt: "2025-03-15",
    tags: ["expansion", "upsell", "sales"],
  },
  {
    id: "wf-009",
    name: "Offboarding — Asset Recovery",
    category: "Offboarding",
    trigger: "Offboarding Started",
    status: "Active",
    lastRun: "2025-07-21 11:00",
    successRate: 95,
    owner: "Operations Team",
    description: "Generates asset recovery tasks, revokes access credentials, archives client records, and sends offboarding summary notification.",
    actionsCount: 6,
    runsTotal: 22,
    runsSuccess: 21,
    createdAt: "2025-02-20",
    tags: ["offboarding", "access", "archive"],
  },
  {
    id: "wf-010",
    name: "Invoice Overdue — Billing Escalation",
    category: "Billing",
    trigger: "Task Overdue",
    status: "Active",
    lastRun: "2025-07-24 08:00",
    successRate: 85,
    owner: "Billing Team",
    description: "Escalates overdue invoices to billing lead, sends automated payment reminder notification, and creates a collections task.",
    actionsCount: 4,
    runsTotal: 78,
    runsSuccess: 66,
    createdAt: "2025-02-05",
    tags: ["billing", "collections", "overdue"],
  },
  {
    id: "wf-011",
    name: "Project Delay — PM Notification",
    category: "Notification",
    trigger: "Project Delayed",
    status: "Active",
    lastRun: "2025-07-23 16:00",
    successRate: 93,
    owner: "Operations Team",
    description: "Notifies the project manager, department leads, and AM when a project milestone is delayed beyond the threshold.",
    actionsCount: 3,
    runsTotal: 45,
    runsSuccess: 42,
    createdAt: "2025-02-15",
    tags: ["project", "delay", "notification"],
  },
  {
    id: "wf-012",
    name: "Renewal Won — Expansion Workflow",
    category: "Renewal",
    trigger: "Contract Signed",
    status: "Active",
    lastRun: "2025-07-20 09:00",
    successRate: 98,
    owner: "Account Management",
    description: "When a renewal contract is signed, updates service records, resets billing cycle, reassigns AM if needed, and notifies departments.",
    actionsCount: 5,
    runsTotal: 41,
    runsSuccess: 40,
    createdAt: "2025-03-10",
    tags: ["renewal", "contract", "billing"],
  },
  {
    id: "wf-013",
    name: "New Project — Task Blueprint Generator",
    category: "Task",
    trigger: "Project Created",
    status: "Active",
    lastRun: "2025-07-24 11:20",
    successRate: 96,
    owner: "Operations Team",
    description: "Automatically generates task blueprints for all assigned departments when a new project is created.",
    actionsCount: 4,
    runsTotal: 96,
    runsSuccess: 92,
    createdAt: "2025-01-25",
    tags: ["tasks", "blueprint", "project"],
  },
  {
    id: "wf-014",
    name: "Cancellation Approved — Revenue Recovery",
    category: "Cancellation",
    trigger: "Cancellation Requested",
    status: "Inactive",
    lastRun: "2025-07-15 10:00",
    successRate: 72,
    owner: "Sales Team",
    description: "Attempts a save by triggering a retention offer, notifying the AM, and creating a save opportunity before processing cancellation.",
    actionsCount: 3,
    runsTotal: 18,
    runsSuccess: 13,
    createdAt: "2025-04-01",
    tags: ["cancellation", "retention", "revenue"],
  },
  {
    id: "wf-015",
    name: "Weekly Report — Auto Generation",
    category: "Notification",
    trigger: "Manual Trigger",
    status: "Active",
    lastRun: "2025-07-21 06:00",
    successRate: 100,
    owner: "Reporting Team",
    description: "Generates weekly performance reports for all active clients and distributes them to account managers every Monday.",
    actionsCount: 3,
    runsTotal: 24,
    runsSuccess: 24,
    createdAt: "2025-02-03",
    tags: ["reporting", "automation", "weekly"],
  },
  {
    id: "wf-016",
    name: "Department Assignment — Activation",
    category: "Activation",
    trigger: "Invoice Paid",
    status: "Active",
    lastRun: "2025-07-24 09:30",
    successRate: 94,
    owner: "Operations Team",
    description: "Assigns departments to the activation project based on the client's service package and sends department kickoff notifications.",
    actionsCount: 5,
    runsTotal: 142,
    runsSuccess: 133,
    createdAt: "2025-01-18",
    tags: ["activation", "departments", "assignment"],
  },
  {
    id: "wf-017",
    name: "Billing Follow-Up — 7-Day Reminder",
    category: "Billing",
    trigger: "Task Overdue",
    status: "Active",
    lastRun: "2025-07-24 07:30",
    successRate: 89,
    owner: "Billing Team",
    description: "Sends automated payment reminders at 7, 14, and 30-day intervals for outstanding invoices.",
    actionsCount: 3,
    runsTotal: 156,
    runsSuccess: 139,
    createdAt: "2025-01-28",
    tags: ["billing", "reminder", "payment"],
  },
  {
    id: "wf-018",
    name: "Custom — VIP Client Fast Track",
    category: "Custom",
    trigger: "Proposal Accepted",
    status: "Active",
    lastRun: "2025-07-23 13:00",
    successRate: 100,
    owner: "Operations Team",
    description: "Fast-tracks VIP clients through activation with executive notification, priority task assignment, and expedited department setup.",
    actionsCount: 7,
    runsTotal: 9,
    runsSuccess: 9,
    createdAt: "2025-04-15",
    tags: ["vip", "custom", "priority"],
  },
  {
    id: "wf-019",
    name: "Task Overdue — Department Escalation",
    category: "Escalation",
    trigger: "Task Overdue",
    status: "Active",
    lastRun: "2025-07-24 07:00",
    successRate: 87,
    owner: "Operations Team",
    description: "Escalates department-level overdue tasks to department leads and sends a daily summary to operations support.",
    actionsCount: 4,
    runsTotal: 312,
    runsSuccess: 271,
    createdAt: "2025-01-22",
    tags: ["escalation", "department", "tasks"],
  },
  {
    id: "wf-020",
    name: "Offboarding — Final Invoice",
    category: "Offboarding",
    trigger: "Offboarding Started",
    status: "Active",
    lastRun: "2025-07-18 09:00",
    successRate: 100,
    owner: "Billing Team",
    description: "Generates the final prorated invoice, sends it to the client, and creates a billing closeout task during offboarding.",
    actionsCount: 3,
    runsTotal: 22,
    runsSuccess: 22,
    createdAt: "2025-02-22",
    tags: ["offboarding", "billing", "invoice"],
  },
  {
    id: "wf-021",
    name: "Renewal Lost — Cancellation Trigger",
    category: "Renewal",
    trigger: "Renewal Window Reached",
    status: "Inactive",
    lastRun: "2025-07-10 10:00",
    successRate: 68,
    owner: "Account Management",
    description: "When a renewal window passes without action, triggers a cancellation risk alert and creates a save opportunity task.",
    actionsCount: 3,
    runsTotal: 14,
    runsSuccess: 10,
    createdAt: "2025-04-20",
    tags: ["renewal", "cancellation", "risk"],
  },
  {
    id: "wf-022",
    name: "Expansion — Cross-Sell Notification",
    category: "Expansion",
    trigger: "Client Health Changed",
    status: "Active",
    lastRun: "2025-07-24 08:45",
    successRate: 91,
    owner: "Sales Team",
    description: "Notifies the sales team of cross-sell opportunities when a client's health score reaches a high threshold.",
    actionsCount: 3,
    runsTotal: 33,
    runsSuccess: 30,
    createdAt: "2025-03-20",
    tags: ["expansion", "cross-sell", "sales"],
  },
  {
    id: "wf-023",
    name: "Multi-Step Approval — Change Request",
    category: "Custom",
    trigger: "Custom Trigger",
    status: "Active",
    lastRun: "2025-07-23 15:30",
    successRate: 95,
    owner: "Operations Team",
    description: "Routes change requests through department approval, AM approval, and executive approval with automatic escalation on inaction.",
    actionsCount: 8,
    runsTotal: 47,
    runsSuccess: 45,
    createdAt: "2025-03-05",
    tags: ["approval", "change-request", "multi-step"],
  },
  {
    id: "wf-024",
    name: "Project Complete — Client Notification",
    category: "Notification",
    trigger: "Project Created",
    status: "Active",
    lastRun: "2025-07-24 10:00",
    successRate: 100,
    owner: "Account Management",
    description: "Sends a project completion notification to the client and AM, generates a completion report, and creates a follow-up check-in task.",
    actionsCount: 4,
    runsTotal: 61,
    runsSuccess: 61,
    createdAt: "2025-02-28",
    tags: ["project", "completion", "notification"],
  },
  {
    id: "wf-025",
    name: "Billing — Collections Escalation",
    category: "Billing",
    trigger: "Task Overdue",
    status: "Failed",
    lastRun: "2025-07-24 06:00",
    successRate: 64,
    owner: "Billing Team",
    description: "Escalates 30-day+ overdue invoices to the collections team and sends a formal demand notice to the client.",
    actionsCount: 4,
    runsTotal: 28,
    runsSuccess: 18,
    createdAt: "2025-03-25",
    tags: ["billing", "collections", "30-day"],
  },
];

// ── Execution History ─────────────────────────────────────────────────────────

export const EXECUTION_HISTORY: ExecutionRecord[] = [
  {
    id: "ex-001",
    workflowId: "wf-001",
    workflowName: "Client Activation — Invoice Paid",
    date: "2025-07-24 09:14",
    trigger: "Invoice Paid",
    result: "Success",
    durationMs: 1240,
    status: "Active",
    actionsExecuted: 6,
    notificationsSent: 3,
    tasksGenerated: 12,
    projectsGenerated: 1,
  },
  {
    id: "ex-002",
    workflowId: "wf-005",
    workflowName: "Task Overdue — Escalation",
    date: "2025-07-24 07:00",
    trigger: "Task Overdue",
    result: "Success",
    durationMs: 540,
    status: "Active",
    actionsExecuted: 3,
    notificationsSent: 2,
    tasksGenerated: 1,
    projectsGenerated: 0,
  },
  {
    id: "ex-003",
    workflowId: "wf-025",
    workflowName: "Billing — Collections Escalation",
    date: "2025-07-24 06:00",
    trigger: "Task Overdue",
    result: "Failed",
    durationMs: 820,
    status: "Failed",
    errorDetails: "Webhook delivery failed: collections-api timeout after 30s",
    actionsExecuted: 2,
    notificationsSent: 0,
    tasksGenerated: 0,
    projectsGenerated: 0,
  },
  {
    id: "ex-004",
    workflowId: "wf-006",
    workflowName: "Contract Signed — Project Creation",
    date: "2025-07-24 10:05",
    trigger: "Contract Signed",
    result: "Success",
    durationMs: 1890,
    status: "Active",
    actionsExecuted: 5,
    notificationsSent: 4,
    tasksGenerated: 8,
    projectsGenerated: 1,
  },
  {
    id: "ex-005",
    workflowId: "wf-013",
    workflowName: "New Project — Task Blueprint Generator",
    date: "2025-07-24 11:20",
    trigger: "Project Created",
    result: "Success",
    durationMs: 670,
    status: "Active",
    actionsExecuted: 4,
    notificationsSent: 2,
    tasksGenerated: 18,
    projectsGenerated: 0,
  },
  {
    id: "ex-006",
    workflowId: "wf-010",
    workflowName: "Invoice Overdue — Billing Escalation",
    date: "2025-07-24 08:00",
    trigger: "Task Overdue",
    result: "Partial",
    durationMs: 1120,
    status: "Active",
    errorDetails: "Email delivery skipped: missing client contact email",
    actionsExecuted: 3,
    notificationsSent: 1,
    tasksGenerated: 1,
    projectsGenerated: 0,
  },
  {
    id: "ex-007",
    workflowId: "wf-003",
    workflowName: "Renewal — 90-Day Window",
    date: "2025-07-23 17:00",
    trigger: "Renewal Window Reached",
    result: "Success",
    durationMs: 980,
    status: "Active",
    actionsExecuted: 5,
    notificationsSent: 3,
    tasksGenerated: 4,
    projectsGenerated: 0,
  },
  {
    id: "ex-008",
    workflowId: "wf-004",
    workflowName: "Cancellation — Offboarding Kickoff",
    date: "2025-07-23 14:22",
    trigger: "Cancellation Requested",
    result: "Success",
    durationMs: 2340,
    status: "Active",
    actionsExecuted: 7,
    notificationsSent: 5,
    tasksGenerated: 14,
    projectsGenerated: 1,
  },
  {
    id: "ex-009",
    workflowId: "wf-007",
    workflowName: "Client Health Drop — Intervention",
    date: "2025-07-24 06:00",
    trigger: "Client Health Changed",
    result: "Success",
    durationMs: 760,
    status: "Active",
    actionsExecuted: 4,
    notificationsSent: 2,
    tasksGenerated: 2,
    projectsGenerated: 0,
  },
  {
    id: "ex-010",
    workflowId: "wf-002",
    workflowName: "Proposal Accepted — Sales Handoff",
    date: "2025-07-24 08:32",
    trigger: "Proposal Accepted",
    result: "Success",
    durationMs: 430,
    status: "Active",
    actionsExecuted: 4,
    notificationsSent: 3,
    tasksGenerated: 3,
    projectsGenerated: 0,
  },
  {
    id: "ex-011",
    workflowId: "wf-019",
    workflowName: "Task Overdue — Department Escalation",
    date: "2025-07-24 07:00",
    trigger: "Task Overdue",
    result: "Success",
    durationMs: 590,
    status: "Active",
    actionsExecuted: 4,
    notificationsSent: 4,
    tasksGenerated: 0,
    projectsGenerated: 0,
  },
  {
    id: "ex-012",
    workflowId: "wf-011",
    workflowName: "Project Delay — PM Notification",
    date: "2025-07-23 16:00",
    trigger: "Project Delayed",
    result: "Success",
    durationMs: 310,
    status: "Active",
    actionsExecuted: 3,
    notificationsSent: 3,
    tasksGenerated: 1,
    projectsGenerated: 0,
  },
  {
    id: "ex-013",
    workflowId: "wf-023",
    workflowName: "Multi-Step Approval — Change Request",
    date: "2025-07-23 15:30",
    trigger: "Custom Trigger",
    result: "Success",
    durationMs: 4200,
    status: "Active",
    actionsExecuted: 8,
    notificationsSent: 6,
    tasksGenerated: 2,
    projectsGenerated: 0,
  },
  {
    id: "ex-014",
    workflowId: "wf-016",
    workflowName: "Department Assignment — Activation",
    date: "2025-07-24 09:30",
    trigger: "Invoice Paid",
    result: "Success",
    durationMs: 1580,
    status: "Active",
    actionsExecuted: 5,
    notificationsSent: 4,
    tasksGenerated: 6,
    projectsGenerated: 0,
  },
  {
    id: "ex-015",
    workflowId: "wf-017",
    workflowName: "Billing Follow-Up — 7-Day Reminder",
    date: "2025-07-24 07:30",
    trigger: "Task Overdue",
    result: "Success",
    durationMs: 280,
    status: "Active",
    actionsExecuted: 3,
    notificationsSent: 2,
    tasksGenerated: 0,
    projectsGenerated: 0,
  },
];

// ── Workflow Templates ────────────────────────────────────────────────────────

export const WORKFLOW_TEMPLATES: WorkflowTemplate[] = [
  {
    id: "tpl-001",
    name: "Client Activation",
    category: "Activation",
    description: "Full client activation workflow from invoice payment through department onboarding.",
    steps: [
      "Invoice Paid",
      "Create Activation Project",
      "Assign Account Manager",
      "Generate Task Blueprints",
      "Assign Departments",
      "Notify Teams",
    ],
    estimatedDuration: "2-4 hours",
    automationCount: 6,
  },
  {
    id: "tpl-002",
    name: "Project Launch",
    category: "Project",
    description: "Triggers project creation, assigns resources, and generates department-specific task lists.",
    steps: [
      "Contract Signed",
      "Create Project",
      "Assign AM",
      "Generate Tasks by Department",
      "Notify Department Leads",
    ],
    estimatedDuration: "1-2 hours",
    automationCount: 5,
  },
  {
    id: "tpl-003",
    name: "Renewal Workflow",
    category: "Renewal",
    description: "90-day renewal window automation with AM notification and client review generation.",
    steps: [
      "90 Days Before Renewal",
      "Create Renewal Opportunity",
      "Notify AM",
      "Generate Client Review",
      "60-Day Follow-Up",
      "30-Day Final Notice",
    ],
    estimatedDuration: "3 months (automated)",
    automationCount: 6,
  },
  {
    id: "tpl-004",
    name: "Expansion Workflow",
    category: "Expansion",
    description: "Identifies and acts on upsell and cross-sell opportunities based on client health.",
    steps: [
      "Health Score Threshold Met",
      "Create Expansion Opportunity",
      "Notify Sales Team",
      "Generate Expansion Proposal",
      "Schedule Sales Call Task",
    ],
    estimatedDuration: "1 hour",
    automationCount: 5,
  },
  {
    id: "tpl-005",
    name: "Cancellation Workflow",
    category: "Cancellation",
    description: "Manages the full cancellation process from request through offboarding initiation.",
    steps: [
      "Cancellation Approved",
      "Create Offboarding Project",
      "Generate Offboarding Tasks",
      "Notify Departments",
      "Schedule Final Invoice",
    ],
    estimatedDuration: "2-3 hours",
    automationCount: 5,
  },
  {
    id: "tpl-006",
    name: "Offboarding Workflow",
    category: "Offboarding",
    description: "Handles all offboarding steps including asset recovery, access revocation, and archiving.",
    steps: [
      "Offboarding Started",
      "Revoke Access",
      "Recover Assets",
      "Generate Final Invoice",
      "Archive Client Records",
      "Send Offboarding Summary",
    ],
    estimatedDuration: "3-5 days",
    automationCount: 6,
  },
  {
    id: "tpl-007",
    name: "Task Escalation",
    category: "Escalation",
    description: "Automatically escalates overdue tasks through department leads to executive team.",
    steps: [
      "Task Overdue",
      "Notify Assigned User",
      "Escalate to Department Lead",
      "Create Escalation Record",
      "Escalate to Ops Support if Unresolved",
    ],
    estimatedDuration: "24-48 hours",
    automationCount: 5,
  },
  {
    id: "tpl-008",
    name: "Billing Follow-Up",
    category: "Billing",
    description: "Multi-touch billing follow-up sequence for outstanding invoices.",
    steps: [
      "Invoice Due",
      "7-Day Reminder",
      "14-Day Follow-Up",
      "30-Day Escalation to Collections",
      "Final Notice",
    ],
    estimatedDuration: "30 days (automated)",
    automationCount: 5,
  },
];

// ── AI Recommendations ────────────────────────────────────────────────────────

export const AI_RECOMMENDATIONS: AIRecommendation[] = [
  {
    id: "ai-001",
    type: "Bottleneck",
    title: "Collections escalation workflow has 36% failure rate",
    description: "The Billing — Collections Escalation workflow is failing on webhook delivery to the collections API. Recommend switching to email delivery as a fallback and adding retry logic with exponential backoff.",
    impact: "High",
    effort: "Low",
    category: "Billing",
  },
  {
    id: "ai-002",
    type: "Opportunity",
    title: "Automate department task generation at contract signing",
    description: "Analysis shows 87% of projects still require manual department task assignment after contract signing. Automating this step could save 3-4 hours per activation.",
    impact: "High",
    effort: "Medium",
    category: "Activation",
  },
  {
    id: "ai-003",
    type: "Improvement",
    title: "Add approval gate to expansion workflow",
    description: "Expansion opportunities are being created without AM approval, leading to premature outreach. Adding an AM approval step before sales notification would improve conversion accuracy.",
    impact: "Medium",
    effort: "Low",
    category: "Expansion",
  },
  {
    id: "ai-004",
    type: "Suggestion",
    title: "Create a 30-day check-in workflow for new activations",
    description: "No automated check-in exists for clients 30 days post-activation. A check-in workflow could improve early churn detection and client satisfaction scores.",
    impact: "High",
    effort: "Medium",
    category: "Activation",
  },
  {
    id: "ai-005",
    type: "Bottleneck",
    title: "Renewal Lost workflow has low success rate (68%)",
    description: "The Renewal Lost workflow is currently inactive and had a 68% success rate. Root cause appears to be missing contact data on 32% of clients. Recommend a pre-check condition before triggering.",
    impact: "Medium",
    effort: "Low",
    category: "Renewal",
  },
  {
    id: "ai-006",
    type: "Opportunity",
    title: "Automate weekly health score review for at-risk clients",
    description: "Only reactive health monitoring exists. A proactive weekly health review workflow could identify at-risk clients 2-3 weeks earlier and reduce churn by an estimated 15%.",
    impact: "High",
    effort: "High",
    category: "Escalation",
  },
];

// ── Dashboard KPIs ────────────────────────────────────────────────────────────

export const WORKFLOW_KPIS = {
  activeWorkflows:    WORKFLOWS.filter((w) => w.status === "Active").length,
  inactiveWorkflows:  WORKFLOWS.filter((w) => w.status === "Inactive").length,
  failedAutomations:  WORKFLOWS.filter((w) => w.status === "Failed").length,
  pendingActions:     14,
  tasksGenerated:     EXECUTION_HISTORY.reduce((s, r) => s + r.tasksGenerated, 0),
  projectsGenerated:  EXECUTION_HISTORY.reduce((s, r) => s + r.projectsGenerated, 0),
  notificationsSent:  EXECUTION_HISTORY.reduce((s, r) => s + r.notificationsSent, 0),
  totalRuns:          WORKFLOWS.reduce((s, w) => s + w.runsTotal, 0),
  avgSuccessRate:
    Math.round(
      WORKFLOWS.filter((w) => w.runsTotal > 0).reduce((s, w) => s + w.successRate, 0) /
        WORKFLOWS.filter((w) => w.runsTotal > 0).length
    ),
};
