import type {
  Client,
  Deliverable,
  Escalation,
  Blocker,
  OnboardingItem,
} from "./types";

// ─── Mock Clients ─────────────────────────────────────────────────────────────

export const mockClients: Client[] = [
  {
    id: "c001",
    name: "Coastal Plumbing Co.",
    industry: "Home Services",
    services: ["SEO", "Meta Ads", "GBP", "LSA"],
    healthScore: "Healthy",
    assignedAM: "Sarah Chen",
    campaignStatus: "Active",
    startDate: "2023-03-15",
    renewalDate: "2025-03-15",
    monthlyRevenue: 4500,
    lastContact: "2025-05-28",
    location: "Miami, FL",
    reportsOverdue: 0,
    openDeliverables: 2,
    aiNotes: "Client is satisfied with Q1 results. Exploring upsell for PPC.",
  },
  {
    id: "c002",
    name: "Peak Performance HVAC",
    industry: "HVAC",
    services: ["Meta Ads", "PPC", "Reporting"],
    healthScore: "At-Risk",
    assignedAM: "James Rivera",
    campaignStatus: "Active",
    startDate: "2022-09-01",
    renewalDate: "2025-09-01",
    monthlyRevenue: 6200,
    lastContact: "2025-05-10",
    location: "Phoenix, AZ",
    reportsOverdue: 2,
    openDeliverables: 5,
    aiNotes: "Missed two monthly calls. Follow up ASAP before renewal window.",
  },
  {
    id: "c003",
    name: "Luxe Dental Spa",
    industry: "Healthcare / Dental",
    services: ["SEO", "Content", "Design", "Reviews"],
    healthScore: "Healthy",
    assignedAM: "Sarah Chen",
    campaignStatus: "Active",
    startDate: "2024-01-10",
    renewalDate: "2026-01-10",
    monthlyRevenue: 3800,
    lastContact: "2025-06-01",
    location: "Beverly Hills, CA",
    reportsOverdue: 0,
    openDeliverables: 1,
    aiNotes: "Very engaged. Requested case study for new Invisalign campaign.",
  },
  {
    id: "c004",
    name: "Summit Roofing Group",
    industry: "Construction / Roofing",
    services: ["LSA", "PPC", "GBP"],
    healthScore: "Critical",
    assignedAM: "Maria Santos",
    campaignStatus: "Paused",
    startDate: "2023-06-01",
    renewalDate: "2025-08-01",
    monthlyRevenue: 5100,
    lastContact: "2025-04-22",
    location: "Dallas, TX",
    reportsOverdue: 3,
    openDeliverables: 8,
    aiNotes: "Client threatened to cancel. Budget dispute unresolved.",
  },
  {
    id: "c005",
    name: "GreenLeaf Landscaping",
    industry: "Landscaping",
    services: ["SEO", "Content", "GBP"],
    healthScore: "Needs Attention",
    assignedAM: "James Rivera",
    campaignStatus: "Active",
    startDate: "2024-04-01",
    renewalDate: "2025-10-01",
    monthlyRevenue: 2900,
    lastContact: "2025-05-20",
    location: "Denver, CO",
    reportsOverdue: 1,
    openDeliverables: 3,
    aiNotes: "Slower results in spring. Client asking about seasonal content.",
  },
  {
    id: "c006",
    name: "Urban Fitness Studio",
    industry: "Fitness / Wellness",
    services: ["Meta Ads", "Design", "Reporting"],
    healthScore: "Healthy",
    assignedAM: "Maria Santos",
    campaignStatus: "Active",
    startDate: "2023-11-01",
    renewalDate: "2025-11-01",
    monthlyRevenue: 3200,
    lastContact: "2025-06-02",
    location: "Austin, TX",
    reportsOverdue: 0,
    openDeliverables: 2,
    aiNotes: "Strong ROAS on summer promo. Ready for renewal conversation.",
  },
  {
    id: "c007",
    name: "Bright Minds Tutoring",
    industry: "Education",
    services: ["SEO", "PPC", "Content"],
    healthScore: "Needs Attention",
    assignedAM: "Sarah Chen",
    campaignStatus: "Active",
    startDate: "2024-02-15",
    renewalDate: "2025-08-15",
    monthlyRevenue: 2200,
    lastContact: "2025-05-15",
    location: "Chicago, IL",
    reportsOverdue: 1,
    openDeliverables: 4,
    aiNotes: "Content deliverable delayed 2 weeks. Client notified.",
  },
  {
    id: "c008",
    name: "Harbor View Realty",
    industry: "Real Estate",
    services: ["SEO", "Meta Ads", "Design", "Content"],
    healthScore: "At-Risk",
    assignedAM: "James Rivera",
    campaignStatus: "Active",
    startDate: "2023-07-01",
    renewalDate: "2025-07-01",
    monthlyRevenue: 7500,
    lastContact: "2025-04-30",
    location: "Seattle, WA",
    reportsOverdue: 2,
    openDeliverables: 6,
    aiNotes: "Unhappy with lead quality. Need strategy call this week.",
  },
  {
    id: "c009",
    name: "Precision Auto Repair",
    industry: "Automotive",
    services: ["GBP", "SEO", "Reviews"],
    healthScore: "Healthy",
    assignedAM: "Maria Santos",
    campaignStatus: "Active",
    startDate: "2024-06-01",
    renewalDate: "2026-06-01",
    monthlyRevenue: 1800,
    lastContact: "2025-06-01",
    location: "Nashville, TN",
    reportsOverdue: 0,
    openDeliverables: 1,
    aiNotes: "New client, onboarding complete. First report due next month.",
  },
  {
    id: "c010",
    name: "CloudPath Tech Solutions",
    industry: "Technology / SaaS",
    services: ["SEO", "Content", "PPC", "Reporting"],
    healthScore: "Healthy",
    assignedAM: "Sarah Chen",
    campaignStatus: "Active",
    startDate: "2023-01-01",
    renewalDate: "2025-12-31",
    monthlyRevenue: 9800,
    lastContact: "2025-06-03",
    location: "San Francisco, CA",
    reportsOverdue: 0,
    openDeliverables: 3,
    aiNotes: "Flagship client. Q2 review scheduled. Expand to LinkedIn Ads?",
  },
];

// ─── Mock Deliverables ────────────────────────────────────────────────────────

export const mockDeliverables: Deliverable[] = [
  {
    id: "d001",
    clientId: "c001",
    clientName: "Coastal Plumbing Co.",
    title: "Monthly SEO Report - June",
    service: "SEO",
    assignedTo: "Alex Kim",
    dueDate: "2025-06-10",
    status: "In Progress",
    priority: "High",
    description: "Full monthly ranking + traffic report with insights.",
  },
  {
    id: "d002",
    clientId: "c002",
    clientName: "Peak Performance HVAC",
    title: "Meta Ads Creative Refresh",
    service: "Meta Ads",
    assignedTo: "Tom Bell",
    dueDate: "2025-06-01",
    status: "Overdue",
    priority: "Critical",
    description: "3 new ad creatives for summer HVAC promo.",
  },
  {
    id: "d003",
    clientId: "c004",
    clientName: "Summit Roofing Group",
    title: "Q2 PPC Strategy Document",
    service: "PPC",
    assignedTo: "Maria Santos",
    dueDate: "2025-05-25",
    status: "Overdue",
    priority: "Critical",
    description: "Revised strategy after budget reduction.",
  },
  {
    id: "d004",
    clientId: "c003",
    clientName: "Luxe Dental Spa",
    title: "Blog Post: Invisalign Benefits",
    service: "Content",
    assignedTo: "Dana Wong",
    dueDate: "2025-06-15",
    status: "In Progress",
    priority: "Medium",
    description: "1200-word SEO blog targeting Invisalign keywords.",
  },
  {
    id: "d005",
    clientId: "c007",
    clientName: "Bright Minds Tutoring",
    title: "Landing Page Design",
    service: "Design",
    assignedTo: "Tom Bell",
    dueDate: "2025-06-08",
    status: "Blocked",
    priority: "High",
    description: "Summer enrollment LP. Blocked on brand assets from client.",
  },
  {
    id: "d006",
    clientId: "c008",
    clientName: "Harbor View Realty",
    title: "Lead Quality Audit Report",
    service: "Reporting",
    assignedTo: "James Rivera",
    dueDate: "2025-06-05",
    status: "Not Started",
    priority: "Critical",
    description: "Detailed breakdown of lead sources + conversion analysis.",
  },
  {
    id: "d007",
    clientId: "c005",
    clientName: "GreenLeaf Landscaping",
    title: "Content Calendar - Q3",
    service: "Content",
    assignedTo: "Dana Wong",
    dueDate: "2025-06-20",
    status: "In Progress",
    priority: "Medium",
    description: "Summer & fall seasonal content plan with 8 posts.",
  },
  {
    id: "d008",
    clientId: "c010",
    clientName: "CloudPath Tech Solutions",
    title: "Q2 Executive Report",
    service: "Reporting",
    assignedTo: "Sarah Chen",
    dueDate: "2025-06-30",
    status: "Not Started",
    priority: "High",
    description: "Full Q2 performance report with recommendations.",
  },
];

// ─── Mock Escalations ─────────────────────────────────────────────────────────

export const mockEscalations: Escalation[] = [
  {
    id: "e001",
    clientId: "c004",
    clientName: "Summit Roofing Group",
    issue: "Client threatening cancellation over poor lead volume",
    raisedBy: "Maria Santos",
    assignedAM: "Maria Santos",
    dateRaised: "2025-05-20",
    status: "Open",
    priority: "Critical",
    notes: "Director intervention needed. Schedule exec call this week.",
  },
  {
    id: "e002",
    clientId: "c002",
    clientName: "Peak Performance HVAC",
    issue: "Missed monthly reporting for 2 consecutive months",
    raisedBy: "James Rivera",
    assignedAM: "James Rivera",
    dateRaised: "2025-05-28",
    status: "In Progress",
    priority: "High",
    notes: "Reports being prepared. Client notified of delay.",
  },
  {
    id: "e003",
    clientId: "c008",
    clientName: "Harbor View Realty",
    issue: "Lead quality complaints — client requesting refund",
    raisedBy: "James Rivera",
    assignedAM: "James Rivera",
    dateRaised: "2025-05-15",
    status: "Escalated",
    priority: "Critical",
    notes: "Elevated to VP of Operations. Strategy session on 6/5.",
  },
  {
    id: "e004",
    clientId: "c007",
    clientName: "Bright Minds Tutoring",
    issue: "Content deliverables 2 weeks behind schedule",
    raisedBy: "Sarah Chen",
    assignedAM: "Sarah Chen",
    dateRaised: "2025-06-01",
    status: "In Progress",
    priority: "Medium",
    notes: "New content writer assigned. ETA June 10.",
  },
];

// ─── Mock Blockers ────────────────────────────────────────────────────────────

export const mockBlockers: Blocker[] = [
  {
    id: "b001",
    clientId: "c007",
    clientName: "Bright Minds Tutoring",
    title: "Missing brand assets for landing page design",
    blockedBy: "Client",
    assignedAM: "Sarah Chen",
    dateCreated: "2025-05-25",
    status: "Awaiting Client",
    impact: "Landing page cannot be built without logo and brand guidelines.",
  },
  {
    id: "b002",
    clientId: "c004",
    clientName: "Summit Roofing Group",
    title: "Budget not confirmed for Q3 PPC",
    blockedBy: "Client",
    assignedAM: "Maria Santos",
    dateCreated: "2025-05-10",
    status: "Open",
    impact: "Campaigns paused. Revenue loss risk if not resolved by 6/15.",
  },
  {
    id: "b003",
    clientId: "c002",
    clientName: "Peak Performance HVAC",
    title: "Ad account access revoked — internal billing dispute",
    blockedBy: "Internal",
    assignedAM: "James Rivera",
    dateCreated: "2025-05-18",
    status: "In Review",
    impact: "No creative can be deployed until resolved. Campaigns stalled.",
  },
  {
    id: "b004",
    clientId: "c008",
    clientName: "Harbor View Realty",
    title: "CRM integration stalled — API key not provided",
    blockedBy: "Client",
    assignedAM: "James Rivera",
    dateCreated: "2025-06-01",
    status: "Awaiting Client",
    impact: "Lead tracking reports cannot be generated without CRM data.",
  },
];

// ─── Mock Onboarding Items ────────────────────────────────────────────────────

export const mockOnboarding: OnboardingItem[] = [
  {
    id: "o001",
    clientId: "c009",
    clientName: "Precision Auto Repair",
    assignedAM: "Maria Santos",
    startDate: "2025-05-15",
    targetCompletionDate: "2025-06-15",
    status: "In Progress",
    completedSteps: 5,
    totalSteps: 8,
    pendingItems: ["Website audit review", "GBP listing verification", "Review generation setup"],
    services: ["GBP", "SEO", "Reviews"],
  },
  {
    id: "o002",
    clientId: "c011",
    clientName: "Blue Sky Solar Panels",
    assignedAM: "Sarah Chen",
    startDate: "2025-06-01",
    targetCompletionDate: "2025-07-01",
    status: "Awaiting Assets",
    completedSteps: 2,
    totalSteps: 10,
    pendingItems: ["Brand kit", "Business details form", "Ad account access", "Website credentials"],
    services: ["SEO", "Meta Ads", "Content", "Design"],
  },
  {
    id: "o003",
    clientId: "c012",
    clientName: "Metro Electrical Services",
    assignedAM: "James Rivera",
    startDate: "2025-05-20",
    targetCompletionDate: "2025-06-20",
    status: "Stalled",
    completedSteps: 3,
    totalSteps: 9,
    pendingItems: ["Client not responding for 2 weeks", "Contract signed but assets missing"],
    services: ["PPC", "LSA", "GBP"],
  },
  {
    id: "o004",
    clientId: "c013",
    clientName: "Elite Pet Grooming",
    assignedAM: "Maria Santos",
    startDate: "2025-06-03",
    targetCompletionDate: "2025-07-03",
    status: "Not Started",
    completedSteps: 0,
    totalSteps: 7,
    pendingItems: ["Welcome call not scheduled"],
    services: ["GBP", "SEO", "Reviews"],
  },
];

// ─── KPI Computations ─────────────────────────────────────────────────────────

export function computeKPIs(clients: Client[], deliverables: Deliverable[]) {
  const totalActiveClients = clients.length;
  const atRiskClients = clients.filter(
    (c) => c.healthScore === "At-Risk"|| c.healthScore === "Critical").length;
  const reportsDue = deliverables.filter(
    (d) => d.status === "Overdue"|| d.title.toLowerCase().includes("report")
  ).length;
  const openDeliverables = deliverables.filter(
    (d) => d.status === "In Progress"|| d.status === "Not Started"|| d.status === "Blocked").length;

  const now = new Date();
  const thirtyDaysOut = new Date(now.getFullYear(), now.getMonth() + 1, now.getDate());
  const renewalsThisMonth = clients.filter((c) => {
    const renewal = new Date(c.renewalDate);
    return renewal >= now && renewal <= thirtyDaysOut;
  }).length;

  return {
    totalActiveClients,
    atRiskClients,
    reportsDue,
    openDeliverables,
    renewalsThisMonth,
  };
}
