// ─── RTM OS — Renewals Engine Mock Data ──────────────────────────────────────
// Signals from: Client Health, Communications, Call Intelligence,
//               Reporting, Billing, Projects, Change Requests

// ══════════════════════════════════════════════════════════════════════════════
// TYPES
// ══════════════════════════════════════════════════════════════════════════════

export type RenewalStatus =
  | "Not Started"| "Planning"| "Review Scheduled"| "Proposal In Progress"| "Negotiation"| "Pending Signature"| "Renewed"| "Lost"| "Cancelled";

export type RenewalRisk = "Low Risk"| "Moderate Risk"| "High Risk"| "Critical";

export type RenewalStrategy =
  | "Renew As-Is"| "Renew With Upgrade"| "Renew With Budget Adjustment"| "Renew With Service Changes"| "Retention Plan Required"| "Executive Intervention Required";

export type TimelineMilestone =
  | "90 Days Before"| "60 Days Before"| "30 Days Before"| "Proposal Sent"| "Negotiation"| "Contract Signed"| "Renewal Completed";

// ── Score Model ───────────────────────────────────────────────────────────────

export interface RenewalScoreBreakdown {
  clientHealth: number;        // 0-100, weight 25%
  projectHealth: number;       // 0-100, weight 20%
  communicationHealth: number; // 0-100, weight 20%
  billingHealth: number;       // 0-100, weight 15%
  callIntelligence: number;    // 0-100, weight 10%
  reportingHealth: number;     // 0-100, weight 5%
  clientEngagement: number;    // 0-100, weight 5%
  overall: number;             // 0-100 computed
}

// ── Client Renewal Profile ────────────────────────────────────────────────────

export interface RenewalRecord {
  id: string;
  client: string;
  accountManager: string;
  contract: string;
  mrr: number;
  arr: number;
  renewalDate: string;
  daysUntilRenewal: number;
  status: RenewalStatus;
  risk: RenewalRisk;
  strategy: RenewalStrategy;
  score: RenewalScoreBreakdown;

  // Client profile
  services: string[];
  industry: string;
  clientSince: string;
  renewalHistory: number; // number of previous renewals
  openIssues: number;
  openEscalations: number;
  recentChangeRequests: number;

  // AI Insights
  renewalProbability: number; // 0-100
  riskFactors: string[];
  growthOpportunities: string[];
  clientConcerns: string[];
  recommendedActions: string[];
  suggestedServices: string[];
  suggestedTerms: string[];

  // Proposal
  currentPackage: string;
  recommendedPackage: string;
  revenueDifference: number; // positive = increase, negative = decrease
  serviceChanges: string[];
  contractTerms: string;
  expectedImpact: string;

  // Signals
  lastContactDays: number;
  openInvoices: number;
  delayedDeliverables: number;
  callSentiment: "Positive"| "Neutral"| "Negative"| "Mixed";
  reportingStatus: "Current"| "Overdue"| "Pending";
  projectStatus: "On Track"| "Monitor"| "Delayed"| "Blocked";
}

// ══════════════════════════════════════════════════════════════════════════════
// HELPERS
// ══════════════════════════════════════════════════════════════════════════════

function computeRenewalScore(b: Omit<RenewalScoreBreakdown, "overall">): RenewalScoreBreakdown {
  const overall = Math.round(
    b.clientHealth * 0.25 +
    b.projectHealth * 0.20 +
    b.communicationHealth * 0.20 +
    b.billingHealth * 0.15 +
    b.callIntelligence * 0.10 +
    b.reportingHealth * 0.05 +
    b.clientEngagement * 0.05
  );
  return { ...b, overall };
}

function daysFromNow(isoDate: string): number {
  const now = new Date("2025-07-01");
  const target = new Date(isoDate);
  return Math.round((target.getTime() - now.getTime()) / 86_400_000);
}

// ══════════════════════════════════════════════════════════════════════════════
// MOCK DATA — 30 RENEWAL RECORDS
// ══════════════════════════════════════════════════════════════════════════════

export const RENEWALS: RenewalRecord[] = [
  // ── 1 — Healthy, Renew As-Is ─────────────────────────────────────────────
  {
    id: "ren-001",
    client: "Acme Digital Partners",
    accountManager: "Sarah Mitchell",
    contract: "CTR-2022-001",
    mrr: 5200,
    arr: 62400,
    renewalDate: "2025-09-15",
    daysUntilRenewal: daysFromNow("2025-09-15"),
    status: "Review Scheduled",
    risk: "Low Risk",
    strategy: "Renew As-Is",
    score: computeRenewalScore({ clientHealth: 92, projectHealth: 88, communicationHealth: 91, billingHealth: 100, callIntelligence: 85, reportingHealth: 90, clientEngagement: 88 }),
    services: ["SEO", "Google Ads", "Reporting"],
    industry: "E-Commerce",
    clientSince: "2022-01-10",
    renewalHistory: 3,
    openIssues: 0,
    openEscalations: 0,
    recentChangeRequests: 1,
    renewalProbability: 94,
    riskFactors: ["Minor scope drift noted in Q2"],
    growthOpportunities: ["Add Meta Ads to existing paid media mix", "Expand reporting tier"],
    clientConcerns: [],
    recommendedActions: ["Schedule 30-day check-in call", "Present growth roadmap"],
    suggestedServices: ["Meta Ads Management", "Analytics Pro Tier"],
    suggestedTerms: ["12-month term", "5% MRR increase"],
    currentPackage: "SEO + Google Ads + Reporting",
    recommendedPackage: "SEO + Google Ads + Meta Ads + Reporting",
    revenueDifference: 1800,
    serviceChanges: ["Add Meta Ads"],
    contractTerms: "12-month, auto-renew, 30-day notice",
    expectedImpact: "Projected 22% increase in paid media ROI with Meta expansion",
    lastContactDays: 5,
    openInvoices: 0,
    delayedDeliverables: 0,
    callSentiment: "Positive",
    reportingStatus: "Current",
    projectStatus: "On Track",
  },

  // ── 2 — Upgrade Opportunity ───────────────────────────────────────────────
  {
    id: "ren-002",
    client: "BlueSky Marketing Group",
    accountManager: "James Carter",
    contract: "CTR-2023-045",
    mrr: 8500,
    arr: 102000,
    renewalDate: "2025-09-01",
    daysUntilRenewal: daysFromNow("2025-09-01"),
    status: "Proposal In Progress",
    risk: "Low Risk",
    strategy: "Renew With Upgrade",
    score: computeRenewalScore({ clientHealth: 88, projectHealth: 90, communicationHealth: 86, billingHealth: 95, callIntelligence: 80, reportingHealth: 88, clientEngagement: 92 }),
    services: ["SEO", "Content", "Email Marketing"],
    industry: "SaaS",
    clientSince: "2023-02-15",
    renewalHistory: 1,
    openIssues: 1,
    openEscalations: 0,
    recentChangeRequests: 2,
    renewalProbability: 91,
    riskFactors: ["Competitor offering pitched to client"],
    growthOpportunities: ["Add Paid Advertising", "Expand content volume"],
    clientConcerns: ["Wants faster content turnaround"],
    recommendedActions: ["Present upgrade proposal", "Address turnaround SLA", "Demo analytics dashboard"],
    suggestedServices: ["Google Ads", "Content Volume Increase"],
    suggestedTerms: ["12-month term", "Bundled discount on upgrade"],
    currentPackage: "SEO + Content + Email Marketing",
    recommendedPackage: "SEO + Content Pro + Google Ads + Email Marketing",
    revenueDifference: 3200,
    serviceChanges: ["Upgrade Content to Pro", "Add Google Ads"],
    contractTerms: "12-month, 10% bundled discount",
    expectedImpact: "Estimated 35% traffic increase with full-funnel strategy",
    lastContactDays: 3,
    openInvoices: 0,
    delayedDeliverables: 1,
    callSentiment: "Positive",
    reportingStatus: "Current",
    projectStatus: "On Track",
  },

  // ── 3 — At Risk, Retention Plan ───────────────────────────────────────────
  {
    id: "ren-003",
    client: "NovaTech Industries",
    accountManager: "Sarah Mitchell",
    contract: "CTR-2022-078",
    mrr: 12000,
    arr: 144000,
    renewalDate: "2025-07-22",
    daysUntilRenewal: daysFromNow("2025-07-22"),
    status: "Negotiation",
    risk: "Critical",
    strategy: "Executive Intervention Required",
    score: computeRenewalScore({ clientHealth: 38, projectHealth: 45, communicationHealth: 32, billingHealth: 60, callIntelligence: 42, reportingHealth: 50, clientEngagement: 28 }),
    services: ["Google Ads", "Meta Ads", "SEO", "Reporting"],
    industry: "Manufacturing",
    clientSince: "2022-03-01",
    renewalHistory: 2,
    openIssues: 5,
    openEscalations: 2,
    recentChangeRequests: 4,
    renewalProbability: 28,
    riskFactors: ["Two open escalations unresolved for 30+ days", "Declining call sentiment", "Missed reporting deadlines", "Client has issued 4 change requests in 60 days"],
    growthOpportunities: [],
    clientConcerns: ["Support response times", "Campaign performance below benchmark", "Report quality"],
    recommendedActions: ["Executive call within 48 hours", "Assign dedicated support lead", "Resolve all open escalations", "Prepare retention offer"],
    suggestedServices: [],
    suggestedTerms: ["Service credit applied", "Enhanced SLA tier", "Dedicated account pod"],
    currentPackage: "Google Ads + Meta Ads + SEO + Reporting",
    recommendedPackage: "Same services with enhanced SLA and dedicated support",
    revenueDifference: 0,
    serviceChanges: ["Add Dedicated Support Pod", "Apply 3-month SLA credit"],
    contractTerms: "12-month, enhanced SLA, service credit applied",
    expectedImpact: "Retention at current MRR with improved satisfaction and escalation resolution",
    lastContactDays: 12,
    openInvoices: 2,
    delayedDeliverables: 3,
    callSentiment: "Negative",
    reportingStatus: "Overdue",
    projectStatus: "Blocked",
  },

  // ── 4 — Moderate Risk ─────────────────────────────────────────────────────
  {
    id: "ren-004",
    client: "Greenfield Media Co",
    accountManager: "Rachel Torres",
    contract: "CTR-2023-112",
    mrr: 4800,
    arr: 57600,
    renewalDate: "2025-09-30",
    daysUntilRenewal: daysFromNow("2025-09-30"),
    status: "Planning",
    risk: "Moderate Risk",
    strategy: "Renew With Service Changes",
    score: computeRenewalScore({ clientHealth: 62, projectHealth: 55, communicationHealth: 70, billingHealth: 85, callIntelligence: 60, reportingHealth: 65, clientEngagement: 58 }),
    services: ["SEO", "Content"],
    industry: "Media & Publishing",
    clientSince: "2023-05-20",
    renewalHistory: 1,
    openIssues: 2,
    openEscalations: 1,
    recentChangeRequests: 3,
    renewalProbability: 62,
    riskFactors: ["One open escalation", "2 delayed deliverables", "Budget review in progress"],
    growthOpportunities: ["Add Email Marketing", "Local SEO expansion"],
    clientConcerns: ["Content quality inconsistency", "Budget uncertainty for next fiscal"],
    recommendedActions: ["Review content delivery SLA", "Offer flexible payment terms", "Resolve escalation"],
    suggestedServices: ["Email Marketing", "Local SEO"],
    suggestedTerms: ["Monthly billing option", "12-month with quarterly review"],
    currentPackage: "SEO + Content",
    recommendedPackage: "SEO + Content + Email Marketing",
    revenueDifference: 1200,
    serviceChanges: ["Add Email Marketing", "Adjust content volume"],
    contractTerms: "12-month, monthly billing available",
    expectedImpact: "Improved retention with flexible billing and expanded scope",
    lastContactDays: 8,
    openInvoices: 0,
    delayedDeliverables: 2,
    callSentiment: "Neutral",
    reportingStatus: "Current",
    projectStatus: "Monitor",
  },

  // ── 5 — Renewed ──────────────────────────────────────────────────────────
  {
    id: "ren-005",
    client: "Vertex Capital Group",
    accountManager: "James Carter",
    contract: "CTR-2022-056",
    mrr: 6500,
    arr: 78000,
    renewalDate: "2025-07-01",
    daysUntilRenewal: daysFromNow("2025-07-01"),
    status: "Renewed",
    risk: "Low Risk",
    strategy: "Renew As-Is",
    score: computeRenewalScore({ clientHealth: 91, projectHealth: 89, communicationHealth: 93, billingHealth: 100, callIntelligence: 87, reportingHealth: 91, clientEngagement: 90 }),
    services: ["Google Ads", "SEO", "Reporting"],
    industry: "Finance",
    clientSince: "2022-07-01",
    renewalHistory: 3,
    openIssues: 0,
    openEscalations: 0,
    recentChangeRequests: 0,
    renewalProbability: 98,
    riskFactors: [],
    growthOpportunities: ["Explore LinkedIn Ads", "Add competitive intelligence reporting"],
    clientConcerns: [],
    recommendedActions: ["Confirm billing updated", "Schedule Q3 kickoff"],
    suggestedServices: ["LinkedIn Ads", "Competitive Intelligence"],
    suggestedTerms: ["12-month renewal at current rate"],
    currentPackage: "Google Ads + SEO + Reporting",
    recommendedPackage: "Google Ads + SEO + Reporting",
    revenueDifference: 0,
    serviceChanges: [],
    contractTerms: "12-month, auto-renew",
    expectedImpact: "Continued performance with stable account team",
    lastContactDays: 1,
    openInvoices: 0,
    delayedDeliverables: 0,
    callSentiment: "Positive",
    reportingStatus: "Current",
    projectStatus: "On Track",
  },

  // ── 6 — Budget Adjustment ─────────────────────────────────────────────────
  {
    id: "ren-006",
    client: "Summit Digital LLC",
    accountManager: "Rachel Torres",
    contract: "CTR-2023-088",
    mrr: 3900,
    arr: 46800,
    renewalDate: "2025-08-15",
    daysUntilRenewal: daysFromNow("2025-08-15"),
    status: "Negotiation",
    risk: "Moderate Risk",
    strategy: "Renew With Budget Adjustment",
    score: computeRenewalScore({ clientHealth: 66, projectHealth: 70, communicationHealth: 72, billingHealth: 75, callIntelligence: 65, reportingHealth: 70, clientEngagement: 60 }),
    services: ["Meta Ads", "Email Marketing"],
    industry: "Retail",
    clientSince: "2023-08-01",
    renewalHistory: 1,
    openIssues: 1,
    openEscalations: 0,
    recentChangeRequests: 2,
    renewalProbability: 70,
    riskFactors: ["Client requested 15% budget reduction", "Seasonal revenue pressure"],
    growthOpportunities: ["Reallocate budget to higher-ROI channels"],
    clientConcerns: ["Seasonal cash flow", "Meta Ads ROAS below target Q1"],
    recommendedActions: ["Present revised budget allocation", "Offer performance guarantee"],
    suggestedServices: [],
    suggestedTerms: ["12-month at adjusted rate", "Performance bonus clause"],
    currentPackage: "Meta Ads + Email Marketing",
    recommendedPackage: "Meta Ads (Adjusted Budget) + Email Marketing",
    revenueDifference: -600,
    serviceChanges: ["Reduce Meta Ads budget 15%", "Retain Email Marketing"],
    contractTerms: "12-month, revised rate, performance bonus",
    expectedImpact: "Retains client at adjusted rate with performance upside",
    lastContactDays: 4,
    openInvoices: 1,
    delayedDeliverables: 0,
    callSentiment: "Neutral",
    reportingStatus: "Current",
    projectStatus: "On Track",
  },

  // ── 7 — High Risk ─────────────────────────────────────────────────────────
  {
    id: "ren-007",
    client: "Cobalt Systems Inc",
    accountManager: "Sarah Mitchell",
    contract: "CTR-2022-033",
    mrr: 9800,
    arr: 117600,
    renewalDate: "2025-08-01",
    daysUntilRenewal: daysFromNow("2025-08-01"),
    status: "Review Scheduled",
    risk: "High Risk",
    strategy: "Retention Plan Required",
    score: computeRenewalScore({ clientHealth: 48, projectHealth: 52, communicationHealth: 44, billingHealth: 70, callIntelligence: 50, reportingHealth: 55, clientEngagement: 40 }),
    services: ["SEO", "Google Ads", "Content", "Reporting"],
    industry: "Technology",
    clientSince: "2022-02-15",
    renewalHistory: 2,
    openIssues: 3,
    openEscalations: 1,
    recentChangeRequests: 3,
    renewalProbability: 45,
    riskFactors: ["Communication health declining", "3 open issues", "Competitor evaluation underway", "Reporting delivered late twice"],
    growthOpportunities: [],
    clientConcerns: ["Slow response times", "Campaign performance", "Report delivery delays"],
    recommendedActions: ["Immediate account review call", "Assign senior AM support", "Create retention package", "Resolve open issues within 7 days"],
    suggestedServices: ["Priority Support Tier"],
    suggestedTerms: ["12-month with quarterly performance review", "Exit clause waived"],
    currentPackage: "SEO + Google Ads + Content + Reporting",
    recommendedPackage: "Same services with Priority Support added",
    revenueDifference: 600,
    serviceChanges: ["Add Priority Support Tier"],
    contractTerms: "12-month, quarterly review, 30-day early exit clause",
    expectedImpact: "Improved satisfaction and early warning system with quarterly reviews",
    lastContactDays: 15,
    openInvoices: 0,
    delayedDeliverables: 2,
    callSentiment: "Negative",
    reportingStatus: "Pending",
    projectStatus: "Monitor",
  },

  // ── 8 — Lost ──────────────────────────────────────────────────────────────
  {
    id: "ren-008",
    client: "Harmon & Associates",
    accountManager: "James Carter",
    contract: "CTR-2021-019",
    mrr: 7200,
    arr: 86400,
    renewalDate: "2025-07-10",
    daysUntilRenewal: daysFromNow("2025-07-10"),
    status: "Lost",
    risk: "Critical",
    strategy: "Executive Intervention Required",
    score: computeRenewalScore({ clientHealth: 22, projectHealth: 30, communicationHealth: 25, billingHealth: 40, callIntelligence: 28, reportingHealth: 35, clientEngagement: 18 }),
    services: ["SEO", "Meta Ads", "Email Marketing"],
    industry: "Legal Services",
    clientSince: "2021-07-10",
    renewalHistory: 3,
    openIssues: 6,
    openEscalations: 3,
    recentChangeRequests: 5,
    renewalProbability: 8,
    riskFactors: ["3 unresolved escalations", "6 open issues", "Billing disputes", "Competitor won pitch", "Low engagement for 60 days"],
    growthOpportunities: [],
    clientConcerns: ["Billing disputes", "Inconsistent deliverables", "No dedicated AM consistency"],
    recommendedActions: ["Post-mortem analysis", "Document lessons learned", "Initiate offboarding process"],
    suggestedServices: [],
    suggestedTerms: [],
    currentPackage: "SEO + Meta Ads + Email Marketing",
    recommendedPackage: "N/A — Account Lost",
    revenueDifference: -86400,
    serviceChanges: [],
    contractTerms: "N/A",
    expectedImpact: "Revenue at risk: $86,400/yr. Offboarding initiated.",
    lastContactDays: 30,
    openInvoices: 3,
    delayedDeliverables: 4,
    callSentiment: "Negative",
    reportingStatus: "Overdue",
    projectStatus: "Blocked",
  },

  // ── 9 — Upgrade Opportunity ───────────────────────────────────────────────
  {
    id: "ren-009",
    client: "Crestview Brands",
    accountManager: "Rachel Torres",
    contract: "CTR-2023-201",
    mrr: 5600,
    arr: 67200,
    renewalDate: "2025-10-01",
    daysUntilRenewal: daysFromNow("2025-10-01"),
    status: "Planning",
    risk: "Low Risk",
    strategy: "Renew With Upgrade",
    score: computeRenewalScore({ clientHealth: 85, projectHealth: 87, communicationHealth: 82, billingHealth: 98, callIntelligence: 79, reportingHealth: 84, clientEngagement: 88 }),
    services: ["Content", "Email Marketing", "SEO"],
    industry: "Consumer Goods",
    clientSince: "2023-01-15",
    renewalHistory: 1,
    openIssues: 0,
    openEscalations: 0,
    recentChangeRequests: 1,
    renewalProbability: 90,
    riskFactors: ["New marketing director may revisit vendor relationships"],
    growthOpportunities: ["Add Paid Social", "Expand email automation"],
    clientConcerns: ["New leadership transition"],
    recommendedActions: ["Schedule intro call with new marketing director", "Present 12-month growth roadmap"],
    suggestedServices: ["Meta Ads", "Email Automation Pro"],
    suggestedTerms: ["12-month at upgraded rate", "Onboarding fee waived"],
    currentPackage: "Content + Email Marketing + SEO",
    recommendedPackage: "Content + Email Pro + SEO + Meta Ads",
    revenueDifference: 2400,
    serviceChanges: ["Upgrade Email to Pro", "Add Meta Ads"],
    contractTerms: "12-month, onboarding waived, 30-day notice",
    expectedImpact: "Full-funnel capability expansion, estimated 28% traffic growth",
    lastContactDays: 7,
    openInvoices: 0,
    delayedDeliverables: 0,
    callSentiment: "Positive",
    reportingStatus: "Current",
    projectStatus: "On Track",
  },

  // ── 10 — Healthy, Renew As-Is ─────────────────────────────────────────────
  {
    id: "ren-010",
    client: "Meridian Health Group",
    accountManager: "Sarah Mitchell",
    contract: "CTR-2022-145",
    mrr: 11200,
    arr: 134400,
    renewalDate: "2025-08-30",
    daysUntilRenewal: daysFromNow("2025-08-30"),
    status: "Review Scheduled",
    risk: "Low Risk",
    strategy: "Renew As-Is",
    score: computeRenewalScore({ clientHealth: 90, projectHealth: 91, communicationHealth: 89, billingHealth: 100, callIntelligence: 88, reportingHealth: 92, clientEngagement: 87 }),
    services: ["SEO", "Content", "Google Ads", "Reporting"],
    industry: "Healthcare",
    clientSince: "2022-09-01",
    renewalHistory: 2,
    openIssues: 0,
    openEscalations: 0,
    recentChangeRequests: 1,
    renewalProbability: 96,
    riskFactors: [],
    growthOpportunities: ["Add Reputation Management", "Expand local SEO"],
    clientConcerns: [],
    recommendedActions: ["Send renewal proposal early", "Present expansion roadmap"],
    suggestedServices: ["Reputation Management", "Local SEO Expansion"],
    suggestedTerms: ["24-month with loyalty discount"],
    currentPackage: "SEO + Content + Google Ads + Reporting",
    recommendedPackage: "Same — present 24-month option",
    revenueDifference: 0,
    serviceChanges: [],
    contractTerms: "12 or 24-month, loyalty discount at 24-month",
    expectedImpact: "Stable revenue lock-in with multi-year deal incentive",
    lastContactDays: 3,
    openInvoices: 0,
    delayedDeliverables: 0,
    callSentiment: "Positive",
    reportingStatus: "Current",
    projectStatus: "On Track",
  },

  // ── 11 — Moderate Risk ────────────────────────────────────────────────────
  {
    id: "ren-011",
    client: "Pinnacle Real Estate",
    accountManager: "James Carter",
    contract: "CTR-2023-067",
    mrr: 4200,
    arr: 50400,
    renewalDate: "2025-09-10",
    daysUntilRenewal: daysFromNow("2025-09-10"),
    status: "Planning",
    risk: "Moderate Risk",
    strategy: "Renew With Service Changes",
    score: computeRenewalScore({ clientHealth: 63, projectHealth: 60, communicationHealth: 68, billingHealth: 80, callIntelligence: 62, reportingHealth: 65, clientEngagement: 55 }),
    services: ["Google Ads", "Meta Ads"],
    industry: "Real Estate",
    clientSince: "2023-03-10",
    renewalHistory: 1,
    openIssues: 2,
    openEscalations: 0,
    recentChangeRequests: 2,
    renewalProbability: 65,
    riskFactors: ["Market slowdown affecting client ROI expectations", "2 open issues"],
    growthOpportunities: ["Add Local SEO to supplement paid media"],
    clientConcerns: ["Market conditions lowering lead quality", "Wants more granular reporting"],
    recommendedActions: ["Deliver enhanced reporting", "Add Local SEO to proposal", "Address lead quality concerns"],
    suggestedServices: ["Local SEO", "Enhanced Reporting Tier"],
    suggestedTerms: ["12-month with enhanced reporting included"],
    currentPackage: "Google Ads + Meta Ads",
    recommendedPackage: "Google Ads + Meta Ads + Local SEO",
    revenueDifference: 800,
    serviceChanges: ["Add Local SEO"],
    contractTerms: "12-month, enhanced reporting included at no charge",
    expectedImpact: "Improved lead quality metrics with organic-paid hybrid approach",
    lastContactDays: 6,
    openInvoices: 0,
    delayedDeliverables: 1,
    callSentiment: "Neutral",
    reportingStatus: "Current",
    projectStatus: "Monitor",
  },

  // ── 12 ────────────────────────────────────────────────────────────────────
  {
    id: "ren-012",
    client: "Stonebridge Law Firm",
    accountManager: "Rachel Torres",
    contract: "CTR-2022-099",
    mrr: 3500,
    arr: 42000,
    renewalDate: "2025-10-15",
    daysUntilRenewal: daysFromNow("2025-10-15"),
    status: "Not Started",
    risk: "Low Risk",
    strategy: "Renew As-Is",
    score: computeRenewalScore({ clientHealth: 82, projectHealth: 80, communicationHealth: 84, billingHealth: 100, callIntelligence: 78, reportingHealth: 82, clientEngagement: 80 }),
    services: ["SEO", "Content"],
    industry: "Legal",
    clientSince: "2022-10-15",
    renewalHistory: 2,
    openIssues: 0,
    openEscalations: 0,
    recentChangeRequests: 0,
    renewalProbability: 88,
    riskFactors: [],
    growthOpportunities: ["Add Google Ads", "Add Reputation Management"],
    clientConcerns: [],
    recommendedActions: ["Initiate renewal conversation at 90-day mark"],
    suggestedServices: ["Google Ads", "Reputation Management"],
    suggestedTerms: ["12-month renewal, 5% loyalty rate"],
    currentPackage: "SEO + Content",
    recommendedPackage: "SEO + Content",
    revenueDifference: 0,
    serviceChanges: [],
    contractTerms: "12-month, 5% loyalty discount",
    expectedImpact: "Straightforward renewal with strong relationship history",
    lastContactDays: 10,
    openInvoices: 0,
    delayedDeliverables: 0,
    callSentiment: "Positive",
    reportingStatus: "Current",
    projectStatus: "On Track",
  },

  // ── 13 ────────────────────────────────────────────────────────────────────
  {
    id: "ren-013",
    client: "Ironclad Fitness",
    accountManager: "Sarah Mitchell",
    contract: "CTR-2023-155",
    mrr: 2800,
    arr: 33600,
    renewalDate: "2025-08-20",
    daysUntilRenewal: daysFromNow("2025-08-20"),
    status: "Proposal In Progress",
    risk: "Moderate Risk",
    strategy: "Renew With Budget Adjustment",
    score: computeRenewalScore({ clientHealth: 60, projectHealth: 62, communicationHealth: 65, billingHealth: 70, callIntelligence: 58, reportingHealth: 62, clientEngagement: 55 }),
    services: ["Meta Ads", "Email Marketing"],
    industry: "Health & Fitness",
    clientSince: "2023-08-20",
    renewalHistory: 1,
    openIssues: 1,
    openEscalations: 0,
    recentChangeRequests: 2,
    renewalProbability: 68,
    riskFactors: ["Seasonal business model creates Q3 budget pressure", "1 open issue"],
    growthOpportunities: ["Add Google Ads for off-season lead generation"],
    clientConcerns: ["Off-season revenue dip", "Wants flexible billing"],
    recommendedActions: ["Offer seasonal billing option", "Present annual performance review"],
    suggestedServices: ["Google Ads (off-season)"],
    suggestedTerms: ["12-month with seasonal billing flexibility"],
    currentPackage: "Meta Ads + Email Marketing",
    recommendedPackage: "Meta Ads (adjusted) + Email Marketing",
    revenueDifference: -400,
    serviceChanges: ["Adjust Meta Ads budget seasonally"],
    contractTerms: "12-month, seasonal budget flex",
    expectedImpact: "Retains client with budget-friendly renewal structure",
    lastContactDays: 5,
    openInvoices: 1,
    delayedDeliverables: 0,
    callSentiment: "Neutral",
    reportingStatus: "Current",
    projectStatus: "On Track",
  },

  // ── 14 ────────────────────────────────────────────────────────────────────
  {
    id: "ren-014",
    client: "Offshore Capital Partners",
    accountManager: "James Carter",
    contract: "CTR-2022-201",
    mrr: 15000,
    arr: 180000,
    renewalDate: "2025-07-28",
    daysUntilRenewal: daysFromNow("2025-07-28"),
    status: "Pending Signature",
    risk: "Low Risk",
    strategy: "Renew With Upgrade",
    score: computeRenewalScore({ clientHealth: 93, projectHealth: 90, communicationHealth: 92, billingHealth: 100, callIntelligence: 89, reportingHealth: 94, clientEngagement: 95 }),
    services: ["SEO", "Google Ads", "Meta Ads", "Content", "Reporting", "Email Marketing"],
    industry: "Finance",
    clientSince: "2022-01-28",
    renewalHistory: 3,
    openIssues: 0,
    openEscalations: 0,
    recentChangeRequests: 1,
    renewalProbability: 97,
    riskFactors: [],
    growthOpportunities: ["Add LinkedIn Ads", "Add data analytics retainer"],
    clientConcerns: [],
    recommendedActions: ["Confirm signature", "Schedule Q3 onboarding for new services"],
    suggestedServices: ["LinkedIn Ads", "Data Analytics Retainer"],
    suggestedTerms: ["24-month with locked rate"],
    currentPackage: "Full Service Bundle",
    recommendedPackage: "Full Service Bundle + LinkedIn Ads + Analytics",
    revenueDifference: 4000,
    serviceChanges: ["Add LinkedIn Ads", "Add Analytics Retainer"],
    contractTerms: "24-month, locked rate, quarterly review",
    expectedImpact: "Strategic multi-year partnership, $228K ARR",
    lastContactDays: 2,
    openInvoices: 0,
    delayedDeliverables: 0,
    callSentiment: "Positive",
    reportingStatus: "Current",
    projectStatus: "On Track",
  },

  // ── 15 ────────────────────────────────────────────────────────────────────
  {
    id: "ren-015",
    client: "TrueNorth Logistics",
    accountManager: "Rachel Torres",
    contract: "CTR-2023-178",
    mrr: 6100,
    arr: 73200,
    renewalDate: "2025-09-05",
    daysUntilRenewal: daysFromNow("2025-09-05"),
    status: "Review Scheduled",
    risk: "Low Risk",
    strategy: "Renew As-Is",
    score: computeRenewalScore({ clientHealth: 86, projectHealth: 84, communicationHealth: 88, billingHealth: 95, callIntelligence: 82, reportingHealth: 87, clientEngagement: 84 }),
    services: ["Google Ads", "SEO"],
    industry: "Logistics",
    clientSince: "2023-09-05",
    renewalHistory: 1,
    openIssues: 0,
    openEscalations: 0,
    recentChangeRequests: 1,
    renewalProbability: 89,
    riskFactors: ["First renewal — relationship still building"],
    growthOpportunities: ["Add Content Marketing", "Expand Google Ads scope"],
    clientConcerns: [],
    recommendedActions: ["Present first-year performance summary", "Introduce expansion options"],
    suggestedServices: ["Content Marketing", "Display Advertising"],
    suggestedTerms: ["12-month at current rate with loyalty credit"],
    currentPackage: "Google Ads + SEO",
    recommendedPackage: "Google Ads + SEO + Content",
    revenueDifference: 1500,
    serviceChanges: ["Add Content Marketing"],
    contractTerms: "12-month, loyalty credit applied",
    expectedImpact: "Deepen relationship in year 2 with content-backed SEO",
    lastContactDays: 6,
    openInvoices: 0,
    delayedDeliverables: 0,
    callSentiment: "Positive",
    reportingStatus: "Current",
    projectStatus: "On Track",
  },

  // ── 16 ────────────────────────────────────────────────────────────────────
  {
    id: "ren-016",
    client: "Apex Construction Group",
    accountManager: "Sarah Mitchell",
    contract: "CTR-2022-067",
    mrr: 5000,
    arr: 60000,
    renewalDate: "2025-08-10",
    daysUntilRenewal: daysFromNow("2025-08-10"),
    status: "Planning",
    risk: "High Risk",
    strategy: "Retention Plan Required",
    score: computeRenewalScore({ clientHealth: 44, projectHealth: 50, communicationHealth: 48, billingHealth: 65, callIntelligence: 45, reportingHealth: 50, clientEngagement: 38 }),
    services: ["Google Ads", "Content"],
    industry: "Construction",
    clientSince: "2022-08-10",
    renewalHistory: 2,
    openIssues: 3,
    openEscalations: 1,
    recentChangeRequests: 3,
    renewalProbability: 42,
    riskFactors: ["Account manager change in Q1", "3 open issues", "Communication gap 15 days", "Delayed deliverables trend"],
    growthOpportunities: [],
    clientConcerns: ["AM turnover disrupted relationship", "Campaign performance inconsistency"],
    recommendedActions: ["Reintroduce account team", "Review all open issues", "Offer dedicated account pod"],
    suggestedServices: [],
    suggestedTerms: ["12-month with AM stability guarantee"],
    currentPackage: "Google Ads + Content",
    recommendedPackage: "Same with dedicated account pod",
    revenueDifference: 0,
    serviceChanges: ["Add Dedicated AM assignment"],
    contractTerms: "12-month, named AM guarantee, quarterly review",
    expectedImpact: "Retention via relationship stabilization and performance recovery",
    lastContactDays: 15,
    openInvoices: 0,
    delayedDeliverables: 2,
    callSentiment: "Negative",
    reportingStatus: "Pending",
    projectStatus: "Monitor",
  },

  // ── 17 ────────────────────────────────────────────────────────────────────
  {
    id: "ren-017",
    client: "Quantum Software Corp",
    accountManager: "James Carter",
    contract: "CTR-2023-099",
    mrr: 8800,
    arr: 105600,
    renewalDate: "2025-10-20",
    daysUntilRenewal: daysFromNow("2025-10-20"),
    status: "Not Started",
    risk: "Low Risk",
    strategy: "Renew With Upgrade",
    score: computeRenewalScore({ clientHealth: 89, projectHealth: 88, communicationHealth: 90, billingHealth: 98, callIntelligence: 86, reportingHealth: 91, clientEngagement: 92 }),
    services: ["SEO", "Google Ads", "Content"],
    industry: "Software",
    clientSince: "2023-10-20",
    renewalHistory: 0,
    openIssues: 0,
    openEscalations: 0,
    recentChangeRequests: 1,
    renewalProbability: 92,
    riskFactors: [],
    growthOpportunities: ["Add LinkedIn Ads for B2B targeting", "Enterprise reporting tier"],
    clientConcerns: [],
    recommendedActions: ["Initiate renewal at 90 days", "Present B2B expansion strategy"],
    suggestedServices: ["LinkedIn Ads", "Enterprise Reporting"],
    suggestedTerms: ["12-month with early signature incentive"],
    currentPackage: "SEO + Google Ads + Content",
    recommendedPackage: "SEO + Google Ads + Content + LinkedIn Ads",
    revenueDifference: 3000,
    serviceChanges: ["Add LinkedIn Ads"],
    contractTerms: "12-month, early signature 5% discount",
    expectedImpact: "B2B funnel expansion with estimated 40% MQL improvement",
    lastContactDays: 4,
    openInvoices: 0,
    delayedDeliverables: 0,
    callSentiment: "Positive",
    reportingStatus: "Current",
    projectStatus: "On Track",
  },

  // ── 18 ────────────────────────────────────────────────────────────────────
  {
    id: "ren-018",
    client: "Brightside Education",
    accountManager: "Rachel Torres",
    contract: "CTR-2022-188",
    mrr: 3200,
    arr: 38400,
    renewalDate: "2025-08-25",
    daysUntilRenewal: daysFromNow("2025-08-25"),
    status: "Proposal In Progress",
    risk: "Moderate Risk",
    strategy: "Renew With Service Changes",
    score: computeRenewalScore({ clientHealth: 64, projectHealth: 66, communicationHealth: 70, billingHealth: 80, callIntelligence: 60, reportingHealth: 68, clientEngagement: 62 }),
    services: ["Content", "Email Marketing"],
    industry: "Education",
    clientSince: "2022-08-25",
    renewalHistory: 2,
    openIssues: 1,
    openEscalations: 0,
    recentChangeRequests: 2,
    renewalProbability: 72,
    riskFactors: ["New academic year budget cycle", "Service mismatch — wants more digital focus"],
    growthOpportunities: ["Add Google Ads for student enrollment campaigns"],
    clientConcerns: ["Content not aligned to enrollment goals", "Needs enrollment-focused strategy"],
    recommendedActions: ["Realign content strategy to enrollment goals", "Present Google Ads pilot for enrollment"],
    suggestedServices: ["Google Ads (Enrollment Campaign)"],
    suggestedTerms: ["12-month with enrollment-focused SLA"],
    currentPackage: "Content + Email Marketing",
    recommendedPackage: "Content (Enrollment Focus) + Google Ads + Email Marketing",
    revenueDifference: 1100,
    serviceChanges: ["Pivot Content to enrollment-focused", "Add Google Ads"],
    contractTerms: "12-month, enrollment SLA included",
    expectedImpact: "Aligned strategy drives measurable enrollment outcomes",
    lastContactDays: 7,
    openInvoices: 0,
    delayedDeliverables: 1,
    callSentiment: "Neutral",
    reportingStatus: "Current",
    projectStatus: "Monitor",
  },

  // ── 19 ────────────────────────────────────────────────────────────────────
  {
    id: "ren-019",
    client: "Silverstone Auto Group",
    accountManager: "Sarah Mitchell",
    contract: "CTR-2023-222",
    mrr: 7400,
    arr: 88800,
    renewalDate: "2025-09-18",
    daysUntilRenewal: daysFromNow("2025-09-18"),
    status: "Planning",
    risk: "Low Risk",
    strategy: "Renew With Upgrade",
    score: computeRenewalScore({ clientHealth: 84, projectHealth: 85, communicationHealth: 83, billingHealth: 96, callIntelligence: 81, reportingHealth: 86, clientEngagement: 85 }),
    services: ["Google Ads", "Meta Ads", "SEO"],
    industry: "Automotive",
    clientSince: "2023-03-18",
    renewalHistory: 1,
    openIssues: 0,
    openEscalations: 0,
    recentChangeRequests: 1,
    renewalProbability: 88,
    riskFactors: ["Inventory shortages may affect campaign spend Q3"],
    growthOpportunities: ["Add email marketing for service department", "Expand inventory-specific campaigns"],
    clientConcerns: ["Inventory availability affecting ad performance"],
    recommendedActions: ["Present inventory-aware campaign strategy", "Add email for service upsell"],
    suggestedServices: ["Email Marketing (Service Dept)", "Dynamic Inventory Ads"],
    suggestedTerms: ["12-month, inventory-flex campaign structure"],
    currentPackage: "Google Ads + Meta Ads + SEO",
    recommendedPackage: "Google Ads + Meta Ads + SEO + Email (Service)",
    revenueDifference: 2200,
    serviceChanges: ["Add Service Email Marketing"],
    contractTerms: "12-month, inventory-flex pause clause",
    expectedImpact: "Service department revenue stream adds revenue floor during inventory gaps",
    lastContactDays: 4,
    openInvoices: 0,
    delayedDeliverables: 0,
    callSentiment: "Positive",
    reportingStatus: "Current",
    projectStatus: "On Track",
  },

  // ── 20 ────────────────────────────────────────────────────────────────────
  {
    id: "ren-020",
    client: "Harborview Hotels",
    accountManager: "James Carter",
    contract: "CTR-2022-244",
    mrr: 9500,
    arr: 114000,
    renewalDate: "2025-08-05",
    daysUntilRenewal: daysFromNow("2025-08-05"),
    status: "Review Scheduled",
    risk: "Moderate Risk",
    strategy: "Renew With Service Changes",
    score: computeRenewalScore({ clientHealth: 65, projectHealth: 62, communicationHealth: 68, billingHealth: 82, callIntelligence: 63, reportingHealth: 66, clientEngagement: 60 }),
    services: ["Google Ads", "Meta Ads", "Content", "SEO", "Email Marketing"],
    industry: "Hospitality",
    clientSince: "2022-08-05",
    renewalHistory: 2,
    openIssues: 2,
    openEscalations: 1,
    recentChangeRequests: 3,
    renewalProbability: 66,
    riskFactors: ["Post-pandemic recovery affecting hospitality spend", "1 escalation open", "Wants to reduce scope"],
    growthOpportunities: ["Streamline to highest-ROI channels"],
    clientConcerns: ["Budget optimization needed", "Too many service lines"],
    recommendedActions: ["Conduct service audit", "Present streamlined package", "Resolve escalation"],
    suggestedServices: [],
    suggestedTerms: ["12-month streamlined package"],
    currentPackage: "Google Ads + Meta Ads + Content + SEO + Email",
    recommendedPackage: "Google Ads + Meta Ads + SEO",
    revenueDifference: -2500,
    serviceChanges: ["Remove Content", "Remove Email Marketing"],
    contractTerms: "12-month, streamlined at lower rate",
    expectedImpact: "Client retention at reduced scope, lower churn risk",
    lastContactDays: 9,
    openInvoices: 0,
    delayedDeliverables: 2,
    callSentiment: "Mixed",
    reportingStatus: "Pending",
    projectStatus: "Monitor",
  },

  // ── 21 ────────────────────────────────────────────────────────────────────
  {
    id: "ren-021",
    client: "Pacific Rim Exports",
    accountManager: "Rachel Torres",
    contract: "CTR-2023-133",
    mrr: 4400,
    arr: 52800,
    renewalDate: "2025-09-22",
    daysUntilRenewal: daysFromNow("2025-09-22"),
    status: "Not Started",
    risk: "Low Risk",
    strategy: "Renew As-Is",
    score: computeRenewalScore({ clientHealth: 80, projectHealth: 78, communicationHealth: 82, billingHealth: 95, callIntelligence: 76, reportingHealth: 80, clientEngagement: 78 }),
    services: ["SEO", "Content"],
    industry: "Import/Export",
    clientSince: "2023-09-22",
    renewalHistory: 0,
    openIssues: 0,
    openEscalations: 0,
    recentChangeRequests: 0,
    renewalProbability: 85,
    riskFactors: ["First renewal — relationship to be deepened"],
    growthOpportunities: ["Add Google Ads", "Add International SEO"],
    clientConcerns: [],
    recommendedActions: ["Begin renewal conversation at 90-day mark", "Highlight first-year wins"],
    suggestedServices: ["Google Ads", "International SEO"],
    suggestedTerms: ["12-month with first-renewal incentive"],
    currentPackage: "SEO + Content",
    recommendedPackage: "SEO + Content + Google Ads",
    revenueDifference: 1600,
    serviceChanges: ["Add Google Ads"],
    contractTerms: "12-month, first-renewal loyalty rate",
    expectedImpact: "Year 2 expansion into paid media with proven organic base",
    lastContactDays: 8,
    openInvoices: 0,
    delayedDeliverables: 0,
    callSentiment: "Positive",
    reportingStatus: "Current",
    projectStatus: "On Track",
  },

  // ── 22 ────────────────────────────────────────────────────────────────────
  {
    id: "ren-022",
    client: "Driftwood Brewing Co",
    accountManager: "Sarah Mitchell",
    contract: "CTR-2023-144",
    mrr: 2600,
    arr: 31200,
    renewalDate: "2025-07-30",
    daysUntilRenewal: daysFromNow("2025-07-30"),
    status: "Negotiation",
    risk: "Moderate Risk",
    strategy: "Renew With Budget Adjustment",
    score: computeRenewalScore({ clientHealth: 62, projectHealth: 60, communicationHealth: 65, billingHealth: 72, callIntelligence: 58, reportingHealth: 63, clientEngagement: 55 }),
    services: ["Meta Ads", "Content"],
    industry: "Food & Beverage",
    clientSince: "2023-07-30",
    renewalHistory: 1,
    openIssues: 1,
    openEscalations: 0,
    recentChangeRequests: 1,
    renewalProbability: 65,
    riskFactors: ["Seasonal sales cycle creates Q3 budget pressure", "Small business cash flow sensitivity"],
    growthOpportunities: ["Add Event Marketing during peak season"],
    clientConcerns: ["Off-season cash flow"],
    recommendedActions: ["Present seasonal billing option", "Lock in Q4 peak rates early"],
    suggestedServices: [],
    suggestedTerms: ["12-month with seasonal flex billing"],
    currentPackage: "Meta Ads + Content",
    recommendedPackage: "Meta Ads (Seasonal Flex) + Content",
    revenueDifference: -300,
    serviceChanges: ["Seasonal Meta Ads budget flex"],
    contractTerms: "12-month, seasonal flex billing",
    expectedImpact: "Retains SMB client with cash-flow-friendly structure",
    lastContactDays: 3,
    openInvoices: 1,
    delayedDeliverables: 0,
    callSentiment: "Neutral",
    reportingStatus: "Current",
    projectStatus: "On Track",
  },

  // ── 23 ────────────────────────────────────────────────────────────────────
  {
    id: "ren-023",
    client: "Redwood Analytics",
    accountManager: "James Carter",
    contract: "CTR-2022-311",
    mrr: 13500,
    arr: 162000,
    renewalDate: "2025-08-18",
    daysUntilRenewal: daysFromNow("2025-08-18"),
    status: "Proposal In Progress",
    risk: "Low Risk",
    strategy: "Renew With Upgrade",
    score: computeRenewalScore({ clientHealth: 91, projectHealth: 89, communicationHealth: 92, billingHealth: 100, callIntelligence: 88, reportingHealth: 93, clientEngagement: 90 }),
    services: ["SEO", "Google Ads", "Content", "Reporting", "Data Analytics"],
    industry: "Analytics / Tech",
    clientSince: "2022-08-18",
    renewalHistory: 2,
    openIssues: 0,
    openEscalations: 0,
    recentChangeRequests: 1,
    renewalProbability: 95,
    riskFactors: [],
    growthOpportunities: ["Add LinkedIn Ads for enterprise targeting", "Expand analytics retainer"],
    clientConcerns: [],
    recommendedActions: ["Present enterprise upgrade proposal", "Lock in 24-month deal"],
    suggestedServices: ["LinkedIn Ads", "Analytics Retainer Expansion"],
    suggestedTerms: ["24-month locked rate with senior team assignment"],
    currentPackage: "SEO + Google Ads + Content + Reporting + Analytics",
    recommendedPackage: "Full Suite + LinkedIn Ads + Analytics Expansion",
    revenueDifference: 5000,
    serviceChanges: ["Add LinkedIn Ads", "Expand Analytics Retainer"],
    contractTerms: "24-month, senior team, locked rate",
    expectedImpact: "Enterprise strategic partnership at $222K ARR",
    lastContactDays: 2,
    openInvoices: 0,
    delayedDeliverables: 0,
    callSentiment: "Positive",
    reportingStatus: "Current",
    projectStatus: "On Track",
  },

  // ── 24 ────────────────────────────────────────────────────────────────────
  {
    id: "ren-024",
    client: "Forest Hill Dentistry",
    accountManager: "Rachel Torres",
    contract: "CTR-2023-080",
    mrr: 2200,
    arr: 26400,
    renewalDate: "2025-09-28",
    daysUntilRenewal: daysFromNow("2025-09-28"),
    status: "Not Started",
    risk: "Low Risk",
    strategy: "Renew As-Is",
    score: computeRenewalScore({ clientHealth: 83, projectHealth: 81, communicationHealth: 85, billingHealth: 100, callIntelligence: 79, reportingHealth: 84, clientEngagement: 82 }),
    services: ["Google Ads", "SEO"],
    industry: "Healthcare / Dental",
    clientSince: "2023-09-28",
    renewalHistory: 0,
    openIssues: 0,
    openEscalations: 0,
    recentChangeRequests: 0,
    renewalProbability: 87,
    riskFactors: ["First renewal cycle"],
    growthOpportunities: ["Add Reputation Management", "Add Patient Email Campaigns"],
    clientConcerns: [],
    recommendedActions: ["Initiate renewal conversation at 90 days"],
    suggestedServices: ["Reputation Management", "Patient Email Campaigns"],
    suggestedTerms: ["12-month at current rate with loyalty benefit"],
    currentPackage: "Google Ads + SEO",
    recommendedPackage: "Google Ads + SEO",
    revenueDifference: 0,
    serviceChanges: [],
    contractTerms: "12-month, loyalty rate",
    expectedImpact: "Stable local practice retention",
    lastContactDays: 11,
    openInvoices: 0,
    delayedDeliverables: 0,
    callSentiment: "Positive",
    reportingStatus: "Current",
    projectStatus: "On Track",
  },

  // ── 25 ────────────────────────────────────────────────────────────────────
  {
    id: "ren-025",
    client: "Sterling Insurance Group",
    accountManager: "Sarah Mitchell",
    contract: "CTR-2021-055",
    mrr: 10800,
    arr: 129600,
    renewalDate: "2025-07-15",
    daysUntilRenewal: daysFromNow("2025-07-15"),
    status: "Renewed",
    risk: "Low Risk",
    strategy: "Renew As-Is",
    score: computeRenewalScore({ clientHealth: 94, projectHealth: 93, communicationHealth: 95, billingHealth: 100, callIntelligence: 91, reportingHealth: 95, clientEngagement: 94 }),
    services: ["SEO", "Google Ads", "Content", "Email Marketing", "Reporting"],
    industry: "Insurance",
    clientSince: "2021-07-15",
    renewalHistory: 4,
    openIssues: 0,
    openEscalations: 0,
    recentChangeRequests: 0,
    renewalProbability: 99,
    riskFactors: [],
    growthOpportunities: ["Add LinkedIn Ads for commercial insurance line"],
    clientConcerns: [],
    recommendedActions: ["Confirm billing active", "Schedule annual review"],
    suggestedServices: ["LinkedIn Ads"],
    suggestedTerms: ["24-month loyal client rate"],
    currentPackage: "Full Service Package",
    recommendedPackage: "Full Service Package",
    revenueDifference: 0,
    serviceChanges: [],
    contractTerms: "24-month, loyal client rate",
    expectedImpact: "Flagship account, 4th consecutive renewal",
    lastContactDays: 1,
    openInvoices: 0,
    delayedDeliverables: 0,
    callSentiment: "Positive",
    reportingStatus: "Current",
    projectStatus: "On Track",
  },

  // ── 26 ────────────────────────────────────────────────────────────────────
  {
    id: "ren-026",
    client: "Metro Pet Supply",
    accountManager: "James Carter",
    contract: "CTR-2023-098",
    mrr: 1900,
    arr: 22800,
    renewalDate: "2025-10-05",
    daysUntilRenewal: daysFromNow("2025-10-05"),
    status: "Not Started",
    risk: "Moderate Risk",
    strategy: "Renew With Budget Adjustment",
    score: computeRenewalScore({ clientHealth: 58, projectHealth: 56, communicationHealth: 60, billingHealth: 70, callIntelligence: 55, reportingHealth: 58, clientEngagement: 50 }),
    services: ["Meta Ads"],
    industry: "Retail / Pet",
    clientSince: "2023-10-05",
    renewalHistory: 0,
    openIssues: 1,
    openEscalations: 0,
    recentChangeRequests: 1,
    renewalProbability: 60,
    riskFactors: ["Small budget constraints", "Single-service reliance", "Low engagement score"],
    growthOpportunities: ["Add SEO for organic growth"],
    clientConcerns: ["ROI justification at small budget"],
    recommendedActions: ["Present ROI report for year 1", "Offer entry-level SEO add-on"],
    suggestedServices: ["SEO Starter"],
    suggestedTerms: ["12-month, retain current rate"],
    currentPackage: "Meta Ads",
    recommendedPackage: "Meta Ads + SEO Starter",
    revenueDifference: 600,
    serviceChanges: ["Add SEO Starter"],
    contractTerms: "12-month, current rate",
    expectedImpact: "Organic + paid dual-channel for better SMB retention",
    lastContactDays: 14,
    openInvoices: 0,
    delayedDeliverables: 1,
    callSentiment: "Neutral",
    reportingStatus: "Current",
    projectStatus: "Monitor",
  },

  // ── 27 ────────────────────────────────────────────────────────────────────
  {
    id: "ren-027",
    client: "Arcadia Wealth Management",
    accountManager: "Rachel Torres",
    contract: "CTR-2022-177",
    mrr: 7800,
    arr: 93600,
    renewalDate: "2025-08-12",
    daysUntilRenewal: daysFromNow("2025-08-12"),
    status: "Review Scheduled",
    risk: "Low Risk",
    strategy: "Renew With Upgrade",
    score: computeRenewalScore({ clientHealth: 87, projectHealth: 88, communicationHealth: 89, billingHealth: 98, callIntelligence: 84, reportingHealth: 90, clientEngagement: 86 }),
    services: ["SEO", "Google Ads", "Content"],
    industry: "Financial Services",
    clientSince: "2022-08-12",
    renewalHistory: 2,
    openIssues: 0,
    openEscalations: 0,
    recentChangeRequests: 1,
    renewalProbability: 92,
    riskFactors: [],
    growthOpportunities: ["Add LinkedIn Ads for HNW targeting", "Add Email Marketing for client nurture"],
    clientConcerns: [],
    recommendedActions: ["Present LinkedIn upgrade", "Frame email as HNW nurture tool"],
    suggestedServices: ["LinkedIn Ads", "Email Marketing (HNW Nurture)"],
    suggestedTerms: ["12-month with upgrade bundle discount"],
    currentPackage: "SEO + Google Ads + Content",
    recommendedPackage: "SEO + Google Ads + Content + LinkedIn + Email",
    revenueDifference: 2600,
    serviceChanges: ["Add LinkedIn Ads", "Add Email Marketing"],
    contractTerms: "12-month, upgrade bundle discount 8%",
    expectedImpact: "Full wealth management digital strategy at $121K ARR",
    lastContactDays: 5,
    openInvoices: 0,
    delayedDeliverables: 0,
    callSentiment: "Positive",
    reportingStatus: "Current",
    projectStatus: "On Track",
  },

  // ── 28 ────────────────────────────────────────────────────────────────────
  {
    id: "ren-028",
    client: "Clearview Optometry",
    accountManager: "Sarah Mitchell",
    contract: "CTR-2023-055",
    mrr: 2100,
    arr: 25200,
    renewalDate: "2025-07-25",
    daysUntilRenewal: daysFromNow("2025-07-25"),
    status: "Proposal In Progress",
    risk: "Low Risk",
    strategy: "Renew As-Is",
    score: computeRenewalScore({ clientHealth: 79, projectHealth: 80, communicationHealth: 81, billingHealth: 95, callIntelligence: 76, reportingHealth: 80, clientEngagement: 78 }),
    services: ["Google Ads", "SEO"],
    industry: "Healthcare / Vision",
    clientSince: "2023-07-25",
    renewalHistory: 1,
    openIssues: 0,
    openEscalations: 0,
    recentChangeRequests: 0,
    renewalProbability: 84,
    riskFactors: ["Second location opening may shift strategy"],
    growthOpportunities: ["Expand campaigns for second location"],
    clientConcerns: ["Second location campaign strategy"],
    recommendedActions: ["Present multi-location campaign structure", "Propose expanded scope for location 2"],
    suggestedServices: ["Multi-location SEO", "Expanded Google Ads"],
    suggestedTerms: ["12-month with multi-location expansion tier"],
    currentPackage: "Google Ads + SEO",
    recommendedPackage: "Google Ads (Multi-Location) + SEO (Multi-Location)",
    revenueDifference: 1200,
    serviceChanges: ["Expand to second location coverage"],
    contractTerms: "12-month, multi-location structure",
    expectedImpact: "Revenue grows with client's physical expansion",
    lastContactDays: 4,
    openInvoices: 0,
    delayedDeliverables: 0,
    callSentiment: "Positive",
    reportingStatus: "Current",
    projectStatus: "On Track",
  },

  // ── 29 ────────────────────────────────────────────────────────────────────
  {
    id: "ren-029",
    client: "Thunderbolt Sporting Goods",
    accountManager: "James Carter",
    contract: "CTR-2022-289",
    mrr: 5800,
    arr: 69600,
    renewalDate: "2025-09-08",
    daysUntilRenewal: daysFromNow("2025-09-08"),
    status: "Planning",
    risk: "Moderate Risk",
    strategy: "Renew With Service Changes",
    score: computeRenewalScore({ clientHealth: 61, projectHealth: 63, communicationHealth: 67, billingHealth: 78, callIntelligence: 60, reportingHealth: 65, clientEngagement: 58 }),
    services: ["Google Ads", "Meta Ads", "Content"],
    industry: "Sporting Goods / Retail",
    clientSince: "2022-09-08",
    renewalHistory: 2,
    openIssues: 2,
    openEscalations: 0,
    recentChangeRequests: 3,
    renewalProbability: 66,
    riskFactors: ["Seasonal revenue pressure", "3 recent change requests indicate misalignment", "2 open issues"],
    growthOpportunities: ["Add Email Marketing for loyalty program"],
    clientConcerns: ["Content output not matching brand tone", "Wants more video content"],
    recommendedActions: ["Service audit — align content to brand voice", "Add video content pilot"],
    suggestedServices: ["Video Content Package", "Email Marketing (Loyalty)"],
    suggestedTerms: ["12-month with content realignment SLA"],
    currentPackage: "Google Ads + Meta Ads + Content",
    recommendedPackage: "Google Ads + Meta Ads + Content (Realigned) + Video",
    revenueDifference: 1400,
    serviceChanges: ["Realign Content strategy", "Add Video Content pilot"],
    contractTerms: "12-month, content SLA, brand tone guarantee",
    expectedImpact: "Improved brand alignment reduces churn risk and opens video upsell",
    lastContactDays: 7,
    openInvoices: 0,
    delayedDeliverables: 1,
    callSentiment: "Mixed",
    reportingStatus: "Current",
    projectStatus: "Monitor",
  },

  // ── 30 ────────────────────────────────────────────────────────────────────
  {
    id: "ren-030",
    client: "EastCoast Plumbing Services",
    accountManager: "Rachel Torres",
    contract: "CTR-2022-322",
    mrr: 3100,
    arr: 37200,
    renewalDate: "2025-07-20",
    daysUntilRenewal: daysFromNow("2025-07-20"),
    status: "Cancelled",
    risk: "Critical",
    strategy: "Executive Intervention Required",
    score: computeRenewalScore({ clientHealth: 30, projectHealth: 35, communicationHealth: 28, billingHealth: 50, callIntelligence: 32, reportingHealth: 40, clientEngagement: 22 }),
    services: ["Google Ads", "SEO"],
    industry: "Home Services",
    clientSince: "2022-07-20",
    renewalHistory: 2,
    openIssues: 4,
    openEscalations: 2,
    recentChangeRequests: 4,
    renewalProbability: 12,
    riskFactors: ["2 unresolved escalations", "4 open issues", "Communication dropped 25+ days", "Client signed with competitor"],
    growthOpportunities: [],
    clientConcerns: ["Campaign performance", "Communication gaps", "Report inconsistency"],
    recommendedActions: ["Post-mortem analysis", "Extract lessons for SMB service improvements", "Initiate offboarding"],
    suggestedServices: [],
    suggestedTerms: [],
    currentPackage: "Google Ads + SEO",
    recommendedPackage: "N/A — Cancelled",
    revenueDifference: -37200,
    serviceChanges: [],
    contractTerms: "N/A",
    expectedImpact: "Revenue lost: $37,200/yr. Post-mortem scheduled.",
    lastContactDays: 25,
    openInvoices: 2,
    delayedDeliverables: 3,
    callSentiment: "Negative",
    reportingStatus: "Overdue",
    projectStatus: "Blocked",
  },
];

// ══════════════════════════════════════════════════════════════════════════════
// DERIVED HELPERS
// ══════════════════════════════════════════════════════════════════════════════

export function getRenewalsByDaysWindow(days: number): RenewalRecord[] {
  return RENEWALS.filter((r) => r.daysUntilRenewal > 0 && r.daysUntilRenewal <= days);
}

export function getAtRiskRenewals(): RenewalRecord[] {
  return RENEWALS.filter((r) => r.risk === "High Risk"|| r.risk === "Critical");
}

export function getActiveRenewals(): RenewalRecord[] {
  return RENEWALS.filter((r) => r.status !== "Renewed"&& r.status !== "Lost"&& r.status !== "Cancelled");
}

export function computeRevenueSummary() {
  const total = RENEWALS.reduce((s, r) => s + r.arr, 0);
  const atRisk = getAtRiskRenewals().reduce((s, r) => s + r.arr, 0);
  const lost = RENEWALS.filter((r) => r.status === "Lost"|| r.status === "Cancelled").reduce((s, r) => s + r.arr, 0);
  const renewed = RENEWALS.filter((r) => r.status === "Renewed").reduce((s, r) => s + r.arr, 0);
  const forecast = getActiveRenewals().reduce((s, r) => s + Math.round(r.arr * (r.renewalProbability / 100)), 0);
  return { total, atRisk, lost, renewed, forecast };
}
