import type {
  ActivationRecord,
  LaunchRecord,
  AILaunchSummary,
  ActivationAnalytics,
} from "@/types/activation";

// ── 20 Activation Records ─────────────────────────────────────────────────────

export const ACTIVATION_RECORDS: ActivationRecord[] = [
  {
    id: "ACT-001",
    client: "Greenfield Dental Group",
    contractNumber: "CTR-2024-0891",
    proposalId: "PROP-2024-0441",
    revenue: 4800,
    servicesSold: ["SEO", "GBP"],
    departmentsInvolved: ["SEO", "GBP", "Account Management"],
    assignedAM: "Marcus Rivera",
    activationStatus: "Active",
    launchDate: "2025-01-15",
    checklist: [
      { key: "verify_contract",      label: "Verify Contract",             completed: true },
      { key: "verify_payment",       label: "Verify Payment",              completed: true },
      { key: "assign_am",            label: "Assign Account Manager",      completed: true },
      { key: "create_projects",      label: "Create Projects",             completed: true },
      { key: "assign_departments",   label: "Assign Departments",          completed: true },
      { key: "blueprints",           label: "Generate Task Blueprints",    completed: true },
      { key: "milestones",           label: "Create Milestones",           completed: true },
      { key: "deliverables",         label: "Create Deliverables",         completed: true },
      { key: "notifications",        label: "Send Internal Notifications", completed: true },
    ],
    salesHandoff: {
      salesOwner: "Tyler Owens",
      servicesSold: ["SEO", "GBP"],
      lineItems: ["Local SEO - 12 mo", "GBP Optimization", "Citation Building"],
      budget: 4800,
      clientGoals: "Increase organic local traffic by 40% in 6 months and improve map pack ranking.",
      clientConcerns: "Previous agency did not provide transparent reporting.",
      specialRequirements: "Monthly reporting calls required.",
      proposalNotes: "Signed standard 12-month agreement. No custom terms.",
      communicationSummary: "4 discovery calls. Very engaged prospect. Prefers Slack.",
    },
    billingHandoff: {
      billingOwner: "Sandra Kim",
      contractStatus: "Signed",
      invoiceStatus: "Paid",
      paymentStatus: "Confirmed",
      billingNotes: "ACH autopay enrolled. First invoice paid day 1.",
      recurringRevenue: 4800,
    },
    amAssignment: {
      primaryAM: "Marcus Rivera",
      secondaryAM: "Lisa Tran",
      executiveSponsor: "James Patel",
    },
    projectGeneration: {
      projectsCreated: 2,
      departmentsAssigned: ["SEO", "GBP"],
      taskBlueprintsGenerated: 14,
      milestonesGenerated: 6,
      dependenciesGenerated: 8,
    },
    launchNotes: "Smooth launch. Client briefed and on-boarded without issues.",
    clientExpectations: "Expects first ranking improvements within 60 days.",
    scopeNotes: "Local SEO for 3 locations. GBP for primary location only.",
    deliverables: [
      "Monthly SEO Report",
      "GBP Posting Calendar",
      "Citation Audit",
      "Keyword Rank Report",
    ],
  },

  {
    id: "ACT-002",
    client: "Summit Auto Repair",
    contractNumber: "CTR-2024-0892",
    proposalId: "PROP-2024-0442",
    revenue: 7200,
    servicesSold: ["PPC", "SEO"],
    departmentsInvolved: ["Paid Advertising", "SEO", "Account Management"],
    assignedAM: "Jessica Moore",
    activationStatus: "Launching",
    launchDate: "2025-02-01",
    checklist: [
      { key: "verify_contract",    label: "Verify Contract",             completed: true },
      { key: "verify_payment",     label: "Verify Payment",              completed: true },
      { key: "assign_am",          label: "Assign Account Manager",      completed: true },
      { key: "create_projects",    label: "Create Projects",             completed: true },
      { key: "assign_departments", label: "Assign Departments",          completed: true },
      { key: "blueprints",         label: "Generate Task Blueprints",    completed: true },
      { key: "milestones",         label: "Create Milestones",           completed: false },
      { key: "deliverables",       label: "Create Deliverables",         completed: false },
      { key: "notifications",      label: "Send Internal Notifications", completed: false },
    ],
    salesHandoff: {
      salesOwner: "Tyler Owens",
      servicesSold: ["PPC", "SEO"],
      lineItems: ["Google Ads Management", "SEO Foundational", "Landing Page Optimization"],
      budget: 7200,
      clientGoals: "Drive 80+ qualified calls per month via Google Ads and increase organic visibility.",
      clientConcerns: "Past PPC campaigns wasted spend. Wants tight negative keyword management.",
      specialRequirements: "Bi-weekly PPC performance calls.",
      proposalNotes: "Custom proposal with tiered ad spend management.",
      communicationSummary: "3 calls. Closed after competitive presentation.",
    },
    billingHandoff: {
      billingOwner: "Sandra Kim",
      contractStatus: "Signed",
      invoiceStatus: "Paid",
      paymentStatus: "Confirmed",
      billingNotes: "Credit card on file. Auto-charge active.",
      recurringRevenue: 7200,
    },
    amAssignment: {
      primaryAM: "Jessica Moore",
      secondaryAM: null,
      executiveSponsor: "James Patel",
    },
    projectGeneration: {
      projectsCreated: 2,
      departmentsAssigned: ["Paid Advertising", "SEO"],
      taskBlueprintsGenerated: 18,
      milestonesGenerated: 7,
      dependenciesGenerated: 10,
    },
    launchNotes: "PPC campaign setup in progress. SEO audit complete.",
    clientExpectations: "Expects ads live within 5 business days.",
    scopeNotes: "Google Search + Display. National geo-targeting excluded.",
    deliverables: [
      "Google Ads Campaign Setup",
      "Weekly PPC Report",
      "SEO Monthly Report",
      "Landing Page Wireframe",
    ],
  },

  {
    id: "ACT-003",
    client: "Harbor Light Legal",
    contractNumber: "CTR-2024-0893",
    proposalId: "PROP-2024-0443",
    revenue: 12500,
    servicesSold: ["Web Development", "SEO", "PPC"],
    departmentsInvolved: ["Web Development", "SEO", "Paid Advertising", "Account Management"],
    assignedAM: "Marcus Rivera",
    activationStatus: "Ready For Launch",
    launchDate: "2025-02-10",
    checklist: [
      { key: "verify_contract",    label: "Verify Contract",             completed: true },
      { key: "verify_payment",     label: "Verify Payment",              completed: true },
      { key: "assign_am",          label: "Assign Account Manager",      completed: true },
      { key: "create_projects",    label: "Create Projects",             completed: true },
      { key: "assign_departments", label: "Assign Departments",          completed: true },
      { key: "blueprints",         label: "Generate Task Blueprints",    completed: true },
      { key: "milestones",         label: "Create Milestones",           completed: true },
      { key: "deliverables",       label: "Create Deliverables",         completed: true },
      { key: "notifications",      label: "Send Internal Notifications", completed: false },
    ],
    salesHandoff: {
      salesOwner: "Danielle Ford",
      servicesSold: ["Web Development", "SEO", "PPC"],
      lineItems: ["Website Redesign", "SEO Foundational", "Google Ads - Legal"],
      budget: 12500,
      clientGoals: "New website and digital marketing engine to support firm growth.",
      clientConcerns: "Current site is outdated. Competitors outranking them.",
      specialRequirements: "ADA compliance required. Brand guide provided.",
      proposalNotes: "Phase 1: Website. Phase 2: SEO + PPC activation post-launch.",
      communicationSummary: "5 calls with Managing Partner. Very detailed requirements.",
    },
    billingHandoff: {
      billingOwner: "Kevin Lam",
      contractStatus: "Signed",
      invoiceStatus: "Paid",
      paymentStatus: "Confirmed",
      billingNotes: "50% upfront paid. Remainder on website launch.",
      recurringRevenue: 4800,
    },
    amAssignment: {
      primaryAM: "Marcus Rivera",
      secondaryAM: "Rachel Ng",
      executiveSponsor: "James Patel",
    },
    projectGeneration: {
      projectsCreated: 3,
      departmentsAssigned: ["Web Development", "SEO", "Paid Advertising"],
      taskBlueprintsGenerated: 28,
      milestonesGenerated: 12,
      dependenciesGenerated: 18,
    },
    launchNotes: "Website in final QA. Awaiting internal notifications before launch.",
    clientExpectations: "Website live by Feb 10. SEO and ads to follow within 2 weeks.",
    scopeNotes: "12-page WordPress site. SEO limited to practice areas + city pages.",
    deliverables: [
      "Website Redesign",
      "ADA Compliance Report",
      "SEO Audit",
      "PPC Campaign Structure",
      "Monthly Performance Report",
    ],
  },

  {
    id: "ACT-004",
    client: "Coastal Plumbing Co.",
    contractNumber: "CTR-2024-0894",
    proposalId: "PROP-2024-0444",
    revenue: 3600,
    servicesSold: ["GBP", "Hosting"],
    departmentsInvolved: ["GBP", "IT / Hosting", "Account Management"],
    assignedAM: "Rachel Ng",
    activationStatus: "Pending Payment",
    launchDate: "2025-02-20",
    checklist: [
      { key: "verify_contract",    label: "Verify Contract",             completed: true },
      { key: "verify_payment",     label: "Verify Payment",              completed: false },
      { key: "assign_am",          label: "Assign Account Manager",      completed: false },
      { key: "create_projects",    label: "Create Projects",             completed: false },
      { key: "assign_departments", label: "Assign Departments",          completed: false },
      { key: "blueprints",         label: "Generate Task Blueprints",    completed: false },
      { key: "milestones",         label: "Create Milestones",           completed: false },
      { key: "deliverables",       label: "Create Deliverables",         completed: false },
      { key: "notifications",      label: "Send Internal Notifications", completed: false },
    ],
    salesHandoff: {
      salesOwner: "Tyler Owens",
      servicesSold: ["GBP", "Hosting"],
      lineItems: ["GBP Management Monthly", "Managed WordPress Hosting"],
      budget: 3600,
      clientGoals: "Improve Google Maps visibility and get reliable hosting.",
      clientConcerns: "Current host goes down frequently.",
      specialRequirements: "None",
      proposalNotes: "Month-to-month after initial 3-month commitment.",
      communicationSummary: "2 calls. Quick close.",
    },
    billingHandoff: {
      billingOwner: "Sandra Kim",
      contractStatus: "Signed",
      invoiceStatus: "Sent",
      paymentStatus: "Awaiting",
      billingNotes: "Invoice #2241 sent Jan 20. Payment due Jan 30. Follow up needed.",
      recurringRevenue: 3600,
    },
    amAssignment: {
      primaryAM: "Rachel Ng",
      secondaryAM: null,
      executiveSponsor: null,
    },
    projectGeneration: {
      projectsCreated: 0,
      departmentsAssigned: [],
      taskBlueprintsGenerated: 0,
      milestonesGenerated: 0,
      dependenciesGenerated: 0,
    },
    launchNotes: "Blocked by pending payment. Billing team following up.",
    clientExpectations: "Expects fast GBP setup once payment clears.",
    scopeNotes: "Single GBP location. Shared hosting plan.",
    deliverables: ["GBP Monthly Report", "Hosting Uptime Dashboard"],
  },

  {
    id: "ACT-005",
    client: "Nexus Digital Agency",
    contractNumber: "CTR-2025-0001",
    proposalId: "PROP-2025-0001",
    revenue: 18000,
    servicesSold: ["AI Automation", "Web Development"],
    departmentsInvolved: ["AI Automation", "Web Development", "Account Management"],
    assignedAM: "Jessica Moore",
    activationStatus: "Pending Assignment",
    launchDate: "2025-03-01",
    checklist: [
      { key: "verify_contract",    label: "Verify Contract",             completed: true },
      { key: "verify_payment",     label: "Verify Payment",              completed: true },
      { key: "assign_am",          label: "Assign Account Manager",      completed: false },
      { key: "create_projects",    label: "Create Projects",             completed: false },
      { key: "assign_departments", label: "Assign Departments",          completed: false },
      { key: "blueprints",         label: "Generate Task Blueprints",    completed: false },
      { key: "milestones",         label: "Create Milestones",           completed: false },
      { key: "deliverables",       label: "Create Deliverables",         completed: false },
      { key: "notifications",      label: "Send Internal Notifications", completed: false },
    ],
    salesHandoff: {
      salesOwner: "Danielle Ford",
      servicesSold: ["AI Automation", "Web Development"],
      lineItems: ["AI Chat + Lead Routing", "CRM Integration", "Custom Dashboard Build"],
      budget: 18000,
      clientGoals: "Automate lead qualification and integrate CRM with AI assistant.",
      clientConcerns: "Complex integrations. Needs clear project timeline.",
      specialRequirements: "Salesforce CRM integration required.",
      proposalNotes: "Statement of work attached. Milestone-based billing.",
      communicationSummary: "7 calls with CTO and VP Marketing.",
    },
    billingHandoff: {
      billingOwner: "Kevin Lam",
      contractStatus: "Signed",
      invoiceStatus: "Paid",
      paymentStatus: "Confirmed",
      billingNotes: "Milestone 1 payment received. Milestone 2 due on delivery.",
      recurringRevenue: 0,
    },
    amAssignment: {
      primaryAM: "Jessica Moore",
      secondaryAM: null,
      executiveSponsor: "James Patel",
    },
    projectGeneration: {
      projectsCreated: 0,
      departmentsAssigned: [],
      taskBlueprintsGenerated: 0,
      milestonesGenerated: 0,
      dependenciesGenerated: 0,
    },
    launchNotes: "Awaiting AM assignment before project creation can begin.",
    clientExpectations: "Full project kickoff by March 1. CTO expects detailed Gantt chart.",
    scopeNotes: "Phase 1: AI chat + lead routing. Phase 2: Dashboard.",
    deliverables: [
      "AI Chat Widget",
      "Lead Routing Workflow",
      "CRM Integration",
      "Custom Analytics Dashboard",
      "Training Documentation",
    ],
  },

  {
    id: "ACT-006",
    client: "Blue Ridge Roofing",
    contractNumber: "CTR-2024-0895",
    proposalId: "PROP-2024-0445",
    revenue: 5400,
    servicesSold: ["SEO", "GBP"],
    departmentsInvolved: ["SEO", "GBP", "Account Management"],
    assignedAM: "Marcus Rivera",
    activationStatus: "Active",
    launchDate: "2024-12-10",
    checklist: [
      { key: "verify_contract",    label: "Verify Contract",             completed: true },
      { key: "verify_payment",     label: "Verify Payment",              completed: true },
      { key: "assign_am",          label: "Assign Account Manager",      completed: true },
      { key: "create_projects",    label: "Create Projects",             completed: true },
      { key: "assign_departments", label: "Assign Departments",          completed: true },
      { key: "blueprints",         label: "Generate Task Blueprints",    completed: true },
      { key: "milestones",         label: "Create Milestones",           completed: true },
      { key: "deliverables",       label: "Create Deliverables",         completed: true },
      { key: "notifications",      label: "Send Internal Notifications", completed: true },
    ],
    salesHandoff: {
      salesOwner: "Tyler Owens",
      servicesSold: ["SEO", "GBP"],
      lineItems: ["Local SEO - 12 mo", "GBP Management"],
      budget: 5400,
      clientGoals: "Dominate local search for roofing in 3 service cities.",
      clientConcerns: "Competitor has strong GBP presence.",
      specialRequirements: "Seasonal campaign emphasis April-September.",
      proposalNotes: "12-month agreement. Auto-renewal clause.",
      communicationSummary: "2 calls. Referred by existing client.",
    },
    billingHandoff: {
      billingOwner: "Sandra Kim",
      contractStatus: "Signed",
      invoiceStatus: "Paid",
      paymentStatus: "Confirmed",
      billingNotes: "Auto-pay active.",
      recurringRevenue: 5400,
    },
    amAssignment: {
      primaryAM: "Marcus Rivera",
      secondaryAM: "Lisa Tran",
      executiveSponsor: null,
    },
    projectGeneration: {
      projectsCreated: 2,
      departmentsAssigned: ["SEO", "GBP"],
      taskBlueprintsGenerated: 12,
      milestonesGenerated: 5,
      dependenciesGenerated: 7,
    },
    launchNotes: "Fully active. Month 2 complete.",
    clientExpectations: "First monthly report showed positive ranking movement.",
    scopeNotes: "3-city local SEO. GBP for primary business location.",
    deliverables: ["Monthly SEO Report", "GBP Activity Log", "Citation Report"],
  },

  {
    id: "ACT-007",
    client: "TechForge Solutions",
    contractNumber: "CTR-2025-0002",
    proposalId: "PROP-2025-0002",
    revenue: 9600,
    servicesSold: ["PPC", "AI Automation"],
    departmentsInvolved: ["Paid Advertising", "AI Automation", "Account Management"],
    assignedAM: "Rachel Ng",
    activationStatus: "On Hold",
    launchDate: "2025-02-28",
    checklist: [
      { key: "verify_contract",    label: "Verify Contract",             completed: true },
      { key: "verify_payment",     label: "Verify Payment",              completed: false },
      { key: "assign_am",          label: "Assign Account Manager",      completed: true },
      { key: "create_projects",    label: "Create Projects",             completed: false },
      { key: "assign_departments", label: "Assign Departments",          completed: false },
      { key: "blueprints",         label: "Generate Task Blueprints",    completed: false },
      { key: "milestones",         label: "Create Milestones",           completed: false },
      { key: "deliverables",       label: "Create Deliverables",         completed: false },
      { key: "notifications",      label: "Send Internal Notifications", completed: false },
    ],
    salesHandoff: {
      salesOwner: "Danielle Ford",
      servicesSold: ["PPC", "AI Automation"],
      lineItems: ["Google Ads", "Microsoft Ads", "AI Lead Scoring Bot"],
      budget: 9600,
      clientGoals: "Scale B2B lead gen with AI-augmented PPC.",
      clientConcerns: "Budget freeze in Q1. May reduce scope.",
      specialRequirements: "LinkedIn integration for B2B targeting.",
      proposalNotes: "Hold placed by client due to internal budget review.",
      communicationSummary: "4 calls. Procurement delay on client side.",
    },
    billingHandoff: {
      billingOwner: "Kevin Lam",
      contractStatus: "Signed",
      invoiceStatus: "Not Sent",
      paymentStatus: "Awaiting",
      billingNotes: "Billing on hold per client request. Resume after Feb 15.",
      recurringRevenue: 9600,
    },
    amAssignment: {
      primaryAM: "Rachel Ng",
      secondaryAM: null,
      executiveSponsor: "James Patel",
    },
    projectGeneration: {
      projectsCreated: 0,
      departmentsAssigned: [],
      taskBlueprintsGenerated: 0,
      milestonesGenerated: 0,
      dependenciesGenerated: 0,
    },
    launchNotes: "Client requested hold. Revisiting scope Feb 15.",
    clientExpectations: "Will confirm go/no-go after internal budget meeting.",
    scopeNotes: "Pending. Budget may be reduced.",
    deliverables: ["PPC Campaign Package", "AI Lead Scoring Workflow"],
  },

  {
    id: "ACT-008",
    client: "Prestige Med Spa",
    contractNumber: "CTR-2025-0003",
    proposalId: "PROP-2025-0003",
    revenue: 6000,
    servicesSold: ["SEO", "PPC"],
    departmentsInvolved: ["SEO", "Paid Advertising", "Account Management"],
    assignedAM: "Jessica Moore",
    activationStatus: "Launching",
    launchDate: "2025-02-05",
    checklist: [
      { key: "verify_contract",    label: "Verify Contract",             completed: true },
      { key: "verify_payment",     label: "Verify Payment",              completed: true },
      { key: "assign_am",          label: "Assign Account Manager",      completed: true },
      { key: "create_projects",    label: "Create Projects",             completed: true },
      { key: "assign_departments", label: "Assign Departments",          completed: true },
      { key: "blueprints",         label: "Generate Task Blueprints",    completed: true },
      { key: "milestones",         label: "Create Milestones",           completed: true },
      { key: "deliverables",       label: "Create Deliverables",         completed: false },
      { key: "notifications",      label: "Send Internal Notifications", completed: false },
    ],
    salesHandoff: {
      salesOwner: "Tyler Owens",
      servicesSold: ["SEO", "PPC"],
      lineItems: ["Local SEO", "Instagram Ads", "Google Search Ads"],
      budget: 6000,
      clientGoals: "Fill appointment calendar. Target high-value procedures.",
      clientConcerns: "HIPAA-adjacent concerns. No patient data in ads.",
      specialRequirements: "Sensitive category compliance for medical advertising.",
      proposalNotes: "Custom creative strategy required for compliance.",
      communicationSummary: "3 calls with owner and office manager.",
    },
    billingHandoff: {
      billingOwner: "Sandra Kim",
      contractStatus: "Signed",
      invoiceStatus: "Paid",
      paymentStatus: "Confirmed",
      billingNotes: "First invoice paid. Monthly auto-charge set.",
      recurringRevenue: 6000,
    },
    amAssignment: {
      primaryAM: "Jessica Moore",
      secondaryAM: "Rachel Ng",
      executiveSponsor: null,
    },
    projectGeneration: {
      projectsCreated: 2,
      departmentsAssigned: ["SEO", "Paid Advertising"],
      taskBlueprintsGenerated: 16,
      milestonesGenerated: 7,
      dependenciesGenerated: 9,
    },
    launchNotes: "Ads in review. SEO technical audit submitted.",
    clientExpectations: "Ads approved and running by Feb 5.",
    scopeNotes: "Google + Instagram. Compliance review required per ad creative.",
    deliverables: [
      "Ad Creative Set",
      "SEO Technical Audit",
      "Compliance Checklist",
      "Monthly Performance Report",
    ],
  },

  {
    id: "ACT-009",
    client: "Grand Vista Hotels",
    contractNumber: "CTR-2025-0004",
    proposalId: "PROP-2025-0004",
    revenue: 22000,
    servicesSold: ["Web Development", "SEO", "PPC", "AI Automation"],
    departmentsInvolved: ["Web Development", "SEO", "Paid Advertising", "AI Automation", "Account Management"],
    assignedAM: "Marcus Rivera",
    activationStatus: "Pending Contract",
    launchDate: "2025-03-15",
    checklist: [
      { key: "verify_contract",    label: "Verify Contract",             completed: false },
      { key: "verify_payment",     label: "Verify Payment",              completed: false },
      { key: "assign_am",          label: "Assign Account Manager",      completed: false },
      { key: "create_projects",    label: "Create Projects",             completed: false },
      { key: "assign_departments", label: "Assign Departments",          completed: false },
      { key: "blueprints",         label: "Generate Task Blueprints",    completed: false },
      { key: "milestones",         label: "Create Milestones",           completed: false },
      { key: "deliverables",       label: "Create Deliverables",         completed: false },
      { key: "notifications",      label: "Send Internal Notifications", completed: false },
    ],
    salesHandoff: {
      salesOwner: "Danielle Ford",
      servicesSold: ["Web Development", "SEO", "PPC", "AI Automation"],
      lineItems: ["Hotel Website Redesign", "SEO - Hospitality", "Google + Meta Ads", "AI Booking Chatbot"],
      budget: 22000,
      clientGoals: "Full digital transformation. Direct bookings up 30%.",
      clientConcerns: "Long procurement cycle. Multiple approvers needed.",
      specialRequirements: "Booking engine integration required.",
      proposalNotes: "Board approval pending. Legal reviewing MSA.",
      communicationSummary: "8 calls with VP Marketing and General Manager.",
    },
    billingHandoff: {
      billingOwner: "Kevin Lam",
      contractStatus: "Pending",
      invoiceStatus: "Not Sent",
      paymentStatus: "Awaiting",
      billingNotes: "MSA in legal review. Invoice to be sent upon signing.",
      recurringRevenue: 5400,
    },
    amAssignment: {
      primaryAM: "Marcus Rivera",
      secondaryAM: "Jessica Moore",
      executiveSponsor: "James Patel",
    },
    projectGeneration: {
      projectsCreated: 0,
      departmentsAssigned: [],
      taskBlueprintsGenerated: 0,
      milestonesGenerated: 0,
      dependenciesGenerated: 0,
    },
    launchNotes: "Awaiting contract signature. High-value account. Prioritize once signed.",
    clientExpectations: "Expects detailed onboarding plan on signing day.",
    scopeNotes: "Full-service engagement. Largest pending contract this quarter.",
    deliverables: [
      "Hotel Website",
      "Booking Engine Integration",
      "SEO Strategy",
      "Paid Media Plan",
      "AI Chatbot",
    ],
  },

  {
    id: "ACT-010",
    client: "Clearview Optometry",
    contractNumber: "CTR-2024-0896",
    proposalId: "PROP-2024-0446",
    revenue: 3200,
    servicesSold: ["GBP", "Hosting"],
    departmentsInvolved: ["GBP", "IT / Hosting", "Account Management"],
    assignedAM: "Lisa Tran",
    activationStatus: "Active",
    launchDate: "2024-11-20",
    checklist: [
      { key: "verify_contract",    label: "Verify Contract",             completed: true },
      { key: "verify_payment",     label: "Verify Payment",              completed: true },
      { key: "assign_am",          label: "Assign Account Manager",      completed: true },
      { key: "create_projects",    label: "Create Projects",             completed: true },
      { key: "assign_departments", label: "Assign Departments",          completed: true },
      { key: "blueprints",         label: "Generate Task Blueprints",    completed: true },
      { key: "milestones",         label: "Create Milestones",           completed: true },
      { key: "deliverables",       label: "Create Deliverables",         completed: true },
      { key: "notifications",      label: "Send Internal Notifications", completed: true },
    ],
    salesHandoff: {
      salesOwner: "Tyler Owens",
      servicesSold: ["GBP", "Hosting"],
      lineItems: ["GBP Management", "Managed Hosting Premium"],
      budget: 3200,
      clientGoals: "Grow local reviews and keep website fast and secure.",
      clientConcerns: "None noted.",
      specialRequirements: "SSL managed by RTM.",
      proposalNotes: "Standard terms.",
      communicationSummary: "1 call.",
    },
    billingHandoff: {
      billingOwner: "Sandra Kim",
      contractStatus: "Signed",
      invoiceStatus: "Paid",
      paymentStatus: "Confirmed",
      billingNotes: "Month 3 active.",
      recurringRevenue: 3200,
    },
    amAssignment: {
      primaryAM: "Lisa Tran",
      secondaryAM: null,
      executiveSponsor: null,
    },
    projectGeneration: {
      projectsCreated: 2,
      departmentsAssigned: ["GBP", "IT / Hosting"],
      taskBlueprintsGenerated: 8,
      milestonesGenerated: 4,
      dependenciesGenerated: 5,
    },
    launchNotes: "Fully active and stable.",
    clientExpectations: "Satisfied client. Reviewing upsell to SEO in Q2.",
    scopeNotes: "Single location GBP. WordPress hosting.",
    deliverables: ["GBP Monthly Report", "Hosting Uptime Report"],
  },

  {
    id: "ACT-011",
    client: "Ironclad Fitness",
    contractNumber: "CTR-2025-0005",
    proposalId: "PROP-2025-0005",
    revenue: 4400,
    servicesSold: ["SEO", "GBP"],
    departmentsInvolved: ["SEO", "GBP", "Account Management"],
    assignedAM: "Rachel Ng",
    activationStatus: "Ready For Launch",
    launchDate: "2025-02-08",
    checklist: [
      { key: "verify_contract",    label: "Verify Contract",             completed: true },
      { key: "verify_payment",     label: "Verify Payment",              completed: true },
      { key: "assign_am",          label: "Assign Account Manager",      completed: true },
      { key: "create_projects",    label: "Create Projects",             completed: true },
      { key: "assign_departments", label: "Assign Departments",          completed: true },
      { key: "blueprints",         label: "Generate Task Blueprints",    completed: true },
      { key: "milestones",         label: "Create Milestones",           completed: true },
      { key: "deliverables",       label: "Create Deliverables",         completed: true },
      { key: "notifications",      label: "Send Internal Notifications", completed: false },
    ],
    salesHandoff: {
      salesOwner: "Tyler Owens",
      servicesSold: ["SEO", "GBP"],
      lineItems: ["Local SEO", "GBP Full Management"],
      budget: 4400,
      clientGoals: "Outrank competing gyms in Google Maps and organic.",
      clientConcerns: "Seasonal drop in memberships. Needs year-round visibility.",
      specialRequirements: "Review response management included.",
      proposalNotes: "Includes review strategy in scope.",
      communicationSummary: "2 calls with owner.",
    },
    billingHandoff: {
      billingOwner: "Sandra Kim",
      contractStatus: "Signed",
      invoiceStatus: "Paid",
      paymentStatus: "Confirmed",
      billingNotes: "Auto-pay active.",
      recurringRevenue: 4400,
    },
    amAssignment: {
      primaryAM: "Rachel Ng",
      secondaryAM: null,
      executiveSponsor: null,
    },
    projectGeneration: {
      projectsCreated: 2,
      departmentsAssigned: ["SEO", "GBP"],
      taskBlueprintsGenerated: 11,
      milestonesGenerated: 5,
      dependenciesGenerated: 6,
    },
    launchNotes: "Ready. Pending final internal notification send.",
    clientExpectations: "Expects launch confirmation email.",
    scopeNotes: "2 gym locations. Review management included.",
    deliverables: ["SEO Monthly Report", "GBP Activity Log", "Review Response Log"],
  },

  {
    id: "ACT-012",
    client: "Pacific Rim Trading Co.",
    contractNumber: "CTR-2025-0006",
    proposalId: "PROP-2025-0006",
    revenue: 8800,
    servicesSold: ["PPC", "Web Development"],
    departmentsInvolved: ["Paid Advertising", "Web Development", "Account Management"],
    assignedAM: "Jessica Moore",
    activationStatus: "Launching",
    launchDate: "2025-02-12",
    checklist: [
      { key: "verify_contract",    label: "Verify Contract",             completed: true },
      { key: "verify_payment",     label: "Verify Payment",              completed: true },
      { key: "assign_am",          label: "Assign Account Manager",      completed: true },
      { key: "create_projects",    label: "Create Projects",             completed: true },
      { key: "assign_departments", label: "Assign Departments",          completed: true },
      { key: "blueprints",         label: "Generate Task Blueprints",    completed: true },
      { key: "milestones",         label: "Create Milestones",           completed: false },
      { key: "deliverables",       label: "Create Deliverables",         completed: false },
      { key: "notifications",      label: "Send Internal Notifications", completed: false },
    ],
    salesHandoff: {
      salesOwner: "Danielle Ford",
      servicesSold: ["PPC", "Web Development"],
      lineItems: ["E-commerce PPC", "WooCommerce Development"],
      budget: 8800,
      clientGoals: "Launch e-commerce with paid traffic from day one.",
      clientConcerns: "Wants store ready before Chinese New Year.",
      specialRequirements: "WooCommerce with multi-currency.",
      proposalNotes: "Hard deadline: Feb 12.",
      communicationSummary: "6 calls. Deadline-sensitive.",
    },
    billingHandoff: {
      billingOwner: "Kevin Lam",
      contractStatus: "Signed",
      invoiceStatus: "Paid",
      paymentStatus: "Confirmed",
      billingNotes: "50% upfront. Remainder on store launch.",
      recurringRevenue: 3600,
    },
    amAssignment: {
      primaryAM: "Jessica Moore",
      secondaryAM: null,
      executiveSponsor: "James Patel",
    },
    projectGeneration: {
      projectsCreated: 2,
      departmentsAssigned: ["Web Development", "Paid Advertising"],
      taskBlueprintsGenerated: 20,
      milestonesGenerated: 9,
      dependenciesGenerated: 14,
    },
    launchNotes: "WooCommerce store in development. PPC campaigns ready to activate.",
    clientExpectations: "Store live Feb 12. Ads go live same day.",
    scopeNotes: "WooCommerce + 3 Google Shopping campaigns.",
    deliverables: ["WooCommerce Store", "PPC Campaign Package", "Shopping Feed Setup"],
  },

  {
    id: "ACT-013",
    client: "Westview Family Medicine",
    contractNumber: "CTR-2024-0897",
    proposalId: "PROP-2024-0447",
    revenue: 2800,
    servicesSold: ["GBP"],
    departmentsInvolved: ["GBP", "Account Management"],
    assignedAM: "Lisa Tran",
    activationStatus: "Active",
    launchDate: "2024-10-01",
    checklist: [
      { key: "verify_contract",    label: "Verify Contract",             completed: true },
      { key: "verify_payment",     label: "Verify Payment",              completed: true },
      { key: "assign_am",          label: "Assign Account Manager",      completed: true },
      { key: "create_projects",    label: "Create Projects",             completed: true },
      { key: "assign_departments", label: "Assign Departments",          completed: true },
      { key: "blueprints",         label: "Generate Task Blueprints",    completed: true },
      { key: "milestones",         label: "Create Milestones",           completed: true },
      { key: "deliverables",       label: "Create Deliverables",         completed: true },
      { key: "notifications",      label: "Send Internal Notifications", completed: true },
    ],
    salesHandoff: {
      salesOwner: "Tyler Owens",
      servicesSold: ["GBP"],
      lineItems: ["GBP Full Management"],
      budget: 2800,
      clientGoals: "5-star reputation and top map pack placement.",
      clientConcerns: "Had negative review incident in past.",
      specialRequirements: "HIPAA compliance on all review responses.",
      proposalNotes: "Sensitive industry. Review response protocol required.",
      communicationSummary: "2 calls with office manager.",
    },
    billingHandoff: {
      billingOwner: "Sandra Kim",
      contractStatus: "Signed",
      invoiceStatus: "Paid",
      paymentStatus: "Confirmed",
      billingNotes: "Month 5 active.",
      recurringRevenue: 2800,
    },
    amAssignment: {
      primaryAM: "Lisa Tran",
      secondaryAM: null,
      executiveSponsor: null,
    },
    projectGeneration: {
      projectsCreated: 1,
      departmentsAssigned: ["GBP"],
      taskBlueprintsGenerated: 6,
      milestonesGenerated: 3,
      dependenciesGenerated: 3,
    },
    launchNotes: "Active month 5. Rating improved from 3.9 to 4.6.",
    clientExpectations: "Target 4.8 rating by end of contract.",
    scopeNotes: "GBP only. Medical review sensitivity protocol active.",
    deliverables: ["Monthly GBP Report", "Review Response Log"],
  },

  {
    id: "ACT-014",
    client: "Apex Consulting Group",
    contractNumber: "CTR-2025-0007",
    proposalId: "PROP-2025-0007",
    revenue: 15000,
    servicesSold: ["AI Automation", "Web Development"],
    departmentsInvolved: ["AI Automation", "Web Development", "Account Management"],
    assignedAM: "Marcus Rivera",
    activationStatus: "Pending Contract",
    launchDate: "2025-03-20",
    checklist: [
      { key: "verify_contract",    label: "Verify Contract",             completed: false },
      { key: "verify_payment",     label: "Verify Payment",              completed: false },
      { key: "assign_am",          label: "Assign Account Manager",      completed: true },
      { key: "create_projects",    label: "Create Projects",             completed: false },
      { key: "assign_departments", label: "Assign Departments",          completed: false },
      { key: "blueprints",         label: "Generate Task Blueprints",    completed: false },
      { key: "milestones",         label: "Create Milestones",           completed: false },
      { key: "deliverables",       label: "Create Deliverables",         completed: false },
      { key: "notifications",      label: "Send Internal Notifications", completed: false },
    ],
    salesHandoff: {
      salesOwner: "Danielle Ford",
      servicesSold: ["AI Automation", "Web Development"],
      lineItems: ["AI Proposal Generator", "Consulting Portal"],
      budget: 15000,
      clientGoals: "Automate proposal generation and build client-facing portal.",
      clientConcerns: "Competitive timeline. Other vendors bidding.",
      specialRequirements: "DocuSign integration.",
      proposalNotes: "Contract being reviewed by their legal team.",
      communicationSummary: "5 calls with Managing Partner.",
    },
    billingHandoff: {
      billingOwner: "Kevin Lam",
      contractStatus: "Pending",
      invoiceStatus: "Not Sent",
      paymentStatus: "Awaiting",
      billingNotes: "Awaiting contract sign-off.",
      recurringRevenue: 0,
    },
    amAssignment: {
      primaryAM: "Marcus Rivera",
      secondaryAM: null,
      executiveSponsor: "James Patel",
    },
    projectGeneration: {
      projectsCreated: 0,
      departmentsAssigned: [],
      taskBlueprintsGenerated: 0,
      milestonesGenerated: 0,
      dependenciesGenerated: 0,
    },
    launchNotes: "Contract in legal review.",
    clientExpectations: "Fast start once signed. Portal demo expected week 1.",
    scopeNotes: "Custom AI tooling + portal. Milestone billing.",
    deliverables: ["AI Proposal Generator", "Client Portal", "Training Docs"],
  },

  {
    id: "ACT-015",
    client: "Horizon Solar",
    contractNumber: "CTR-2025-0008",
    proposalId: "PROP-2025-0008",
    revenue: 6800,
    servicesSold: ["SEO", "PPC"],
    departmentsInvolved: ["SEO", "Paid Advertising", "Account Management"],
    assignedAM: "Jessica Moore",
    activationStatus: "Ready For Launch",
    launchDate: "2025-02-15",
    checklist: [
      { key: "verify_contract",    label: "Verify Contract",             completed: true },
      { key: "verify_payment",     label: "Verify Payment",              completed: true },
      { key: "assign_am",          label: "Assign Account Manager",      completed: true },
      { key: "create_projects",    label: "Create Projects",             completed: true },
      { key: "assign_departments", label: "Assign Departments",          completed: true },
      { key: "blueprints",         label: "Generate Task Blueprints",    completed: true },
      { key: "milestones",         label: "Create Milestones",           completed: true },
      { key: "deliverables",       label: "Create Deliverables",         completed: true },
      { key: "notifications",      label: "Send Internal Notifications", completed: false },
    ],
    salesHandoff: {
      salesOwner: "Tyler Owens",
      servicesSold: ["SEO", "PPC"],
      lineItems: ["Solar SEO Package", "Google Ads - Solar Leads"],
      budget: 6800,
      clientGoals: "Generate residential solar installation leads at under $120 CPL.",
      clientConcerns: "Seasonal. Spring/summer heavy.",
      specialRequirements: "State incentive landing pages needed.",
      proposalNotes: "12-month with performance bonus clause.",
      communicationSummary: "3 calls with owner.",
    },
    billingHandoff: {
      billingOwner: "Sandra Kim",
      contractStatus: "Signed",
      invoiceStatus: "Paid",
      paymentStatus: "Confirmed",
      billingNotes: "Auto-pay active.",
      recurringRevenue: 6800,
    },
    amAssignment: {
      primaryAM: "Jessica Moore",
      secondaryAM: "Rachel Ng",
      executiveSponsor: null,
    },
    projectGeneration: {
      projectsCreated: 2,
      departmentsAssigned: ["SEO", "Paid Advertising"],
      taskBlueprintsGenerated: 14,
      milestonesGenerated: 6,
      dependenciesGenerated: 9,
    },
    launchNotes: "All systems ready. Awaiting final notification.",
    clientExpectations: "Ads live before spring season.",
    scopeNotes: "Residential solar focus. 5 state incentive pages.",
    deliverables: [
      "Solar Landing Pages",
      "Google Ads Campaign",
      "SEO Roadmap",
      "Lead Tracking Setup",
    ],
  },

  {
    id: "ACT-016",
    client: "Momentum Physical Therapy",
    contractNumber: "CTR-2024-0898",
    proposalId: "PROP-2024-0448",
    revenue: 3800,
    servicesSold: ["GBP", "SEO"],
    departmentsInvolved: ["GBP", "SEO", "Account Management"],
    assignedAM: "Lisa Tran",
    activationStatus: "Active",
    launchDate: "2024-12-01",
    checklist: [
      { key: "verify_contract",    label: "Verify Contract",             completed: true },
      { key: "verify_payment",     label: "Verify Payment",              completed: true },
      { key: "assign_am",          label: "Assign Account Manager",      completed: true },
      { key: "create_projects",    label: "Create Projects",             completed: true },
      { key: "assign_departments", label: "Assign Departments",          completed: true },
      { key: "blueprints",         label: "Generate Task Blueprints",    completed: true },
      { key: "milestones",         label: "Create Milestones",           completed: true },
      { key: "deliverables",       label: "Create Deliverables",         completed: true },
      { key: "notifications",      label: "Send Internal Notifications", completed: true },
    ],
    salesHandoff: {
      salesOwner: "Tyler Owens",
      servicesSold: ["GBP", "SEO"],
      lineItems: ["GBP Management", "Local SEO"],
      budget: 3800,
      clientGoals: "Fill PT schedule. 3 practitioners.",
      clientConcerns: "Insurance referrals declining. Direct search needed.",
      specialRequirements: "Multi-practitioner GBP strategy.",
      proposalNotes: "Standard terms.",
      communicationSummary: "2 calls with owner.",
    },
    billingHandoff: {
      billingOwner: "Sandra Kim",
      contractStatus: "Signed",
      invoiceStatus: "Paid",
      paymentStatus: "Confirmed",
      billingNotes: "Auto-pay active.",
      recurringRevenue: 3800,
    },
    amAssignment: {
      primaryAM: "Lisa Tran",
      secondaryAM: null,
      executiveSponsor: null,
    },
    projectGeneration: {
      projectsCreated: 2,
      departmentsAssigned: ["GBP", "SEO"],
      taskBlueprintsGenerated: 10,
      milestonesGenerated: 4,
      dependenciesGenerated: 6,
    },
    launchNotes: "Month 3 active. Positive trajectory.",
    clientExpectations: "Steady improvement each month.",
    scopeNotes: "2 PT clinic locations.",
    deliverables: ["Monthly SEO Report", "GBP Activity Log"],
  },

  {
    id: "ACT-017",
    client: "Launchpad Startups",
    contractNumber: "CTR-2025-0009",
    proposalId: "PROP-2025-0009",
    revenue: 11200,
    servicesSold: ["AI Automation", "PPC"],
    departmentsInvolved: ["AI Automation", "Paid Advertising", "Account Management"],
    assignedAM: "Rachel Ng",
    activationStatus: "Launching",
    launchDate: "2025-02-18",
    checklist: [
      { key: "verify_contract",    label: "Verify Contract",             completed: true },
      { key: "verify_payment",     label: "Verify Payment",              completed: true },
      { key: "assign_am",          label: "Assign Account Manager",      completed: true },
      { key: "create_projects",    label: "Create Projects",             completed: true },
      { key: "assign_departments", label: "Assign Departments",          completed: true },
      { key: "blueprints",         label: "Generate Task Blueprints",    completed: false },
      { key: "milestones",         label: "Create Milestones",           completed: false },
      { key: "deliverables",       label: "Create Deliverables",         completed: false },
      { key: "notifications",      label: "Send Internal Notifications", completed: false },
    ],
    salesHandoff: {
      salesOwner: "Danielle Ford",
      servicesSold: ["AI Automation", "PPC"],
      lineItems: ["AI Outreach Automation", "LinkedIn Ads", "Meta Ads"],
      budget: 11200,
      clientGoals: "Automate investor/customer outreach with AI. Drive SaaS signups.",
      clientConcerns: "Runway-sensitive. Needs proven ROI fast.",
      specialRequirements: "HubSpot integration.",
      proposalNotes: "6-month engagement with monthly deliverables.",
      communicationSummary: "4 calls with Founder and Head of Growth.",
    },
    billingHandoff: {
      billingOwner: "Kevin Lam",
      contractStatus: "Signed",
      invoiceStatus: "Paid",
      paymentStatus: "Confirmed",
      billingNotes: "Monthly billing. Auto-pay active.",
      recurringRevenue: 11200,
    },
    amAssignment: {
      primaryAM: "Rachel Ng",
      secondaryAM: "Marcus Rivera",
      executiveSponsor: "James Patel",
    },
    projectGeneration: {
      projectsCreated: 2,
      departmentsAssigned: ["AI Automation", "Paid Advertising"],
      taskBlueprintsGenerated: 0,
      milestonesGenerated: 0,
      dependenciesGenerated: 0,
    },
    launchNotes: "Projects created. Blueprint generation in progress.",
    clientExpectations: "First AI automation deliverable within 2 weeks.",
    scopeNotes: "AI + ads integrated workflow. HubSpot sync.",
    deliverables: [
      "AI Outreach Sequence",
      "HubSpot Integration",
      "LinkedIn Ad Set",
      "Meta Ad Set",
      "Performance Dashboard",
    ],
  },

  {
    id: "ACT-018",
    client: "Redstone Home Services",
    contractNumber: "CTR-2025-0010",
    proposalId: "PROP-2025-0010",
    revenue: 5200,
    servicesSold: ["SEO", "GBP", "Hosting"],
    departmentsInvolved: ["SEO", "GBP", "IT / Hosting", "Account Management"],
    assignedAM: "Marcus Rivera",
    activationStatus: "Pending Payment",
    launchDate: "2025-02-25",
    checklist: [
      { key: "verify_contract",    label: "Verify Contract",             completed: true },
      { key: "verify_payment",     label: "Verify Payment",              completed: false },
      { key: "assign_am",          label: "Assign Account Manager",      completed: false },
      { key: "create_projects",    label: "Create Projects",             completed: false },
      { key: "assign_departments", label: "Assign Departments",          completed: false },
      { key: "blueprints",         label: "Generate Task Blueprints",    completed: false },
      { key: "milestones",         label: "Create Milestones",           completed: false },
      { key: "deliverables",       label: "Create Deliverables",         completed: false },
      { key: "notifications",      label: "Send Internal Notifications", completed: false },
    ],
    salesHandoff: {
      salesOwner: "Tyler Owens",
      servicesSold: ["SEO", "GBP", "Hosting"],
      lineItems: ["Local SEO", "GBP Management", "Managed Hosting"],
      budget: 5200,
      clientGoals: "All-in-one digital presence for HVAC + plumbing services.",
      clientConcerns: "Never done digital marketing before.",
      specialRequirements: "None",
      proposalNotes: "12-month bundled package.",
      communicationSummary: "3 calls.",
    },
    billingHandoff: {
      billingOwner: "Sandra Kim",
      contractStatus: "Signed",
      invoiceStatus: "Sent",
      paymentStatus: "Awaiting",
      billingNotes: "Invoice sent Jan 28. Overdue as of Feb 2.",
      recurringRevenue: 5200,
    },
    amAssignment: {
      primaryAM: "Marcus Rivera",
      secondaryAM: null,
      executiveSponsor: null,
    },
    projectGeneration: {
      projectsCreated: 0,
      departmentsAssigned: [],
      taskBlueprintsGenerated: 0,
      milestonesGenerated: 0,
      dependenciesGenerated: 0,
    },
    launchNotes: "Payment overdue. Billing escalation triggered.",
    clientExpectations: "Ready to start immediately once paid.",
    scopeNotes: "Full local digital bundle.",
    deliverables: ["SEO Report", "GBP Report", "Hosting Dashboard"],
  },

  {
    id: "ACT-019",
    client: "Pinnacle Wealth Advisors",
    contractNumber: "CTR-2025-0011",
    proposalId: "PROP-2025-0011",
    revenue: 16500,
    servicesSold: ["Web Development", "SEO", "AI Automation"],
    departmentsInvolved: ["Web Development", "SEO", "AI Automation", "Account Management"],
    assignedAM: "Jessica Moore",
    activationStatus: "Pending Assignment",
    launchDate: "2025-03-10",
    checklist: [
      { key: "verify_contract",    label: "Verify Contract",             completed: true },
      { key: "verify_payment",     label: "Verify Payment",              completed: true },
      { key: "assign_am",          label: "Assign Account Manager",      completed: false },
      { key: "create_projects",    label: "Create Projects",             completed: false },
      { key: "assign_departments", label: "Assign Departments",          completed: false },
      { key: "blueprints",         label: "Generate Task Blueprints",    completed: false },
      { key: "milestones",         label: "Create Milestones",           completed: false },
      { key: "deliverables",       label: "Create Deliverables",         completed: false },
      { key: "notifications",      label: "Send Internal Notifications", completed: false },
    ],
    salesHandoff: {
      salesOwner: "Danielle Ford",
      servicesSold: ["Web Development", "SEO", "AI Automation"],
      lineItems: ["Wealth Advisor Website", "Financial SEO", "AI Client Onboarding Bot"],
      budget: 16500,
      clientGoals: "Authority positioning, organic lead gen, and automated prospect onboarding.",
      clientConcerns: "Compliance-heavy industry. FINRA considerations.",
      specialRequirements: "Compliance disclaimer management in content.",
      proposalNotes: "Phased delivery. Web first.",
      communicationSummary: "6 calls with Managing Director.",
    },
    billingHandoff: {
      billingOwner: "Kevin Lam",
      contractStatus: "Signed",
      invoiceStatus: "Paid",
      paymentStatus: "Confirmed",
      billingNotes: "Milestone billing. Phase 1 paid.",
      recurringRevenue: 4800,
    },
    amAssignment: {
      primaryAM: "Jessica Moore",
      secondaryAM: null,
      executiveSponsor: "James Patel",
    },
    projectGeneration: {
      projectsCreated: 0,
      departmentsAssigned: [],
      taskBlueprintsGenerated: 0,
      milestonesGenerated: 0,
      dependenciesGenerated: 0,
    },
    launchNotes: "AM assignment pending. High-priority account.",
    clientExpectations: "Kickoff call within 3 business days of assignment.",
    scopeNotes: "Compliance-sensitive content. FINRA review process built in.",
    deliverables: [
      "Wealth Advisor Website",
      "FINRA-Compliant Content",
      "SEO Strategy",
      "AI Onboarding Bot",
    ],
  },

  {
    id: "ACT-020",
    client: "SkyHigh Drone Services",
    contractNumber: "CTR-2025-0012",
    proposalId: "PROP-2025-0012",
    revenue: 7600,
    servicesSold: ["PPC", "GBP", "Web Development"],
    departmentsInvolved: ["Paid Advertising", "GBP", "Web Development", "Account Management"],
    assignedAM: "Lisa Tran",
    activationStatus: "Ready For Launch",
    launchDate: "2025-02-22",
    checklist: [
      { key: "verify_contract",    label: "Verify Contract",             completed: true },
      { key: "verify_payment",     label: "Verify Payment",              completed: true },
      { key: "assign_am",          label: "Assign Account Manager",      completed: true },
      { key: "create_projects",    label: "Create Projects",             completed: true },
      { key: "assign_departments", label: "Assign Departments",          completed: true },
      { key: "blueprints",         label: "Generate Task Blueprints",    completed: true },
      { key: "milestones",         label: "Create Milestones",           completed: true },
      { key: "deliverables",       label: "Create Deliverables",         completed: true },
      { key: "notifications",      label: "Send Internal Notifications", completed: false },
    ],
    salesHandoff: {
      salesOwner: "Tyler Owens",
      servicesSold: ["PPC", "GBP", "Web Development"],
      lineItems: ["Google Ads - Drone Services", "GBP Setup + Management", "Landing Page"],
      budget: 7600,
      clientGoals: "Generate B2B drone inspection contracts from PPC and GBP.",
      clientConcerns: "Niche market. Needs precise targeting.",
      specialRequirements: "FAA compliance messaging in ads.",
      proposalNotes: "Custom landing page tied to PPC.",
      communicationSummary: "3 calls with CEO.",
    },
    billingHandoff: {
      billingOwner: "Sandra Kim",
      contractStatus: "Signed",
      invoiceStatus: "Paid",
      paymentStatus: "Confirmed",
      billingNotes: "Auto-pay active.",
      recurringRevenue: 4200,
    },
    amAssignment: {
      primaryAM: "Lisa Tran",
      secondaryAM: "Rachel Ng",
      executiveSponsor: null,
    },
    projectGeneration: {
      projectsCreated: 3,
      departmentsAssigned: ["Web Development", "Paid Advertising", "GBP"],
      taskBlueprintsGenerated: 16,
      milestonesGenerated: 7,
      dependenciesGenerated: 11,
    },
    launchNotes: "All systems ready. One notification step remaining.",
    clientExpectations: "Full launch by Feb 22.",
    scopeNotes: "Landing page + PPC + GBP activation day 1.",
    deliverables: [
      "Drone Service Landing Page",
      "Google Ads Campaigns",
      "GBP Profile Setup",
      "Monthly Report",
    ],
  },
];

// ── Launch Records ─────────────────────────────────────────────────────────────

export const LAUNCH_RECORDS: LaunchRecord[] = [
  {
    id: "LNC-001",
    client: "Summit Auto Repair",
    services: ["PPC", "SEO"],
    departments: ["Paid Advertising", "SEO"],
    launchDate: "2025-02-01",
    launchStatus: "Launching",
    projectManager: "Jessica Moore",
    blockers: [],
    completionPercent: 72,
  },
  {
    id: "LNC-002",
    client: "Harbor Light Legal",
    services: ["Web Development", "SEO", "PPC"],
    departments: ["Web Development", "SEO", "Paid Advertising"],
    launchDate: "2025-02-10",
    launchStatus: "Upcoming",
    projectManager: "Marcus Rivera",
    blockers: ["Internal notifications pending"],
    completionPercent: 89,
  },
  {
    id: "LNC-003",
    client: "Prestige Med Spa",
    services: ["SEO", "PPC"],
    departments: ["SEO", "Paid Advertising"],
    launchDate: "2025-02-05",
    launchStatus: "Launching",
    projectManager: "Jessica Moore",
    blockers: ["Ad creative in review"],
    completionPercent: 78,
  },
  {
    id: "LNC-004",
    client: "Pacific Rim Trading Co.",
    services: ["PPC", "Web Development"],
    departments: ["Paid Advertising", "Web Development"],
    launchDate: "2025-02-12",
    launchStatus: "Launching",
    projectManager: "Jessica Moore",
    blockers: ["Milestones not yet created"],
    completionPercent: 65,
  },
  {
    id: "LNC-005",
    client: "Ironclad Fitness",
    services: ["SEO", "GBP"],
    departments: ["SEO", "GBP"],
    launchDate: "2025-02-08",
    launchStatus: "Upcoming",
    projectManager: "Rachel Ng",
    blockers: ["Internal notifications pending"],
    completionPercent: 94,
  },
  {
    id: "LNC-006",
    client: "Horizon Solar",
    services: ["SEO", "PPC"],
    departments: ["SEO", "Paid Advertising"],
    launchDate: "2025-02-15",
    launchStatus: "Upcoming",
    projectManager: "Jessica Moore",
    blockers: ["Internal notifications pending"],
    completionPercent: 91,
  },
  {
    id: "LNC-007",
    client: "Launchpad Startups",
    services: ["AI Automation", "PPC"],
    departments: ["AI Automation", "Paid Advertising"],
    launchDate: "2025-02-18",
    launchStatus: "Launching",
    projectManager: "Rachel Ng",
    blockers: ["Task blueprints in progress", "Milestones pending"],
    completionPercent: 55,
  },
  {
    id: "LNC-008",
    client: "SkyHigh Drone Services",
    services: ["PPC", "GBP", "Web Development"],
    departments: ["Paid Advertising", "GBP", "Web Development"],
    launchDate: "2025-02-22",
    launchStatus: "Upcoming",
    projectManager: "Lisa Tran",
    blockers: ["Notification step remaining"],
    completionPercent: 93,
  },
  {
    id: "LNC-009",
    client: "Coastal Plumbing Co.",
    services: ["GBP", "Hosting"],
    departments: ["GBP", "IT / Hosting"],
    launchDate: "2025-02-20",
    launchStatus: "Blocked",
    projectManager: "Rachel Ng",
    blockers: ["Payment not confirmed", "Projects not created"],
    completionPercent: 12,
  },
  {
    id: "LNC-010",
    client: "Redstone Home Services",
    services: ["SEO", "GBP", "Hosting"],
    departments: ["SEO", "GBP", "IT / Hosting"],
    launchDate: "2025-02-25",
    launchStatus: "Blocked",
    projectManager: "Marcus Rivera",
    blockers: ["Invoice overdue", "Payment not received"],
    completionPercent: 8,
  },
  {
    id: "LNC-011",
    client: "Greenfield Dental Group",
    services: ["SEO", "GBP"],
    departments: ["SEO", "GBP"],
    launchDate: "2025-01-15",
    launchStatus: "Active",
    projectManager: "Marcus Rivera",
    blockers: [],
    completionPercent: 100,
  },
  {
    id: "LNC-012",
    client: "Blue Ridge Roofing",
    services: ["SEO", "GBP"],
    departments: ["SEO", "GBP"],
    launchDate: "2024-12-10",
    launchStatus: "Active",
    projectManager: "Marcus Rivera",
    blockers: [],
    completionPercent: 100,
  },
  {
    id: "LNC-013",
    client: "Clearview Optometry",
    services: ["GBP", "Hosting"],
    departments: ["GBP", "IT / Hosting"],
    launchDate: "2024-11-20",
    launchStatus: "Active",
    projectManager: "Lisa Tran",
    blockers: [],
    completionPercent: 100,
  },
  {
    id: "LNC-014",
    client: "Westview Family Medicine",
    services: ["GBP"],
    departments: ["GBP"],
    launchDate: "2024-10-01",
    launchStatus: "Active",
    projectManager: "Lisa Tran",
    blockers: [],
    completionPercent: 100,
  },
  {
    id: "LNC-015",
    client: "Momentum Physical Therapy",
    services: ["GBP", "SEO"],
    departments: ["GBP", "SEO"],
    launchDate: "2024-12-01",
    launchStatus: "Active",
    projectManager: "Lisa Tran",
    blockers: [],
    completionPercent: 100,
  },
  {
    id: "LNC-016",
    client: "Nexus Digital Agency",
    services: ["AI Automation", "Web Development"],
    departments: ["AI Automation", "Web Development"],
    launchDate: "2025-03-01",
    launchStatus: "Onboarding",
    projectManager: "Jessica Moore",
    blockers: ["AM assignment pending"],
    completionPercent: 22,
  },
  {
    id: "LNC-017",
    client: "Grand Vista Hotels",
    services: ["Web Development", "SEO", "PPC", "AI Automation"],
    departments: ["Web Development", "SEO", "Paid Advertising", "AI Automation"],
    launchDate: "2025-03-15",
    launchStatus: "Onboarding",
    projectManager: "Marcus Rivera",
    blockers: ["Contract not signed", "Payment pending"],
    completionPercent: 4,
  },
  {
    id: "LNC-018",
    client: "Apex Consulting Group",
    services: ["AI Automation", "Web Development"],
    departments: ["AI Automation", "Web Development"],
    launchDate: "2025-03-20",
    launchStatus: "Onboarding",
    projectManager: "Marcus Rivera",
    blockers: ["Contract in legal review"],
    completionPercent: 6,
  },
  {
    id: "LNC-019",
    client: "Pinnacle Wealth Advisors",
    services: ["Web Development", "SEO", "AI Automation"],
    departments: ["Web Development", "SEO", "AI Automation"],
    launchDate: "2025-03-10",
    launchStatus: "Onboarding",
    projectManager: "Jessica Moore",
    blockers: ["AM assignment pending"],
    completionPercent: 18,
  },
  {
    id: "LNC-020",
    client: "TechForge Solutions",
    services: ["PPC", "AI Automation"],
    departments: ["Paid Advertising", "AI Automation"],
    launchDate: "2025-02-28",
    launchStatus: "Delayed",
    projectManager: "Rachel Ng",
    blockers: ["Client-requested hold", "Payment pending"],
    completionPercent: 10,
  },
];

// ── AI Launch Summary ─────────────────────────────────────────────────────────

export const AI_LAUNCH_SUMMARY: AILaunchSummary = {
  launchRisks: [
    "2 clients blocked by unconfirmed payment (Coastal Plumbing, Redstone Home Services)",
    "Grand Vista Hotels contract not yet signed — $22,000 at risk",
    "TechForge Solutions on hold — client budget freeze unresolved",
    "Pacific Rim Trading Co. milestone creation overdue with hard Feb 12 deadline",
    "3 launches within 10 days share same project manager (Jessica Moore)",
  ],
  missingRequirements: [
    "Internal notifications not sent for 6 active records",
    "Task blueprints missing for Launchpad Startups and Nexus Digital Agency",
    "Milestones not created for Summit Auto Repair and Pacific Rim Trading Co.",
    "AM not assigned for Nexus Digital Agency and Pinnacle Wealth Advisors",
    "Projects not created for 5 Pending Assignment / Pending Contract records",
  ],
  pendingAssignments: [
    "Nexus Digital Agency — no primary AM assigned",
    "Pinnacle Wealth Advisors — no primary AM assigned",
    "Apex Consulting Group — secondary AM needed for complex delivery",
    "Grand Vista Hotels — department heads not yet briefed",
  ],
  billingIssues: [
    "Coastal Plumbing Co. — invoice sent Jan 20, payment overdue",
    "Redstone Home Services — invoice overdue as of Feb 2, escalation triggered",
    "Grand Vista Hotels — MSA in legal review, billing on hold",
    "TechForge Solutions — invoice not sent, billing paused by client",
    "Apex Consulting Group — contract pending, no invoice issued",
  ],
  recommendedActions: [
    "Escalate Coastal Plumbing and Redstone payment follow-up to billing director immediately",
    "Assign AM to Nexus Digital Agency and Pinnacle Wealth Advisors today to unblock project creation",
    "Complete milestone and deliverable creation for Summit Auto Repair before Feb 1 go-live",
    "Schedule PM capacity review — Jessica Moore has 3 launches in 10-day window",
    "Send internal notifications for all 6 Ready For Launch records",
    "Follow up with Grand Vista Hotels legal team on MSA timeline",
  ],
};

// ── Activation Analytics ──────────────────────────────────────────────────────

export const ACTIVATION_ANALYTICS: ActivationAnalytics = {
  avgTimeToLaunch: 11.4,
  bottlenecks: [
    { stage: "Pending Payment",    avgDays: 5.2, count: 3 },
    { stage: "Pending Assignment", avgDays: 4.1, count: 2 },
    { stage: "Pending Contract",   avgDays: 7.8, count: 2 },
    { stage: "Ready For Launch",   avgDays: 1.9, count: 4 },
    { stage: "Launching",          avgDays: 3.5, count: 4 },
  ],
  departmentDelays: [
    { department: "Paid Advertising", avgDelay: 2.1, cases: 7  },
    { department: "Web Development",  avgDelay: 3.4, cases: 6  },
    { department: "AI Automation",    avgDelay: 2.8, cases: 4  },
    { department: "SEO",              avgDelay: 1.6, cases: 9  },
    { department: "GBP",              avgDelay: 0.9, cases: 8  },
    { department: "IT / Hosting",     avgDelay: 0.7, cases: 3  },
  ],
  revenueWaitingForLaunch: 82900,
  pendingActivations: 14,
};
