import type {
  Integration,
  ClientIntegrationAssignment,
  DepartmentIntegrationAssignment,
  CallIntelligenceMapping,
  WorkflowConnection,
  WebhookEntry,
  AIRecommendation,
} from "./types";

// ─── Mock Integrations (20 total, fully configurable — no hardcoded vendors in logic) ──
export const MOCK_INTEGRATIONS: Integration[] = [
  // ── CRM ───────────────────────────────────────────────────────────────────
  {
    id: "int-001",
    name: "GoHighLevel",
    category: "CRM",
    status: "connected",
    authType: "API Key",
    apiEndpoint: "https://rest.gohighlevel.com/v1",
    owner: "Jordan M.",
    clientsUsing: ["client-001", "client-002", "client-003", "client-004", "client-005"],
    departmentsUsing: ["Sales", "Account Management", "Reporting"],
    lastSync: "2025-01-20T14:32:00Z",
    dataObjects: ["Leads", "Opportunities", "Communications", "Revenue"],
    description: "CRM, pipeline management, and marketing automation.",
    isBuiltIn: false,
    enabled: true,
    errorCount: 0,
    failedRequests: 0,
    healthScore: "excellent",
    healthPercent: 99,
  },
  {
    id: "int-002",
    name: "HubSpot",
    category: "CRM",
    status: "disconnected",
    authType: "OAuth",
    apiEndpoint: "https://api.hubapi.com",
    owner: "Sarah K.",
    clientsUsing: [],
    departmentsUsing: [],
    lastSync: null,
    dataObjects: ["Leads", "Opportunities"],
    description: "Inbound marketing and sales CRM platform.",
    isBuiltIn: false,
    enabled: false,
    errorCount: 0,
    failedRequests: 0,
    healthScore: "fair",
    healthPercent: 0,
  },
  {
    id: "int-003",
    name: "Salesforce",
    category: "CRM",
    status: "pending",
    authType: "OAuth",
    apiEndpoint: "https://login.salesforce.com/services/oauth2/token",
    owner: "Mike T.",
    clientsUsing: ["client-006"],
    departmentsUsing: ["Sales"],
    lastSync: null,
    dataObjects: ["Leads", "Opportunities", "Revenue"],
    description: "Enterprise CRM for large-scale pipeline management.",
    isBuiltIn: false,
    enabled: true,
    errorCount: 2,
    failedRequests: 5,
    healthScore: "fair",
    healthPercent: 42,
  },
  {
    id: "int-004",
    name: "Custom CRM",
    category: "CRM",
    status: "connected",
    authType: "Bearer Token",
    apiEndpoint: "https://api.client-crm.internal/v2",
    owner: "Alex R.",
    clientsUsing: ["client-007", "client-008"],
    departmentsUsing: ["Account Management"],
    lastSync: "2025-01-20T10:00:00Z",
    dataObjects: ["Leads", "Custom Objects"],
    description: "Client-specific custom CRM connector.",
    isBuiltIn: false,
    enabled: true,
    errorCount: 1,
    failedRequests: 3,
    healthScore: "good",
    healthPercent: 87,
  },
  // ── Call Tracking ─────────────────────────────────────────────────────────
  {
    id: "int-005",
    name: "CallRail",
    category: "Call Tracking",
    status: "connected",
    authType: "API Key",
    apiEndpoint: "https://api.callrail.com/v3",
    owner: "Jordan M.",
    clientsUsing: ["client-001", "client-002", "client-003"],
    departmentsUsing: ["Reporting", "Account Management"],
    lastSync: "2025-01-20T15:00:00Z",
    dataObjects: ["Calls", "Leads"],
    description: "Call tracking, recording, and attribution.",
    isBuiltIn: false,
    enabled: true,
    errorCount: 0,
    failedRequests: 0,
    healthScore: "excellent",
    healthPercent: 100,
  },
  {
    id: "int-006",
    name: "WhatConverts",
    category: "Call Tracking",
    status: "connected",
    authType: "API Key",
    apiEndpoint: "https://api.whatconverts.com/v1",
    owner: "Lisa P.",
    clientsUsing: ["client-004", "client-005"],
    departmentsUsing: ["Reporting"],
    lastSync: "2025-01-20T12:10:00Z",
    dataObjects: ["Calls", "Leads", "Opportunities"],
    description: "Lead attribution and call tracking platform.",
    isBuiltIn: false,
    enabled: true,
    errorCount: 0,
    failedRequests: 1,
    healthScore: "good",
    healthPercent: 93,
  },
  {
    id: "int-007",
    name: "Invoca",
    category: "Call Tracking",
    status: "disconnected",
    authType: "API Key",
    apiEndpoint: "https://api.invoca.net/api/2022-01-01",
    owner: "Chris D.",
    clientsUsing: [],
    departmentsUsing: [],
    lastSync: null,
    dataObjects: ["Calls"],
    description: "AI-powered conversation intelligence for calls.",
    isBuiltIn: false,
    enabled: false,
    errorCount: 0,
    failedRequests: 0,
    healthScore: "fair",
    healthPercent: 0,
  },
  // ── Analytics ─────────────────────────────────────────────────────────────
  {
    id: "int-008",
    name: "GA4",
    category: "Analytics",
    status: "connected",
    authType: "OAuth",
    apiEndpoint: "https://analyticsdata.googleapis.com/v1beta",
    owner: "Jordan M.",
    clientsUsing: ["client-001", "client-002", "client-003", "client-004", "client-005", "client-006"],
    departmentsUsing: ["Reporting", "SEO & Local", "Paid Advertising"],
    lastSync: "2025-01-20T15:30:00Z",
    dataObjects: ["Reports", "Leads"],
    description: "Google Analytics 4 — site traffic and conversion data.",
    isBuiltIn: false,
    enabled: true,
    errorCount: 0,
    failedRequests: 0,
    healthScore: "excellent",
    healthPercent: 99,
  },
  {
    id: "int-009",
    name: "Google Search Console",
    category: "Analytics",
    status: "connected",
    authType: "OAuth",
    apiEndpoint: "https://www.googleapis.com/webmasters/v3",
    owner: "Lisa P.",
    clientsUsing: ["client-001", "client-002", "client-003"],
    departmentsUsing: ["SEO & Local", "Reporting"],
    lastSync: "2025-01-20T08:00:00Z",
    dataObjects: ["Reports"],
    description: "Organic search performance and indexing data.",
    isBuiltIn: false,
    enabled: true,
    errorCount: 0,
    failedRequests: 0,
    healthScore: "excellent",
    healthPercent: 98,
  },
  {
    id: "int-010",
    name: "Custom Analytics",
    category: "Analytics",
    status: "error",
    authType: "Bearer Token",
    apiEndpoint: "https://analytics.internal/api/v1",
    owner: "Alex R.",
    clientsUsing: ["client-007"],
    departmentsUsing: ["Reporting"],
    lastSync: "2025-01-18T22:00:00Z",
    dataObjects: ["Reports", "Custom Objects"],
    description: "Internal analytics aggregation service.",
    isBuiltIn: false,
    enabled: true,
    errorCount: 12,
    failedRequests: 34,
    healthScore: "poor",
    healthPercent: 22,
  },
  // ── Advertising ───────────────────────────────────────────────────────────
  {
    id: "int-011",
    name: "Google Ads",
    category: "Advertising",
    status: "connected",
    authType: "OAuth",
    apiEndpoint: "https://googleads.googleapis.com/v14",
    owner: "Mike T.",
    clientsUsing: ["client-001", "client-002", "client-003", "client-004"],
    departmentsUsing: ["Paid Advertising", "Reporting"],
    lastSync: "2025-01-20T15:45:00Z",
    dataObjects: ["Reports", "Revenue", "Leads"],
    description: "Google Ads campaign performance and spend data.",
    isBuiltIn: false,
    enabled: true,
    errorCount: 0,
    failedRequests: 0,
    healthScore: "excellent",
    healthPercent: 100,
  },
  {
    id: "int-012",
    name: "Meta Ads",
    category: "Advertising",
    status: "connected",
    authType: "OAuth",
    apiEndpoint: "https://graph.facebook.com/v18.0",
    owner: "Mike T.",
    clientsUsing: ["client-001", "client-003", "client-005"],
    departmentsUsing: ["Paid Advertising", "Reporting"],
    lastSync: "2025-01-20T15:00:00Z",
    dataObjects: ["Reports", "Revenue", "Leads"],
    description: "Facebook and Instagram advertising data.",
    isBuiltIn: false,
    enabled: true,
    errorCount: 1,
    failedRequests: 2,
    healthScore: "good",
    healthPercent: 91,
  },
  {
    id: "int-013",
    name: "LSA Platform",
    category: "Advertising",
    status: "connected",
    authType: "OAuth",
    apiEndpoint: "https://localservices.googleapis.com/v1",
    owner: "Jordan M.",
    clientsUsing: ["client-002", "client-004"],
    departmentsUsing: ["Local Service Ads", "Reporting"],
    lastSync: "2025-01-20T11:00:00Z",
    dataObjects: ["Leads", "Reports", "Revenue"],
    description: "Google Local Services Ads lead and budget tracking.",
    isBuiltIn: false,
    enabled: true,
    errorCount: 0,
    failedRequests: 0,
    healthScore: "excellent",
    healthPercent: 97,
  },
  {
    id: "int-014",
    name: "GBP Connector",
    category: "Advertising",
    status: "connected",
    authType: "OAuth",
    apiEndpoint: "https://mybusinessbusinessinformation.googleapis.com/v1",
    owner: "Lisa P.",
    clientsUsing: ["client-001", "client-002", "client-003", "client-004", "client-005"],
    departmentsUsing: ["SEO & Local", "Reporting"],
    lastSync: "2025-01-20T09:00:00Z",
    dataObjects: ["Reports"],
    description: "Google Business Profile insights and activity.",
    isBuiltIn: false,
    enabled: true,
    errorCount: 0,
    failedRequests: 0,
    healthScore: "excellent",
    healthPercent: 99,
  },
  {
    id: "int-015",
    name: "Custom Ads Platform",
    category: "Advertising",
    status: "pending",
    authType: "API Key",
    apiEndpoint: "https://ads.custom-platform.io/api/v2",
    owner: "Chris D.",
    clientsUsing: [],
    departmentsUsing: [],
    lastSync: null,
    dataObjects: ["Reports", "Revenue"],
    description: "Custom advertising platform connector (setup in progress).",
    isBuiltIn: false,
    enabled: true,
    errorCount: 0,
    failedRequests: 0,
    healthScore: "fair",
    healthPercent: 0,
  },
  // ── Communication ─────────────────────────────────────────────────────────
  {
    id: "int-016",
    name: "Twilio",
    category: "Communication",
    status: "disconnected",
    authType: "API Key",
    apiEndpoint: "https://api.twilio.com/2010-04-01",
    owner: "Chris D.",
    clientsUsing: [],
    departmentsUsing: [],
    lastSync: null,
    dataObjects: ["Communications", "Calls"],
    description: "SMS, voice, and messaging communication APIs.",
    isBuiltIn: false,
    enabled: false,
    errorCount: 0,
    failedRequests: 0,
    healthScore: "fair",
    healthPercent: 0,
  },
  // ── AI ────────────────────────────────────────────────────────────────────
  {
    id: "int-017",
    name: "OpenAI",
    category: "AI",
    status: "connected",
    authType: "API Key",
    apiEndpoint: "https://api.openai.com/v1",
    owner: "Jordan M.",
    clientsUsing: ["client-001", "client-002", "client-003", "client-004", "client-005", "client-006", "client-007", "client-008"],
    departmentsUsing: ["Reporting", "Sales", "Account Management"],
    lastSync: "2025-01-20T15:59:00Z",
    dataObjects: ["Reports", "Communications"],
    description: "AI summaries, call intelligence, and recommendations.",
    isBuiltIn: false,
    enabled: true,
    errorCount: 0,
    failedRequests: 1,
    healthScore: "excellent",
    healthPercent: 99,
  },
  {
    id: "int-018",
    name: "Anthropic",
    category: "AI",
    status: "pending",
    authType: "API Key",
    apiEndpoint: "https://api.anthropic.com/v1",
    owner: "Sarah K.",
    clientsUsing: [],
    departmentsUsing: [],
    lastSync: null,
    dataObjects: ["Reports"],
    description: "Claude model access for AI-assisted analysis.",
    isBuiltIn: false,
    enabled: false,
    errorCount: 0,
    failedRequests: 0,
    healthScore: "fair",
    healthPercent: 0,
  },
  // ── Storage ───────────────────────────────────────────────────────────────
  {
    id: "int-019",
    name: "Google Drive",
    category: "Storage",
    status: "connected",
    authType: "OAuth",
    apiEndpoint: "https://www.googleapis.com/drive/v3",
    owner: "Sarah K.",
    clientsUsing: ["client-001", "client-002", "client-003"],
    departmentsUsing: ["Content", "Account Management", "Reporting"],
    lastSync: "2025-01-20T14:00:00Z",
    dataObjects: ["Reports", "Projects"],
    description: "File storage, shared documents, and report assets.",
    isBuiltIn: false,
    enabled: true,
    errorCount: 0,
    failedRequests: 0,
    healthScore: "excellent",
    healthPercent: 100,
  },
  // ── Custom API ────────────────────────────────────────────────────────────
  {
    id: "int-020",
    name: "Custom API Connector",
    category: "Custom API",
    status: "connected",
    authType: "Custom",
    apiEndpoint: "https://custom-api.client.io/v1",
    owner: "Alex R.",
    clientsUsing: ["client-008"],
    departmentsUsing: ["IT & Security"],
    lastSync: "2025-01-19T18:00:00Z",
    dataObjects: ["Custom Objects"],
    description: "Configurable connector for any third-party API endpoint.",
    isBuiltIn: false,
    enabled: true,
    errorCount: 3,
    failedRequests: 7,
    healthScore: "good",
    healthPercent: 80,
  },
];

// ─── Client Assignments ───────────────────────────────────────────────────────
export const MOCK_CLIENT_ASSIGNMENTS: ClientIntegrationAssignment[] = [
  {
    clientId: "client-001",
    clientName: "Apex Roofing",
    crmIntegrationId: "int-001",
    callTrackingIntegrationId: "int-005",
    analyticsIntegrationId: "int-008",
    advertisingIntegrationId: "int-011",
    aiIntegrationId: "int-017",
    communicationIntegrationId: null,
  },
  {
    clientId: "client-002",
    clientName: "Summit HVAC",
    crmIntegrationId: "int-001",
    callTrackingIntegrationId: "int-005",
    analyticsIntegrationId: "int-008",
    advertisingIntegrationId: "int-012",
    aiIntegrationId: "int-017",
    communicationIntegrationId: null,
  },
  {
    clientId: "client-003",
    clientName: "Metro Plumbing",
    crmIntegrationId: "int-001",
    callTrackingIntegrationId: "int-005",
    analyticsIntegrationId: "int-008",
    advertisingIntegrationId: "int-011",
    aiIntegrationId: "int-017",
    communicationIntegrationId: null,
  },
  {
    clientId: "client-004",
    clientName: "Blue Ridge Electrical",
    crmIntegrationId: "int-001",
    callTrackingIntegrationId: "int-006",
    analyticsIntegrationId: "int-008",
    advertisingIntegrationId: "int-013",
    aiIntegrationId: "int-017",
    communicationIntegrationId: null,
  },
  {
    clientId: "client-005",
    clientName: "Coastal Landscaping",
    crmIntegrationId: "int-001",
    callTrackingIntegrationId: "int-006",
    analyticsIntegrationId: "int-008",
    advertisingIntegrationId: "int-012",
    aiIntegrationId: "int-017",
    communicationIntegrationId: null,
  },
  {
    clientId: "client-006",
    clientName: "Pinnacle Law Group",
    crmIntegrationId: "int-003",
    callTrackingIntegrationId: null,
    analyticsIntegrationId: "int-008",
    advertisingIntegrationId: "int-011",
    aiIntegrationId: "int-017",
    communicationIntegrationId: null,
  },
  {
    clientId: "client-007",
    clientName: "Harbor Dental",
    crmIntegrationId: "int-004",
    callTrackingIntegrationId: null,
    analyticsIntegrationId: "int-010",
    advertisingIntegrationId: null,
    aiIntegrationId: "int-017",
    communicationIntegrationId: null,
  },
  {
    clientId: "client-008",
    clientName: "Ridgeline Contractors",
    crmIntegrationId: "int-004",
    callTrackingIntegrationId: null,
    analyticsIntegrationId: null,
    advertisingIntegrationId: null,
    aiIntegrationId: "int-017",
    communicationIntegrationId: null,
  },
];

// ─── Department Assignments ───────────────────────────────────────────────────
export const MOCK_DEPARTMENT_ASSIGNMENTS: DepartmentIntegrationAssignment[] = [
  {
    departmentId: "dept-sales",
    departmentName: "Sales",
    connectedIntegrationIds: ["int-001", "int-003", "int-017"],
    reportsConsuming: ["Pipeline Report", "Lead Volume Report", "AI Sales Summary"],
    workflowsConsuming: ["Lead Assignment", "Follow-Up Sequence", "Handoff Trigger"],
  },
  {
    departmentId: "dept-am",
    departmentName: "Account Management",
    connectedIntegrationIds: ["int-001", "int-004", "int-019", "int-017"],
    reportsConsuming: ["Client Health Report", "Renewal Risk Report", "AM Summary"],
    workflowsConsuming: ["Renewal Trigger", "Escalation Routing", "Check-In Automation"],
  },
  {
    departmentId: "dept-reporting",
    departmentName: "Reporting",
    connectedIntegrationIds: ["int-005", "int-006", "int-008", "int-009", "int-010", "int-011", "int-012", "int-013", "int-014", "int-017"],
    reportsConsuming: ["SEO Report", "PPC Report", "LSA Report", "GBP Report", "Executive Dashboard", "Client Dashboard"],
    workflowsConsuming: ["Weekly Report Automation", "Monthly Report Automation", "AI Summary Generation"],
  },
  {
    departmentId: "dept-seo",
    departmentName: "SEO & Local",
    connectedIntegrationIds: ["int-008", "int-009", "int-014"],
    reportsConsuming: ["Organic Traffic Report", "Ranking Report", "GBP Activity Report"],
    workflowsConsuming: ["SEO Task Trigger", "GBP Update Workflow"],
  },
  {
    departmentId: "dept-paid",
    departmentName: "Paid Advertising",
    connectedIntegrationIds: ["int-011", "int-012", "int-008"],
    reportsConsuming: ["Google Ads Report", "Meta Ads Report", "ROAS Dashboard"],
    workflowsConsuming: ["Campaign Budget Alert", "ROAS Drop Alert", "Lead Volume Trigger"],
  },
  {
    departmentId: "dept-lsa",
    departmentName: "Local Service Ads",
    connectedIntegrationIds: ["int-013", "int-005"],
    reportsConsuming: ["LSA Performance Report", "Lead Quality Report"],
    workflowsConsuming: ["LSA Lead Routing", "Dispute Workflow"],
  },
  {
    departmentId: "dept-content",
    departmentName: "Content",
    connectedIntegrationIds: ["int-019"],
    reportsConsuming: ["Content Delivery Report"],
    workflowsConsuming: ["Content Approval Workflow"],
  },
  {
    departmentId: "dept-it",
    departmentName: "IT & Security",
    connectedIntegrationIds: ["int-020"],
    reportsConsuming: ["Integration Health Report", "Security Audit Report"],
    workflowsConsuming: ["Incident Response", "API Key Rotation"],
  },
];

// ─── Call Intelligence Mapping ────────────────────────────────────────────────
export const MOCK_CALL_INTELLIGENCE: CallIntelligenceMapping[] = [
  {
    integrationId: "int-005",
    callProviderIntegrationId: "int-005",
    classifications: [
      {
        id: "cl-001",
        label: "Booked Call",
        type: "booked_call",
        enabled: true,
        keywords: ["appointment", "scheduled", "booked", "confirm"],
      },
      {
        id: "cl-002",
        label: "Qualified Lead",
        type: "qualified_lead",
        enabled: true,
        keywords: ["interested", "quote", "estimate", "price", "how much"],
      },
      {
        id: "cl-003",
        label: "Spam",
        type: "spam",
        enabled: true,
        keywords: ["robocall", "survey", "solicitation"],
      },
      {
        id: "cl-004",
        label: "Existing Client",
        type: "custom",
        enabled: true,
        keywords: ["existing", "account", "my service"],
      },
      {
        id: "cl-005",
        label: "Wrong Number",
        type: "custom",
        enabled: true,
        keywords: ["wrong number", "not looking for"],
      },
    ],
  },
  {
    integrationId: "int-006",
    callProviderIntegrationId: "int-006",
    classifications: [
      {
        id: "cl-006",
        label: "Booked Call",
        type: "booked_call",
        enabled: true,
        keywords: ["booked", "set appointment", "confirmed"],
      },
      {
        id: "cl-007",
        label: "Qualified Lead",
        type: "qualified_lead",
        enabled: true,
        keywords: ["quote needed", "free estimate", "service request"],
      },
      {
        id: "cl-008",
        label: "Spam",
        type: "spam",
        enabled: true,
        keywords: ["survey", "insurance", "warranty"],
      },
    ],
  },
];

// ─── Workflow Connections ─────────────────────────────────────────────────────
export const MOCK_WORKFLOW_CONNECTIONS: WorkflowConnection[] = [
  {
    id: "wf-001",
    workflowName: "New Lead Assignment",
    triggerSource: "Inbound Call",
    dataSource: "Calls",
    connectedIntegrationId: "int-005",
    status: "active",
  },
  {
    id: "wf-002",
    workflowName: "CRM Opportunity Update",
    triggerSource: "Form Submission",
    dataSource: "Leads",
    connectedIntegrationId: "int-001",
    status: "active",
  },
  {
    id: "wf-003",
    workflowName: "Weekly Report Generation",
    triggerSource: "Scheduled (Monday 8AM)",
    dataSource: "Reports",
    connectedIntegrationId: "int-008",
    status: "active",
  },
  {
    id: "wf-004",
    workflowName: "AI Call Summary",
    triggerSource: "Call Completed",
    dataSource: "Calls",
    connectedIntegrationId: "int-017",
    status: "active",
  },
  {
    id: "wf-005",
    workflowName: "ROAS Drop Alert",
    triggerSource: "ROAS < 3.0x",
    dataSource: "Revenue",
    connectedIntegrationId: "int-011",
    status: "active",
  },
  {
    id: "wf-006",
    workflowName: "Client Health Score Update",
    triggerSource: "Daily Sync",
    dataSource: "Reports",
    connectedIntegrationId: "int-001",
    status: "active",
  },
  {
    id: "wf-007",
    workflowName: "Custom Analytics Sync",
    triggerSource: "Hourly",
    dataSource: "Custom Objects",
    connectedIntegrationId: "int-010",
    status: "error",
  },
  {
    id: "wf-008",
    workflowName: "GBP Review Notification",
    triggerSource: "New Review Posted",
    dataSource: "Reports",
    connectedIntegrationId: "int-014",
    status: "paused",
  },
];

// ─── Webhooks ─────────────────────────────────────────────────────────────────
export const MOCK_WEBHOOKS: WebhookEntry[] = [
  {
    id: "wh-001",
    name: "CallRail Inbound Lead",
    integrationId: "int-005",
    providerName: "CallRail",
    status: "active",
    lastEvent: "2025-01-20T15:02:00Z",
    errorCount: 0,
    endpoint: "/api/webhooks/callrail/inbound",
    events: ["call.completed", "call.missed", "form.submitted"],
  },
  {
    id: "wh-002",
    name: "GoHighLevel CRM Sync",
    integrationId: "int-001",
    providerName: "GoHighLevel",
    status: "active",
    lastEvent: "2025-01-20T14:58:00Z",
    errorCount: 0,
    endpoint: "/api/webhooks/ghl/crm-sync",
    events: ["contact.created", "opportunity.updated", "appointment.booked"],
  },
  {
    id: "wh-003",
    name: "Google Ads Conversion",
    integrationId: "int-011",
    providerName: "Google Ads",
    status: "active",
    lastEvent: "2025-01-20T15:30:00Z",
    errorCount: 1,
    endpoint: "/api/webhooks/google-ads/conversion",
    events: ["conversion.recorded"],
  },
  {
    id: "wh-004",
    name: "Custom Analytics Event",
    integrationId: "int-010",
    providerName: "Custom Analytics",
    status: "error",
    lastEvent: "2025-01-18T22:00:00Z",
    errorCount: 12,
    endpoint: "/api/webhooks/custom-analytics/event",
    events: ["data.sync", "report.ready"],
  },
  {
    id: "wh-005",
    name: "WhatConverts Lead",
    integrationId: "int-006",
    providerName: "WhatConverts",
    status: "active",
    lastEvent: "2025-01-20T12:15:00Z",
    errorCount: 0,
    endpoint: "/api/webhooks/whatconverts/lead",
    events: ["lead.received", "call.tracked"],
  },
  {
    id: "wh-006",
    name: "Meta Ads Lead Form",
    integrationId: "int-012",
    providerName: "Meta Ads",
    status: "active",
    lastEvent: "2025-01-20T14:40:00Z",
    errorCount: 2,
    endpoint: "/api/webhooks/meta-ads/lead-form",
    events: ["lead.created"],
  },
];

// ─── AI Recommendations ───────────────────────────────────────────────────────
export const MOCK_AI_RECOMMENDATIONS: AIRecommendation[] = [
  {
    id: "rec-001",
    type: "missing",
    title: "3 clients have no call tracking assigned",
    description:
      "Clients client-006, client-007, and client-008 have no call tracking integration configured. Call attribution data is unavailable for these accounts.",
    affectedIntegrationIds: ["int-005", "int-006"],
    priority: "high",
  },
  {
    id: "rec-002",
    type: "improvement",
    title: "Custom Analytics connector requires attention",
    description:
      "int-010 (Custom Analytics) has 12 errors and 34 failed requests. Health score is 22%. Reconfigure the endpoint or rotate the Bearer Token.",
    affectedIntegrationIds: ["int-010"],
    priority: "high",
  },
  {
    id: "rec-003",
    type: "unused",
    title: "HubSpot integration is disconnected and unused",
    description:
      "HubSpot was added but never connected. If this integration is not needed, disable it to reduce configuration clutter.",
    affectedIntegrationIds: ["int-002"],
    priority: "medium",
  },
  {
    id: "rec-004",
    type: "missing",
    title: "client-008 has no analytics or advertising integration",
    description:
      "Ridgeline Contractors has no analytics or advertising platform connected. Performance data cannot be reported for this client.",
    affectedIntegrationIds: ["int-008", "int-011"],
    priority: "high",
  },
  {
    id: "rec-005",
    type: "redundant",
    title: "Two call tracking providers cover overlapping clients",
    description:
      "CallRail and WhatConverts are both active but serve different client sets. Consider standardizing on one provider to simplify call intelligence mapping.",
    affectedIntegrationIds: ["int-005", "int-006"],
    priority: "low",
  },
  {
    id: "rec-006",
    type: "improvement",
    title: "Salesforce OAuth authorization incomplete",
    description:
      "Salesforce was added for client-006 but OAuth is not yet authorized. Complete the OAuth handshake to activate CRM sync.",
    affectedIntegrationIds: ["int-003"],
    priority: "medium",
  },
  {
    id: "rec-007",
    type: "improvement",
    title: "Enable Anthropic as fallback AI provider",
    description:
      "Anthropic is configured but not yet connected. Setting it as a fallback AI provider improves resilience if OpenAI is unavailable.",
    affectedIntegrationIds: ["int-017", "int-018"],
    priority: "low",
  },
];
